[package]
name = "nsh"
version = "0.5.13"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A POSIX shell as a library"

[lib]
name = "nsh"
path = "src/lib.rs"

[features]
api-sketch = []

[dependencies]
bstr = "1"
libc = "0.2"
nshedit = { git = "https://github.com/necessary-nu/nshedit.git", rev = "cfb16cee5c51144a7a7f1b3574add4dd008a79d4" }
nshedit-plat = { git = "https://github.com/necessary-nu/nshedit.git", rev = "cfb16cee5c51144a7a7f1b3574add4dd008a79d4" }
nshterm = { git = "https://github.com/necessary-nu/nshedit.git", rev = "cfb16cee5c51144a7a7f1b3574add4dd008a79d4" }

[[example]]
name = "embed"
required-features = ["api-sketch"]
