[package]
name = "nsh"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A POSIX shell as a library"

[lib]
name = "nsh"
path = "src/lib.rs"

[dependencies]
bstr = "1"
nsh-platform = { path = "../nsh-platform" }
nshedit = "0.1.0"
nshterm = "0.1.0"

[[example]]
name = "embed"
