[package]
name = "nsh-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "The nsh command-line shell"

[[bin]]
name = "nsh"
path = "src/main.rs"

[dependencies]
bstr = "1"
nsh = { path = "../nsh" }
nsh-platform = { path = "../nsh-platform" }
