//! Waiting for a child, and what its status means.
//!
//! `wait` the built-in, the implicit wait a foreground job gets, and the
//! reaping a shell does between commands are one mechanism with three
//! entry points. What separates them is only whether they block and
//! whether a signal may interrupt them.

use super::*;

/*
 * Wait for job to finish.
 *
 * Under job control we have the problem that while a child process is
 * running interrupts generated by the user are sent to the child but not
 * to the shell.  This means that an infinite loop started by an inter-
 * active user may be hard to kill.  With job control turned off, an
 * interactive user may place an interactive program inside a loop.  If
 * the interactive program catches interrupts, the user doesn't want
 * these interrupts to also abort the loop.  The approach we take here
 * is to have the shell ignore interrupt signals while waiting for a
 * forground process to terminate, and then send itself an interrupt
 * signal if the child process was terminated by an interrupt signal.
 * Unfortunately, some programs want to do a bit of cleanup and then
 * exit on interrupt; unless these processes terminate themselves by
 * sending a signal to themselves (instead of calling exit) they will
 * confuse this approach.
 *
 * Called with interrupts off.
 */

// [spec:dash:sem:jobs.waitforjob-fn]
// [spec:posix:sem:shell.exit-status-collection]
// [spec:posix:req:jobctl.foreground-process-group-restored]
// [spec:posix:req:signal.trap-deferred-until-foreground-command-completes]
// [spec:posix:sem:cmd.async-status-via-wait]
pub fn wait_for_job(
    shell: &mut crate::context::Shell,
    job_id: Option<JobId>,
) -> Result<crate::status::ExitStatus, Error> {
    let mut terminal_error: Option<(&'static [u8], std::io::Error)> = None;

    reap_children(
        shell,
        if job_id.is_some() {
            WaitMode::Block
        } else {
            WaitMode::Poll
        },
        job_id,
    )?;
    let Some(job_id) = job_id else {
        return Ok(shell.status);
    };

    let status = job_exit_status(shell, job_id);
    /* Read while the job is still live: the entry is removed below once
     * it is done, and `${PIPESTATUS[@]}` is the only reader that wants
     * every member rather than the last. */
    // [spec:nsh:req:compat.bash.builtins-special-variables]
    let statuses = pipeline_statuses(shell, job_id);
    crate::variables::special::set_pipeline_status(shell, &statuses);
    if shell.jobs[job_id].job_control {
        if shell.jobs[job_id].is_stopped() {
            let result = shell
                .jobs
                .terminal
                .as_ref()
                .map(nsh_platform::TerminalSettings::capture);
            match result {
                Some(Ok(settings)) => shell.jobs[job_id].terminal_settings = Some(settings),
                Some(Err(error)) => {
                    terminal_error = Some((b"Cannot save job tty settings", error));
                }
                None => {}
            }
        }
        let shell_group = ProcessGroupId::from_leader(shell.root_pid);
        set_terminal_process_group(shell, shell_group)?;
        if shell.jobs[job_id].is_stopped() {
            if let Some(settings) = shell.jobs.shell_terminal_settings.take() {
                let result = shell
                    .jobs
                    .terminal
                    .as_ref()
                    .map(|descriptor| settings.apply(descriptor));
                if let Some(Err(error)) = result {
                    terminal_error = Some((b"Cannot restore shell tty settings", error));
                }
            }
        } else {
            /* A completed foreground utility owns intentional changes made
             * with `stty`. The saved snapshot exists so a suspended job's
             * private modes cannot strand the shell; applying it after a
             * normal exit would erase the utility's successful result. */
            shell.jobs.shell_terminal_settings = None;
        }
        /*
         * This is truly gross.
         * If we're doing job control, then we did a TIOCSPGRP which
         * caused us (the shell) to no longer be in the controlling
         * session -- so we wouldn't have seen any ^C/SIGINT.  So, we
         * intuit from the subprocess exit status whether a SIGINT
         * occurred, and if so interrupt ourselves.  Yuck.  - mycroft
         */
        if shell.jobs[job_id].interrupted {
            if let Err(error) = nsh_platform::raise_signal(nsh_platform::interrupt_signal()) {
                let mut message = b"Cannot raise interrupt (".to_vec();
                message.extend_from_slice(shell.locale.error_message(&error).as_bytes());
                message.push(b')');
                return Err(shell.diagnostics().shell_error(&message));
            }
        }
    }
    if shell.jobs[job_id].is_done() {
        remove_job(&mut shell.interrupt_deferral, &mut shell.jobs, job_id);
    }
    if let Some((operation, error)) = terminal_error {
        return Err(terminal_settings_error(shell, operation, error));
    }
    Ok(status)
}

/*
 * Wait for a process to terminate.
 */

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum WaitOutcome {
    Reaped {
        process: ProcessId,
        status: ChildStatus,
    },
    Interrupted,
    Exhausted,
}

pub(super) fn record_child_status(
    job: &mut Job,
    process: ProcessId,
    status: ChildStatus,
) -> Option<JobState> {
    let child = job
        .processes
        .iter_mut()
        .find(|child| child.process_id == process)?;
    child.status = Some(status);

    let stopped = job.processes.iter().find_map(|child| match child.status {
        Some(status @ ChildStatus::Stopped(_)) => Some(status),
        _ => None,
    });
    job.stop_status = stopped;
    if job.processes.iter().any(|child| child.status.is_none()) {
        Some(JobState::Running)
    } else if stopped.is_some() {
        Some(JobState::Stopped)
    } else {
        Some(JobState::Done)
    }
}

// [spec:dash:sem:jobs.waitone-fn]
// [spec:posix:req:jobctl.suspend-on-catchable-signal]
// [spec:posix:req:jobctl.suspend-on-sigstop]
// [spec:posix:req:builtin.set.opt-b-notify]
fn wait_once(
    shell: &mut crate::context::Shell,
    mode: WaitMode,
    job_id: Option<JobId>,
) -> Result<WaitOutcome, Error> {
    let mut thisjob: Option<JobId> = None;
    let mut state = JobState::Running;
    let mut reported_status = None;

    let waited = crate::error::with_interrupts_deferred(shell, |shell| {
        let waited = wait_for_process(shell, mode, job_id)?;
        if let WaitOutcome::Reaped { process, status } = waited {
            reported_status = Some(status);
            for id in shell.jobs.order_snapshot() {
                if shell.jobs[id].is_done() {
                    continue;
                }
                let Some(next_state) = record_child_status(&mut shell.jobs[id], process, status)
                else {
                    continue;
                };
                thisjob = Some(id);
                state = next_state;
                if next_state != JobState::Running {
                    shell.jobs[id].changed = true;
                    if shell.jobs[id].transition_to(next_state) && next_state == JobState::Stopped {
                        shell.jobs.position_stopped(id);
                    }
                }
                break;
            }
        }
        Ok::<_, Error>(waited)
    })?;

    if thisjob.is_some() && thisjob == job_id {
        let mut message = Vec::new();
        format_process_status(
            &shell.locale,
            &mut message,
            reported_status.expect("a matched job has a reaped status"),
            true,
        );
        if !message.is_empty() {
            message.push(b'\n');
            shell.write_output(OutputDestination::Stderr, &message)?;
        }
    }
    /* A blocking wait can leave an interrupt pending while this structured
     * scope is active. Deliver it only after the caller's prior depth has
     * been restored. */
    if let Some(error) = crate::error::poll_interrupt(shell.interrupt_context()) {
        return Err(error);
    }
    /* A blocking wait for one foreground job can reap a different,
     * background job first.  `-b` makes that completion observable here,
     * before the wait resumes; non-blocking callers already render changed
     * jobs themselves, and a waited-for job is reported by its caller. */
    if let Some(changed_job) = thisjob {
        if notify_completion_now(
            mode,
            state,
            shell.jobs.job_control,
            shell.options.enabled(ShellOption::Notify),
            shell.jobs[changed_job].job_control,
            Some(changed_job) == job_id,
        ) {
            write_job(
                shell,
                OutputDestination::Stderr,
                changed_job,
                JobDisplay::Standard,
            )?;
        }
    }
    Ok(waited)
}

// [spec:dash:sem:jobs.dowait-fn]
pub(crate) fn reap_children(
    shell: &mut crate::context::Shell,
    mode: WaitMode,
    job_id: Option<JobId>,
) -> Result<bool, Error> {
    let child_pending = crate::signal_inbox::signals().child_pending();
    let mut wait_completed: bool;
    let mut waited: WaitOutcome;
    let mut mode = mode;

    if job_id.is_some_and(|index| !shell.jobs[index].is_running()) {
        mode = WaitMode::Poll;
    }

    if mode == WaitMode::Poll && !child_pending {
        return Ok(true);
    }

    wait_completed = true;

    loop {
        waited = wait_once(shell, mode, job_id)?;
        wait_completed &= waited != WaitOutcome::Interrupted;

        mode = mode.after_observation();
        if waited == WaitOutcome::Interrupted
            || job_id.is_some_and(|index| !shell.jobs[index].is_running())
        {
            mode = WaitMode::Poll;
        }
        if waited == WaitOutcome::Exhausted {
            break;
        }
    }

    Ok(wait_completed)
}

/*
 * Do a wait system call.  If block is zero, we return -1 rather than
 * blocking.  If block is DOWAIT_WAITCMD, we return 0 when a signal
 * other than SIGCHLD interrupted the wait.
 *
 * We use sigsuspend in conjunction with a non-blocking wait in
 * order to ensure that waitcmd exits promptly upon the reception
 * of a signal.
 *
 * For code paths other than waitcmd we either use a blocking wait
 * or a non-blocking wait.  For the latter case the caller of dowait
 * must ensure that it is called over and over again until all dead
 * children have been reaped.  Otherwise zombies may linger.
 */

/// What one pass over this shell's own children found.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ChildScan {
    /// One of this shell's children had a status, and it has been taken.
    Reaped {
        process: ProcessId,
        status: ChildStatus,
    },
    /// This shell has children, and none of them has a status waiting.
    NoneReady,
    /// This shell has no children left to wait for.
    NoChildren,
    /// A signal arrived before the wait could answer.
    SignalArrived,
}

/// Give up a reaped child, unless it is still alive to be waited for.
///
/// A stop is reported by a process that is still there and will report
/// again — when it is continued, and when it finally exits — so only a
/// terminal status ends this shell's claim on the pid.
fn release_reaped_child(
    shell: &mut crate::context::Shell,
    process: ProcessId,
    status: ChildStatus,
) {
    if matches!(
        status,
        ChildStatus::Exited(_) | ChildStatus::Signaled { .. }
    ) {
        shell.forked_children.release(process);
    }
}

/// Ask after each of this shell's own children in turn, and take the
/// status of the first that has one.
///
/// The C asks `waitpid(-1)`, which answers with whichever child the
/// operating system likes — including one an embedding host forked and is
/// still holding. Naming the process is what makes the answer this
/// shell's to take.
// [spec:nsh:req:embedding-safety.host-children-are-not-reaped]
fn scan_forked_children(shell: &mut crate::context::Shell, report_stopped: bool) -> ChildScan {
    for process in shell.forked_children.snapshot() {
        match nsh_platform::wait_for_child(process, true, report_stopped) {
            Ok(Some((process, status))) => {
                release_reaped_child(shell, process, status);
                return ChildScan::Reaped { process, status };
            }
            Ok(None) => {}
            Err(error) if error.kind() == std::io::ErrorKind::Interrupted => {
                return ChildScan::SignalArrived;
            }
            /* The only way a child of this shell stops being waitable is
             * that something else has reaped it, and a status that has
             * been taken cannot be taken again. */
            Err(_) => shell.forked_children.release(process),
        }
    }
    if shell.forked_children.is_empty() {
        ChildScan::NoChildren
    } else {
        ChildScan::NoneReady
    }
}

/// A process of the job the caller is waiting for which has not reported
/// yet, and so the one whose completion can end that wait.
fn unfinished_process(shell: &crate::context::Shell, job_id: Option<JobId>) -> Option<ProcessId> {
    shell.jobs[job_id?]
        .processes
        .iter()
        .find(|child| child.status.is_none())
        .map(|child| child.process_id)
}

/// Block until one named child of this shell reports.
///
/// Naming one process rather than blocking on all of them is what the
/// operating system offers; the rest are not lost, because a shell that
/// catches `SIGCHLD` without `SA_RESTART` has this wait interrupted when
/// any of its children changes state, and the caller rescans.
fn block_for_child(
    shell: &mut crate::context::Shell,
    target: ProcessId,
    report_stopped: bool,
) -> ChildScan {
    match nsh_platform::wait_for_child(target, false, report_stopped) {
        Ok(Some((process, status))) => {
            release_reaped_child(shell, process, status);
            ChildScan::Reaped { process, status }
        }
        /* A blocking wait has no "not yet" answer; treating it as one
         * costs a rescan and cannot loop, because the scan that follows
         * asks the same question. */
        Ok(None) => ChildScan::NoneReady,
        Err(error) if error.kind() == std::io::ErrorKind::Interrupted => ChildScan::SignalArrived,
        Err(_) => {
            shell.forked_children.release(target);
            ChildScan::NoneReady
        }
    }
}

/// Block until the process substitution `wait` with no operands blocks
/// on has reported.
///
/// `false` reports a signal that arrived first, which is the answer the
/// job loop gives for the same interruption.
///
/// By name, and by *that* name: the generic reaper would come to rest on
/// whichever child of this shell reported first, and a here-document
/// writer, a command substitution and a background job are none of them
/// what `wait` was told to wait for.
// [spec:nsh:req:compat.bash.process-substitution]
pub(crate) fn wait_for_process_substitution(
    shell: &mut crate::context::Shell,
) -> Result<bool, Error> {
    while let Some(target) = shell.last_process_substitution {
        if let ChildScan::SignalArrived = block_for_child(shell, target, false) {
            if let Some(error) = crate::error::poll_interrupt(shell.interrupt_context()) {
                return Err(error);
            }
            if crate::signal_inbox::signals().pending_signal().is_some() {
                return Ok(false);
            }
            continue;
        }
        /* Whatever else came back, this pid is not one to wait for
         * again: it reported, or the operating system says it is not
         * ours to reap. */
        shell.last_process_substitution = None;
    }
    Ok(true)
}

// [spec:dash:sem:jobs.waitproc-fn]
// [spec:nsh:req:embedding-safety.host-children-are-not-reaped]
fn wait_for_process(
    shell: &mut crate::context::Shell,
    mode: WaitMode,
    job_id: Option<JobId>,
) -> Result<WaitOutcome, Error> {
    let report_stopped = shell.jobs.job_control;
    let signals = crate::signal_inbox::signals();

    loop {
        signals.set_child_pending(false);
        let mut scanned = scan_forked_children(shell, report_stopped);
        if scanned == ChildScan::NoneReady && !mode.kernel_nonblocking() {
            /* The blocking caller wants a status rather than an answer,
             * so come to rest on a process of the job it asked about —
             * any other choice can outlive the wait it was meant to end. */
            let preferred = unfinished_process(shell, job_id);
            scanned = match shell.forked_children.blocking_target(preferred) {
                Some(target) => block_for_child(shell, target, report_stopped),
                None => ChildScan::NoChildren,
            };
        }

        match scanned {
            ChildScan::Reaped { process, status } => {
                return Ok(WaitOutcome::Reaped { process, status });
            }
            ChildScan::NoChildren => return Ok(WaitOutcome::Exhausted),
            ChildScan::SignalArrived => {
                /* One of the three EINTR sites the C retries blindly, and
                 * the one that matters for a ^C during a foreground
                 * command that does not itself die of it. */
                if let Some(error) = crate::error::poll_interrupt(shell.interrupt_context()) {
                    return Err(error);
                }
                continue;
            }
            /* Only the blocking arm can arrive here without an answer,
             * and only because the child it came to rest on stopped being
             * this shell's between the scan and the wait. The set has one
             * fewer member than it did, so the next pass asks a strictly
             * smaller question and cannot circle. */
            ChildScan::NoneReady if !mode.kernel_nonblocking() => continue,
            ChildScan::NoneReady => {}
        }

        if !mode.suspends_for_signal() {
            return Ok(WaitOutcome::Exhausted);
        }

        let blocked =
            nsh_platform::BlockedSignals::all().expect("blocking signals around child wait failed");

        while !signals.child_pending() && signals.pending_signal().is_none() {
            if let Err(error) = blocked.suspend() {
                let mut message = b"Cannot wait for signal (".to_vec();
                message.extend_from_slice(shell.locale.error_message(&error).as_bytes());
                message.push(b')');
                return Err(shell.diagnostics().shell_error(&message));
            }
        }

        drop(blocked);

        if !signals.child_pending() {
            return Ok(WaitOutcome::Interrupted);
        }
    }
}

/*
 * return 1 if there are stopped jobs, otherwise 0
 */

// [spec:dash:sem:jobs.stoppedjobs-fn]
pub fn has_stopped_jobs(shell: &mut crate::context::Shell) -> Result<bool, Error> {
    if shell.jobs.job_warning != JobWarning::Ready {
        return Ok(false);
    }
    if shell
        .jobs
        .current()
        .is_some_and(|id| shell.jobs[id].is_stopped())
    {
        shell.write_output(OutputDestination::Stderr, b"You have stopped jobs.\n")?;
        shell.jobs.job_warning = JobWarning::Reported;
        Ok(true)
    } else {
        Ok(false)
    }
}
