//! Literal port of `src/parser.c` / `src/parser.h`.
//! Rules: `docs/spec/port/src/parser.md`.
//!
//! The shell command parser.  This is a 1:1 transcription of the C: the
//! same functions, the same control flow, the same side-effect order and
//! the same bugs.  `readtoken1` in particular keeps the C shape — one
//! function whose "internal subroutines" (`checkend`, `parseredir`,
//! `parsesub`, `parsebackq`, `parsearith`) are reached by `goto` in C and
//! are plain functions taking the shared state by `&mut` here.

use core::mem;
use core::ptr;
use core::ptr::addr_of_mut;

use libc::{c_char, c_int, c_uint, c_void};

use crate::error::{errlinno, handler, jmploc};
use crate::expand::{expandarg, restore_handler_expandarg, rmescapes, EXP_QUOTED};
use crate::input::{
    pgetc, pgetc_eoa, popfile, pungetc, pungetn, pushstring, setinputstring, unwindfiles,
    whichprompt, PEOA,
};
use crate::memalloc::{grabstackblock, popstackmark, pushstackmark, stackmark, stalloc, stnputs};
use crate::output::{fmtstr, VaArg};
use crate::nodes::{
    narg, nbinary, ncase, nclist, ncmd, nfile, nfor, nhere, nif, nnot, node, nodelist, npipe,
    nredir, NAND, NAPPEND, NARG, NBACKGND, NCASE, NCLIST, NCLOBBER, NCMD, NDEFUN, NFOR, NFROM,
    NFROMFD, NFROMTO, NHERE, NIF, NNOT, NOR, NPIPE, NREDIR, NSEMI, NSUBSHELL, NTO, NTOFD,
    NUNTIL, NWHILE, NXHERE,
};
use crate::syntax::{
    digit_val, is_digit, is_in_name, is_name, is_special, syntax_at, Syntax, CBACK, CBQUOTE,
    CCTL, CDQUOTE, CENDQUOTE, CENDVAR, CEOF, CLP, CNL, CRP, CSQUOTE, CVAR, CWORD, PEOF,
};

// ---------------------------------------------------------------------
// Local transcriptions of the C macros this file uses.
// ---------------------------------------------------------------------

/// `#define equal(s1, s2) (strcmp(s1, s2) == 0)` — src/mystring.h
macro_rules! equal {
    ($s1:expr, $s2:expr) => {
        libc::strcmp($s1, $s2) == 0
    };
}

/// `MB_LEN_MAX` from `<limits.h>` (16 on the platforms dash targets).
const MB_LEN_MAX: usize = 16;

/// `#define stackblock() ((void *)stacknxt)` — src/memalloc.h
unsafe fn stackblock() -> *mut c_char {
    crate::memalloc::stackblock() as *mut c_char
}

/// `#define stackblocksize() stacknleft` — src/memalloc.h
unsafe fn stackblocksize() -> usize {
    crate::memalloc::stackblocksize()
}

/// `#define grabstackstr(p) stalloc((char *)(p) - (char *)stackblock())`
unsafe fn grabstackstr(p: *mut c_char) -> *mut c_char {
    crate::memalloc::grabstackstr(p) as *mut c_char
}

/*
 * The four syntax tables, as the *table pointers* `synstack->syntax`
 * carries around.  `syntax.h` spells them `basesyntax + SYNBASE` etc.;
 * Rust cannot form an interior pointer that is indexed negatively, so the
 * SYNBASE offset stays inside `syntax_at` and what travels is a pointer
 * to the whole table.  Pointer identity is what `readtoken1` compares.
 */

/// `#define BASESYNTAX (basesyntax + SYNBASE)`
fn BASESYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::basesyntax)
}

/// `#define DQSYNTAX (dqsyntax + SYNBASE)`
fn DQSYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::dqsyntax)
}

/// `#define SQSYNTAX (sqsyntax + SYNBASE)`
fn SQSYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::sqsyntax)
}

/// `#define ARISYNTAX (arisyntax + SYNBASE)`
fn ARISYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::arisyntax)
}

/// `syntax[c]` for a table held in a variable.
unsafe fn syn_at(tab: *const Syntax, c: c_int) -> c_int {
    syntax_at(&*tab, c) as c_int
}

// ---------------------------------------------------------------------
// src/token.h (generated by mktokens): values returned by readtoken.
// ---------------------------------------------------------------------

pub const TEOF: c_int = 0;
pub const TBLANK: c_int = 1;
pub const TNL: c_int = 2;
pub const TSEMI: c_int = 3;
pub const TBACKGND: c_int = 4;
pub const TAND: c_int = 5;
pub const TOR: c_int = 6;
pub const TPIPE: c_int = 7;
pub const TLP: c_int = 8;
pub const TRP: c_int = 9;
pub const TENDCASE: c_int = 10;
pub const TENDBQUOTE: c_int = 11;
pub const TREDIR: c_int = 12;
pub const TWORD: c_int = 13;
pub const TNOT: c_int = 14;
pub const TCASE: c_int = 15;
pub const TDO: c_int = 16;
pub const TDONE: c_int = 17;
pub const TELIF: c_int = 18;
pub const TELSE: c_int = 19;
pub const TESAC: c_int = 20;
pub const TFI: c_int = 21;
pub const TFOR: c_int = 22;
pub const TIF: c_int = 23;
pub const TIN: c_int = 24;
pub const TTHEN: c_int = 25;
pub const TUNTIL: c_int = 26;
pub const TWHILE: c_int = 27;
pub const TBEGIN: c_int = 28;
pub const TEND: c_int = 29;

// ---------------------------------------------------------------------
// src/token_vars.h (generated by mktokens), included by parser.c.
// ---------------------------------------------------------------------

/// Array indicating which tokens mark the end of a list.
static tokendlist: [c_char; 30] = [
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
];

/// A table of `const char *` needs a `Sync` wrapper to live in a plain
/// `static`; the contents are exactly the generated C arrays.
struct CStrTable<const N: usize>([*const c_char; N]);
unsafe impl<const N: usize> Sync for CStrTable<N> {}

static tokname: CStrTable<30> = CStrTable([
    c"end of file".as_ptr(),
    c"blank".as_ptr(),
    c"newline".as_ptr(),
    c"\";\"".as_ptr(),
    c"\"&\"".as_ptr(),
    c"\"&&\"".as_ptr(),
    c"\"||\"".as_ptr(),
    c"\"|\"".as_ptr(),
    c"\"(\"".as_ptr(),
    c"\")\"".as_ptr(),
    c"\";;\"".as_ptr(),
    c"\"`\"".as_ptr(),
    c"redirection".as_ptr(),
    c"word".as_ptr(),
    c"\"!\"".as_ptr(),
    c"\"case\"".as_ptr(),
    c"\"do\"".as_ptr(),
    c"\"done\"".as_ptr(),
    c"\"elif\"".as_ptr(),
    c"\"else\"".as_ptr(),
    c"\"esac\"".as_ptr(),
    c"\"fi\"".as_ptr(),
    c"\"for\"".as_ptr(),
    c"\"if\"".as_ptr(),
    c"\"in\"".as_ptr(),
    c"\"then\"".as_ptr(),
    c"\"until\"".as_ptr(),
    c"\"while\"".as_ptr(),
    c"\"{\"".as_ptr(),
    c"\"}\"".as_ptr(),
]);

pub const KWDOFFSET: c_int = 14;

static parsekwd: CStrTable<16> = CStrTable([
    c"!".as_ptr(),
    c"case".as_ptr(),
    c"do".as_ptr(),
    c"done".as_ptr(),
    c"elif".as_ptr(),
    c"else".as_ptr(),
    c"esac".as_ptr(),
    c"fi".as_ptr(),
    c"for".as_ptr(),
    c"if".as_ptr(),
    c"in".as_ptr(),
    c"then".as_ptr(),
    c"until".as_ptr(),
    c"while".as_ptr(),
    c"{".as_ptr(),
    c"}".as_ptr(),
]);

// ---------------------------------------------------------------------
// src/parser.h
// ---------------------------------------------------------------------

/* control characters in argument strings */
pub const CTL_FIRST: c_int = -127; /* first 'special' character */
pub const CTLESC: c_int = -127; /* escape next character */
pub const CTLVAR: c_int = -126; /* variable defn */
pub const CTLENDVAR: c_int = -125;
pub const CTLBACKQ: c_int = -124;
pub const CTLMBCHAR: c_int = -123;
pub const CTLARI: c_int = -122; /* arithmetic expression */
pub const CTLENDARI: c_int = -121;
pub const CTLQUOTEMARK: c_int = -120;
pub const CTL_LAST: c_int = -120; /* last 'special' character */

/* variable substitution byte (follows CTLVAR) */
pub const VSTYPE: c_int = 0x0f; /* type of variable substitution */
pub const VSNUL: c_int = 0x10; /* colon--treat the empty string as unset */
pub const VSBIT: c_int = 0x20; /* Ensure subtype is not zero */

/* values of VSTYPE field */
pub const VSNORMAL: c_int = 0x1; /* normal variable:  $var or ${var} */
pub const VSMINUS: c_int = 0x2; /* ${var-text} */
pub const VSPLUS: c_int = 0x3; /* ${var+text} */
pub const VSQUESTION: c_int = 0x4; /* ${var?message} */
pub const VSASSIGN: c_int = 0x5; /* ${var=text} */
pub const VSTRIMRIGHT: c_int = 0x6; /* ${var%pattern} */
pub const VSTRIMRIGHTMAX: c_int = 0x7; /* ${var%%pattern} */
pub const VSTRIMLEFT: c_int = 0x8; /* ${var#pattern} */
pub const VSTRIMLEFTMAX: c_int = 0x9; /* ${var##pattern} */
pub const VSLENGTH: c_int = 0xa; /* ${#var} */
/* VSLENGTH must come last. */

/* values of checkkwd variable */
pub const CHKALIAS: c_int = 0x1;
pub const CHKKWD: c_int = 0x2;
pub const CHKNL: c_int = 0x4;
pub const CHKEOFMARK: c_int = 0x8;

/// `#define NEOF ((union node *)&tokpushback)`
pub unsafe fn NEOF() -> *mut node {
    addr_of_mut!(tokpushback) as *mut node
}

/// Used by expandstr to get here-doc like behaviour:
/// `#define FAKEEOFMARK (char *)1`
fn FAKEEOFMARK() -> *mut c_char {
    1 as *mut c_char
}

// ---------------------------------------------------------------------

// [spec:dash:def:parser.heredoc]
#[repr(C)]
pub struct heredoc {
    pub next: *mut heredoc,   /* next here document in list */
    pub here: *mut node,      /* redirection node */
    pub eofmark: *mut c_char, /* string indicating end of input */
    pub striptabs: c_int,     /* if set, strip leading tabs */
}

// [spec:dash:def:parser.synstack]
#[repr(C)]
pub struct synstack {
    pub syntax: *const Syntax,
    pub prev: *mut synstack,
    pub next: *mut synstack,
    pub innerdq: c_int,
    pub varpushed: c_int,
    pub dblquote: c_int,
    pub backq: c_int,      /* Inside back quotes (here-doc word only). */
    pub varnest: c_int,    /* levels of variables expansion */
    pub parenlevel: c_int, /* levels of parens in arithmetic */
    pub dqvarnest: c_int,  /* levels of variables expansion within double quotes */
}

pub static mut heredoclist: *mut heredoc = ptr::null_mut(); /* list of here documents to read */
pub static mut doprompt: c_int = 0; /* if set, prompt the user */
pub static mut needprompt: c_int = 0; /* true if interactive and at start of line */
pub static mut lasttoken: c_int = 0; /* last token read */
pub static mut tokpushback: c_int = 0; /* last token pushed back */
pub static mut wordtext: *mut c_char = ptr::null_mut(); /* text of last word */
pub static mut checkkwd: c_int = 0;
pub static mut backquotelist: *mut nodelist = ptr::null_mut();
pub static mut redirnode: *mut node = ptr::null_mut();
pub static mut heredoc: *mut heredoc = ptr::null_mut();
pub static mut quoteflag: c_int = 0; /* set if (part of) last token was quoted */

// [spec:dash:def:parser.isassignment-fn]
// [spec:dash:sem:parser.isassignment-fn]
pub unsafe fn isassignment(p: *const c_char) -> c_int {
    let q = endofname(p);
    if p == q as *const c_char {
        return 0;
    }
    (*q == '=' as c_char) as c_int
}

// [spec:dash:def:parser.issimplecmd-fn]
// [spec:dash:sem:parser.issimplecmd-fn]
pub unsafe fn issimplecmd(n: *mut node, name: *const c_char) -> c_int {
    (!n.is_null()
        && (*n).r#type == NCMD
        && !(*n).ncmd.args.is_null()
        && equal!((*(*n).ncmd.args).narg.text, name)) as c_int
}

// [spec:dash:def:parser.realeofmark-fn]
// [spec:dash:sem:parser.realeofmark-fn]
unsafe fn realeofmark(eofmark: *const c_char) -> c_int {
    (!eofmark.is_null() && eofmark != FAKEEOFMARK() as *const c_char) as c_int
}

/*
 * Read and parse a command.  Returns NEOF on end of file.  (NULL is a
 * valid parse tree indicating a blank line.)
 */

// [spec:dash:def:parser.parsecmd-fn]
// [spec:dash:sem:parser.parsecmd-fn]
pub unsafe fn parsecmd(interact: c_int) -> *mut node {
    tokpushback = 0;
    checkkwd = 0;
    heredoclist = ptr::null_mut();
    doprompt = interact;
    if doprompt != 0 {
        setprompt(doprompt);
    }
    needprompt = 0;
    list(1)
}

// [spec:dash:def:parser.list-fn]
// [spec:dash:sem:parser.list-fn]
unsafe fn list(nlflag: c_int) -> *mut node {
    let mut nlflag = nlflag;
    let chknl = if nlflag & 1 != 0 { 0 } else { CHKNL };
    let mut n1: *mut node;
    let mut n2: *mut node;
    let mut tok: c_int;

    n1 = ptr::null_mut();
    loop {
        checkkwd = chknl | CHKKWD | CHKALIAS;
        tok = readtoken();
        match tok {
            TNL => {
                parseheredoc();
                return n1;
            }

            TEOF => {
                if n1.is_null() && chknl == 0 {
                    n1 = NEOF();
                }
                /* out_eof: */
                parseheredoc();
                tokpushback += 1;
                lasttoken = TEOF;
                return n1;
            }
            _ => {}
        }

        tokpushback += 1;
        if nlflag == 2 && tokendlist[tok as usize] != 0 {
            return n1;
        }
        nlflag |= 2;

        n2 = andor();
        tok = readtoken();
        if tok == TBACKGND {
            if (*n2).r#type == NPIPE {
                (*n2).npipe.backgnd = 1;
            } else {
                if (*n2).r#type != NREDIR {
                    let n3 = stalloc(mem::size_of::<nredir>()) as *mut node;
                    (*n3).nredir.n = n2;
                    (*n3).nredir.redirect = ptr::null_mut();
                    n2 = n3;
                }
                (*n2).r#type = NBACKGND;
            }
        }
        if n1.is_null() {
            n1 = n2;
        } else {
            let n3 = stalloc(mem::size_of::<nbinary>()) as *mut node;
            (*n3).r#type = NSEMI;
            (*n3).nbinary.ch1 = n1;
            (*n3).nbinary.ch2 = n2;
            n1 = n3;
        }
        match tok {
            TEOF => {
                /* goto out_eof */
                parseheredoc();
                tokpushback += 1;
                lasttoken = TEOF;
                return n1;
            }
            TNL => {
                tokpushback += 1;
                /* fall through */
            }
            TBACKGND | TSEMI => {}
            _ => {
                if chknl == 0 {
                    synexpect(-1);
                }
                tokpushback += 1;
                return n1;
            }
        }
    }
}

// [spec:dash:def:parser.andor-fn]
// [spec:dash:sem:parser.andor-fn]
unsafe fn andor() -> *mut node {
    let mut n1: *mut node;
    let mut t: c_int;

    n1 = pipeline();
    loop {
        t = readtoken();
        if t == TAND {
            t = NAND;
        } else if t == TOR {
            t = NOR;
        } else {
            tokpushback += 1;
            return n1;
        }
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        let n2 = pipeline();
        let n3 = stalloc(mem::size_of::<nbinary>()) as *mut node;
        (*n3).r#type = t;
        (*n3).nbinary.ch1 = n1;
        (*n3).nbinary.ch2 = n2;
        n1 = n3;
    }
}

// [spec:dash:def:parser.pipeline-fn]
// [spec:dash:sem:parser.pipeline-fn]
unsafe fn pipeline() -> *mut node {
    let mut n1: *mut node;
    let n2: *mut node;
    let pipenode: *mut node;
    let mut lp: *mut nodelist;
    let mut prev: *mut nodelist;
    let mut negate: c_int;

    negate = 0;
    /* TRACE(("pipeline: entered\n")); */
    if readtoken() == TNOT {
        negate = (negate == 0) as c_int;
        checkkwd = CHKKWD | CHKALIAS;
    } else {
        tokpushback += 1;
    }
    n1 = command();
    if readtoken() == TPIPE {
        pipenode = stalloc(mem::size_of::<npipe>()) as *mut node;
        (*pipenode).r#type = NPIPE;
        (*pipenode).npipe.backgnd = 0;
        lp = stalloc(mem::size_of::<nodelist>()) as *mut nodelist;
        (*pipenode).npipe.cmdlist = lp;
        (*lp).n = n1;
        loop {
            prev = lp;
            lp = stalloc(mem::size_of::<nodelist>()) as *mut nodelist;
            checkkwd = CHKNL | CHKKWD | CHKALIAS;
            (*lp).n = command();
            (*prev).next = lp;
            if readtoken() != TPIPE {
                break;
            }
        }
        (*lp).next = ptr::null_mut();
        n1 = pipenode;
    }
    tokpushback += 1;
    if negate != 0 {
        n2 = stalloc(mem::size_of::<nnot>()) as *mut node;
        (*n2).r#type = NNOT;
        (*n2).nnot.com = n1;
        n2
    } else {
        n1
    }
}

// [spec:dash:def:parser.command-fn]
// [spec:dash:sem:parser.command-fn]
unsafe fn command() -> *mut node {
    let mut n1: *mut node;
    let mut n2: *mut node;
    let mut ap: *mut node = ptr::null_mut();
    let mut app: *mut *mut node;
    let mut cp: *mut node;
    let mut cpp: *mut *mut node;
    let mut redir: *mut node;
    let mut rpp: *mut *mut node;
    let rpp2: *mut *mut node;
    let mut t: c_int;
    let savelinno: c_int;

    redir = ptr::null_mut();
    rpp2 = &mut redir as *mut *mut node;

    savelinno = crate::plinno!();

    let mut goto_redir = false;
    let tok = readtoken();
    if tok == TIF {
        n1 = stalloc(mem::size_of::<nif>()) as *mut node;
        (*n1).r#type = NIF;
        (*n1).nif.test = list(0);
        if readtoken() != TTHEN {
            synexpect(TTHEN);
        }
        (*n1).nif.ifpart = list(0);
        n2 = n1;
        while readtoken() == TELIF {
            (*n2).nif.elsepart = stalloc(mem::size_of::<nif>()) as *mut node;
            n2 = (*n2).nif.elsepart;
            (*n2).r#type = NIF;
            (*n2).nif.test = list(0);
            if readtoken() != TTHEN {
                synexpect(TTHEN);
            }
            (*n2).nif.ifpart = list(0);
        }
        if lasttoken == TELSE {
            (*n2).nif.elsepart = list(0);
        } else {
            (*n2).nif.elsepart = ptr::null_mut();
            tokpushback += 1;
        }
        t = TFI;
    } else if tok == TWHILE || tok == TUNTIL {
        let got: c_int;
        n1 = stalloc(mem::size_of::<nbinary>()) as *mut node;
        (*n1).r#type = if lasttoken == TWHILE { NWHILE } else { NUNTIL };
        (*n1).nbinary.ch1 = list(0);
        got = readtoken();
        if got != TDO {
            synexpect(TDO);
        }
        (*n1).nbinary.ch2 = list(0);
        t = TDONE;
    } else if tok == TFOR {
        if readtoken() != TWORD || quoteflag != 0 || goodname(wordtext) == 0 {
            synerror(c"Bad for loop variable".as_ptr());
        }
        n1 = stalloc(mem::size_of::<nfor>()) as *mut node;
        (*n1).r#type = NFOR;
        (*n1).nfor.linno = savelinno;
        (*n1).nfor.var = wordtext;
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() == TIN {
            app = &mut ap as *mut *mut node;
            while readtoken() == TWORD {
                n2 = stalloc(mem::size_of::<narg>()) as *mut node;
                (*n2).r#type = NARG;
                (*n2).narg.text = wordtext;
                (*n2).narg.backquote = backquotelist;
                *app = n2;
                app = addr_of_mut!((*n2).narg.next);
            }
            *app = ptr::null_mut();
            (*n1).nfor.args = ap;
            if lasttoken != TNL && lasttoken != TSEMI {
                synexpect(-1);
            }
        } else {
            n2 = stalloc(mem::size_of::<narg>()) as *mut node;
            (*n2).r#type = NARG;
            (*n2).narg.text =
                ptr::addr_of!(crate::mystring::dolatstr) as *const c_char as *mut c_char;
            (*n2).narg.backquote = ptr::null_mut();
            (*n2).narg.next = ptr::null_mut();
            (*n1).nfor.args = n2;
            /*
             * Newline or semicolon here is optional (but note
             * that the original Bourne shell only allowed NL).
             */
            if lasttoken != TSEMI {
                tokpushback += 1;
            }
        }
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() != TDO {
            synexpect(TDO);
        }
        (*n1).nfor.body = list(0);
        t = TDONE;
    } else if tok == TCASE {
        n1 = stalloc(mem::size_of::<ncase>()) as *mut node;
        (*n1).r#type = NCASE;
        (*n1).ncase.linno = savelinno;
        if readtoken() != TWORD {
            synexpect(TWORD);
        }
        n2 = stalloc(mem::size_of::<narg>()) as *mut node;
        (*n1).ncase.expr = n2;
        (*n2).r#type = NARG;
        (*n2).narg.text = wordtext;
        (*n2).narg.backquote = backquotelist;
        (*n2).narg.next = ptr::null_mut();
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() != TIN {
            synexpect(TIN);
        }
        cpp = addr_of_mut!((*n1).ncase.cases);
        'next_case: loop {
            checkkwd = CHKNL | CHKKWD;
            t = readtoken();
            while t != TESAC {
                if lasttoken == TLP {
                    readtoken();
                }
                cp = stalloc(mem::size_of::<nclist>()) as *mut node;
                *cpp = cp;
                (*cp).r#type = NCLIST;
                app = addr_of_mut!((*cp).nclist.pattern);
                loop {
                    if lasttoken < TWORD {
                        synexpect(TWORD);
                    }
                    ap = stalloc(mem::size_of::<narg>()) as *mut node;
                    *app = ap;
                    (*ap).r#type = NARG;
                    (*ap).narg.text = wordtext;
                    (*ap).narg.backquote = backquotelist;
                    if readtoken() != TPIPE {
                        break;
                    }
                    app = addr_of_mut!((*ap).narg.next);
                    readtoken();
                }
                (*ap).narg.next = ptr::null_mut();
                if lasttoken != TRP {
                    synexpect(TRP);
                }
                (*cp).nclist.body = list(2);

                cpp = addr_of_mut!((*cp).nclist.next);

                checkkwd = CHKNL | CHKKWD;
                t = readtoken();
                if t != TESAC {
                    if t != TENDCASE {
                        synexpect(TENDCASE);
                    } else {
                        continue 'next_case;
                    }
                }
            }
            break;
        }
        *cpp = ptr::null_mut();
        goto_redir = true;
    } else if tok == TLP {
        n1 = stalloc(mem::size_of::<nredir>()) as *mut node;
        (*n1).r#type = NSUBSHELL;
        (*n1).nredir.linno = savelinno;
        (*n1).nredir.n = list(0);
        (*n1).nredir.redirect = ptr::null_mut();
        t = TRP;
    } else if tok == TBEGIN {
        n1 = list(0);
        t = TEND;
    } else if tok == TWORD || tok == TREDIR {
        tokpushback += 1;
        return simplecmd();
    } else {
        synexpect(-1);
        /* NOTREACHED */
    }

    if !goto_redir {
        if readtoken() != t {
            synexpect(t);
        }
    }

    /* redir: */
    /* Now check for redirection which may follow command */
    checkkwd = CHKKWD | CHKALIAS;
    rpp = rpp2;
    while readtoken() == TREDIR {
        n2 = redirnode;
        *rpp = n2;
        rpp = addr_of_mut!((*n2).nfile.next);
        parsefname();
    }
    tokpushback += 1;
    *rpp = ptr::null_mut();
    if !redir.is_null() {
        if (*n1).r#type != NSUBSHELL {
            n2 = stalloc(mem::size_of::<nredir>()) as *mut node;
            (*n2).r#type = NREDIR;
            (*n2).nredir.linno = savelinno;
            (*n2).nredir.n = n1;
            n1 = n2;
        }
        (*n1).nredir.redirect = redir;
    }

    n1
}

// [spec:dash:def:parser.simplecmd-fn]
// [spec:dash:sem:parser.simplecmd-fn]
unsafe fn simplecmd() -> *mut node {
    let mut args: *mut node;
    let mut app: *mut *mut node;
    let mut n: *mut node = ptr::null_mut();
    let mut vars: *mut node;
    let mut vpp: *mut *mut node;
    let mut rpp: *mut *mut node;
    let mut redir: *mut node;
    let mut savecheckkwd: c_int;
    let savelinno: c_int;

    args = ptr::null_mut();
    app = &mut args as *mut *mut node;
    vars = ptr::null_mut();
    vpp = &mut vars as *mut *mut node;
    redir = ptr::null_mut();
    rpp = &mut redir as *mut *mut node;

    savecheckkwd = CHKALIAS;
    savelinno = crate::plinno!();
    loop {
        checkkwd = savecheckkwd;
        let tok = readtoken();
        if tok == TWORD {
            n = stalloc(mem::size_of::<narg>()) as *mut node;
            (*n).r#type = NARG;
            (*n).narg.text = wordtext;
            (*n).narg.backquote = backquotelist;
            if savecheckkwd != 0 && isassignment(wordtext) != 0 {
                *vpp = n;
                vpp = addr_of_mut!((*n).narg.next);
            } else {
                *app = n;
                app = addr_of_mut!((*n).narg.next);
                savecheckkwd = 0;
            }
        } else if tok == TREDIR {
            n = redirnode;
            *rpp = n;
            rpp = addr_of_mut!((*n).nfile.next);
            parsefname(); /* read name of redirection file */
        } else {
            if tok == TLP
                && !args.is_null()
                && app == addr_of_mut!((*args).narg.next)
                && vars.is_null()
                && redir.is_null()
            {
                let bcmd: *const crate::builtins::builtincmd;
                let name: *const c_char;

                /* We have a function */
                if readtoken() != TRP {
                    synexpect(TRP);
                }
                name = (*n).narg.text;
                bcmd = crate::exec::find_builtin(name);
                if goodname(name) == 0
                    || (!bcmd.is_null()
                        && ((*bcmd).flags & crate::builtins::BUILTIN_SPECIAL) != 0)
                {
                    synerror(c"Bad function name".as_ptr());
                }
                (*n).r#type = NDEFUN;
                checkkwd = CHKNL | CHKKWD | CHKALIAS;
                (*n).ndefun.text = (*n).narg.text;
                (*n).ndefun.linno = crate::plinno!();
                (*n).ndefun.body = command();
                return n;
            }
            /* fall through */
            /* default: */
            tokpushback += 1;
            break;
        }
    }
    /* out: */
    *app = ptr::null_mut();
    *vpp = ptr::null_mut();
    *rpp = ptr::null_mut();
    n = stalloc(mem::size_of::<ncmd>()) as *mut node;
    (*n).r#type = NCMD;
    (*n).ncmd.linno = savelinno;
    (*n).ncmd.args = args;
    (*n).ncmd.assign = vars;
    (*n).ncmd.redirect = redir;
    n
}

// [spec:dash:def:parser.makename-fn]
// [spec:dash:sem:parser.makename-fn]
unsafe fn makename() -> *mut node {
    let n: *mut node;

    n = stalloc(mem::size_of::<narg>()) as *mut node;
    (*n).r#type = NARG;
    (*n).narg.next = ptr::null_mut();
    (*n).narg.text = wordtext;
    (*n).narg.backquote = backquotelist;
    n
}

// [spec:dash:def:parser.fixredir-fn]
// [spec:dash:sem:parser.fixredir-fn]
pub unsafe fn fixredir(n: *mut node, text: *const c_char, err: c_int) {
    /* TRACE(("Fix redir %s %d\n", text, err)); */
    if err == 0 {
        (*n).ndup.vname = ptr::null_mut();
    }

    if is_digit(*text.offset(0) as c_int) && *text.offset(1) == 0 {
        (*n).ndup.dupfd = digit_val(*text.offset(0) as c_int);
    } else if *text.offset(0) == '-' as c_char && *text.offset(1) == 0 {
        (*n).ndup.dupfd = -1;
    } else {
        if err != 0 {
            crate::error::sh_error(c"Bad fd number: %s".as_ptr(), &[VaArg::Str(text)]);
        } else {
            (*n).ndup.vname = makename();
        }
    }
}

// [spec:dash:def:parser.parsefname-fn]
// [spec:dash:sem:parser.parsefname-fn]
unsafe fn parsefname() {
    let n: *mut node = redirnode;

    if (*n).r#type == NHERE {
        checkkwd |= CHKEOFMARK;
    }
    if readtoken() != TWORD {
        synexpect(-1);
    }
    checkkwd &= !CHKEOFMARK;
    if (*n).r#type == NHERE {
        let here: *mut heredoc = heredoc;
        let mut p: *mut heredoc;

        if quoteflag == 0 {
            (*n).r#type = NXHERE;
        }
        /* TRACE(("Here document %d\n", n->type)); */
        rmescapes(wordtext);
        (*here).eofmark = wordtext;
        (*here).next = ptr::null_mut();
        if heredoclist.is_null() {
            heredoclist = here;
        } else {
            p = heredoclist;
            while !(*p).next.is_null() {
                p = (*p).next;
            }
            (*p).next = here;
        }
    } else if (*n).r#type == NTOFD || (*n).r#type == NFROMFD {
        fixredir(n, wordtext, 0);
    } else {
        (*n).nfile.fname = makename();
    }
}

/*
 * Input any here documents.
 */

// [spec:dash:def:parser.parseheredoc-fn]
// [spec:dash:sem:parser.parseheredoc-fn]
unsafe fn parseheredoc() {
    let mut here: *mut heredoc;

    here = heredoclist;
    heredoclist = ptr::null_mut();

    while !here.is_null() {
        if needprompt != 0 {
            setprompt(2);
        }
        if (*(*here).here).r#type == NHERE {
            readtoken1(pgetc(), SQSYNTAX(), (*here).eofmark, (*here).striptabs);
        } else {
            readtoken1(
                pgetc_eatbnl(),
                DQSYNTAX(),
                (*here).eofmark,
                (*here).striptabs,
            );
        }
        let n = stalloc(mem::size_of::<narg>()) as *mut node;
        (*n).narg.r#type = NARG;
        (*n).narg.next = ptr::null_mut();
        (*n).narg.text = wordtext;
        (*n).narg.backquote = backquotelist;
        (*(*here).here).nhere.doc = n;
        here = (*here).next;
    }
}

// [spec:dash:def:parser.readtoken-fn]
// [spec:dash:sem:parser.readtoken-fn]
unsafe fn readtoken() -> c_int {
    let mut t: c_int;
    let mut kwd: c_int = checkkwd;

    'top: loop {
        t = xxreadtoken();

        /*
         * eat newlines
         */
        if kwd & CHKNL != 0 {
            while t == TNL {
                parseheredoc();
                checkkwd = 0;
                t = xxreadtoken();
            }
        }

        kwd |= checkkwd;
        checkkwd = 0;

        if t != TWORD || quoteflag != 0 {
            break 'top;
        }

        /*
         * check for keywords
         */
        if kwd & CHKKWD != 0 {
            let pp: *const *const c_char = findkwd(wordtext);

            if !pp.is_null() {
                t = pp.offset_from(parsekwd.0.as_ptr()) as c_int + KWDOFFSET;
                lasttoken = t;
                break 'top;
            }
        }

        if kwd & CHKALIAS != 0 {
            let ap = crate::alias::lookupalias(wordtext, 1);
            if !ap.is_null() {
                if *(*ap).val != 0 {
                    pushstring((*ap).val, ap as *mut c_void);
                }
                continue 'top;
            }
        }
        break 'top;
    }
    /* out: */
    t
}

// [spec:dash:def:parser.nlprompt-fn]
// [spec:dash:sem:parser.nlprompt-fn]
unsafe fn nlprompt() {
    crate::plinno!() += 1;
    if doprompt != 0 {
        setprompt(2);
    }
}

// [spec:dash:def:parser.nlnoprompt-fn]
// [spec:dash:sem:parser.nlnoprompt-fn]
unsafe fn nlnoprompt() {
    crate::plinno!() += 1;
    needprompt = doprompt;
}

/*
 * Read the next input token.
 * If the token is a word, we set backquotelist to the list of cmds in
 *	backquotes.  We set quoteflag to true if any part of the word was
 *	quoted.
 * If the token is TREDIR, then we set redirnode to a structure containing
 *	the redirection.
 */

// [spec:dash:def:parser.xxreadtoken-fn]
// [spec:dash:sem:parser.xxreadtoken-fn]
unsafe fn xxreadtoken() -> c_int {
    let mut c: c_int;

    if tokpushback != 0 {
        tokpushback = 0;
        return lasttoken;
    }
    if needprompt != 0 {
        setprompt(2);
    }
    loop {
        /* until token or start of word found */
        let tok: c_int;

        c = pgetc_eatbnl();
        if c == ' ' as c_int || c == '\t' as c_int {
            continue;
        } else if c == '#' as c_int {
            loop {
                c = pgetc();
                if c == '\n' as c_int || c == PEOF {
                    break;
                }
            }
            pungetc();
            continue;
        } else if c == '\n' as c_int {
            nlnoprompt();
            lasttoken = TNL;
            return TNL;
        } else if c == PEOF {
            lasttoken = TEOF;
            return TEOF;
        } else if c == '&' as c_int {
            if pgetc_eatbnl() == '&' as c_int {
                lasttoken = TAND;
                return TAND;
            }
            pungetc();
            lasttoken = TBACKGND;
            return TBACKGND;
        } else if c == '|' as c_int {
            if pgetc_eatbnl() == '|' as c_int {
                lasttoken = TOR;
                return TOR;
            }
            pungetc();
            lasttoken = TPIPE;
            return TPIPE;
        } else if c == ';' as c_int {
            if pgetc_eatbnl() == ';' as c_int {
                lasttoken = TENDCASE;
                return TENDCASE;
            }
            pungetc();
            lasttoken = TSEMI;
            return TSEMI;
        } else if c == '(' as c_int {
            lasttoken = TLP;
            return TLP;
        } else if c == ')' as c_int {
            lasttoken = TRP;
            return TRP;
        }
        tok = readtoken1(c, BASESYNTAX(), ptr::null_mut(), 0);
        if tok != TBLANK {
            return tok;
        }
    }
}

// [spec:dash:def:parser.pgetc-eatbnl-fn]
// [spec:dash:sem:parser.pgetc-eatbnl-fn]
unsafe fn pgetc_eatbnl() -> c_int {
    let mut c: c_int;

    loop {
        c = pgetc();
        if c != '\\' as c_int {
            break;
        }
        if pgetc() != '\n' as c_int {
            pungetc();
            break;
        }

        nlprompt();
    }

    c
}

// [spec:dash:def:parser.pgetc-top-fn]
// [spec:dash:sem:parser.pgetc-top-fn]
unsafe fn pgetc_top(stack: *mut synstack) -> c_int {
    if (*stack).syntax == SQSYNTAX() {
        pgetc()
    } else {
        pgetc_eatbnl()
    }
}

// [spec:dash:def:parser.synstack-push-fn]
// [spec:dash:sem:parser.synstack-push-fn]
unsafe fn synstack_push(stack: *mut *mut synstack, next: *mut synstack, syntax: *const Syntax) {
    ptr::write_bytes(next as *mut u8, 0, mem::size_of::<synstack>());
    (*next).syntax = syntax;
    (*next).next = *stack;
    (**stack).prev = next;
    *stack = next;
}

// [spec:dash:def:parser.synstack-pop-fn]
// [spec:dash:sem:parser.synstack-pop-fn]
unsafe fn synstack_pop(stack: *mut *mut synstack) {
    *stack = (**stack).next;
}

// [spec:dash:def:parser.getmbc-fn]
// [spec:dash:sem:parser.getmbc-fn]
pub unsafe fn getmbc(c: c_int, out: *mut c_char, mode: c_int) -> c_uint {
    let mut c = c;
    let mut out = out;
    let start: *mut c_char = out;
    let mut mbst: libc::mbstate_t = mem::zeroed();
    let mut ml: c_uint = 0;
    let mut ml2: usize;
    let mut wc: libc::wchar_t = 0;
    let mbc: *mut c_char;

    if c >= 0 || c <= PEOF {
        return 0;
    }

    mbc = if (mode & 3) < 2 {
        out.offset(2 + (mode == 1) as isize)
    } else {
        out
    };
    *mbc.offset(ml as isize) = c as c_char;
    loop {
        ml2 = mbrtowc(&mut wc, mbc.offset(ml as isize), 1, &mut mbst);
        ml += 1;
        if ml2 != (-2isize) as usize {
            break;
        }
        if ml as usize >= MB_LEN_MAX {
            break;
        }
        c = pgetc_eoa();
        if c == PEOA || c == PEOF {
            break;
        }
        *mbc.offset(ml as isize) = c as c_char;
    }

    if ml2 == 1 && ml > 1 {
        if mode == 4 && iswblank(wc as u32) != 0 {
            return 1;
        }

        if (mode & 3) < 2 {
            crate::USTPUTC!(CTLMBCHAR, out);
            if mode == 1 {
                crate::USTPUTC!(CTLESC, out);
            }
            crate::USTPUTC!(ml, out);
        }
        crate::STADJUST!(ml, out);
        if (mode & 3) < 2 {
            crate::USTPUTC!(ml, out);
            crate::USTPUTC!(CTLMBCHAR, out);
        }

        return (out as usize - start as usize) as c_uint;
    }

    if ml > 1 {
        pungetn(ml as c_int - 1);
    }

    0
}

// [spec:dash:def:parser.dollarsq-escape-fn]
// [spec:dash:sem:parser.dollarsq-escape-fn]
unsafe fn dollarsq_escape(out: *mut c_char) -> *mut c_char {
    let mut out = out;
    /* 10 = length of UXXXXXXXX + NUL */
    let mut str: [c_char; 10] = [0; 10];
    let mut len: c_uint;
    let mut p: *mut c_char;

    len = 0;
    while (len as usize) < mem::size_of_val(&str) - 1 {
        let c = pgetc();

        if c <= PEOF {
            break;
        }

        str[len as usize] = c as c_char;
        len += 1;

        if c == '\'' as c_int {
            break;
        }
    }
    str[len as usize] = 0;

    p = str.as_mut_ptr();
    if *p != 'c' as c_char {
        let ret: c_uint;

        ret = crate::bltin::printf::conv_escape(p, out, true);
        p = p.offset((ret >> 4) as isize);
        out = out.offset((ret & 15) as isize);
    } else {
        p = p.offset(1);
        if *p != 0 {
            let conv_ch: c_int;
            let c: c_int;

            c = *p as u8 as c_int;
            p = p.offset(1);

            p = p.offset((((c ^ *p as c_int) | (c ^ '\\' as c_int)) == 0) as isize);

            conv_ch = (c & !((c & 0x40) >> 1) & 0x7f) ^ 0x40;
            crate::USTPUTC!(conv_ch, out);
        }
    }

    pungetn((len as isize - (p as isize - str.as_ptr() as isize)) as c_int);
    out
}

/*
 * If eofmark is NULL, read a word or a redirection symbol.  If eofmark
 * is not NULL, read a here document.  In the latter case, eofmark is the
 * word which marks the end of the document and striptabs is true if
 * leading tabs should be stripped from the document.  The argument firstc
 * is the first character of the input token or document.
 *
 * Because C does not have internal subroutines, the original simulates
 * them with goto's: CHECKEND, PARSEREDIR, PARSESUB, PARSEBACKQOLD,
 * PARSEBACKQNEW and PARSEARITH run code that appears at the end of
 * readtoken1.  Here they are plain functions taking the shared C locals
 * (`Rt1`) by `&mut`; they are called from exactly the same places and
 * mutate the state in exactly the same order.
 */

/// The locals of `readtoken1` that its internal subroutines share.
struct Rt1 {
    synstack: *mut synstack,
    chkeofmark: c_int,
    printesc: bool,
    bqlist: *mut nodelist,
    dollarsq: c_int,
    c: c_int,
    quotef: c_int,
    out: *mut c_char,
    eofmark: *mut c_char,
    striptabs: c_int,
    /// Backing store for the `alloca`'d `struct synstack` levels.  The C
    /// cannot free them (alloca inside a loop), so it reuses them through
    /// the `prev` link and only calls `alloca` when `prev` is NULL; this
    /// pool therefore only grows at exactly those points.  Boxes give the
    /// stable addresses the `prev`/`next` links require, and the whole
    /// pool is released when readtoken1 returns, like the alloca frame.
    pool: Vec<Box<synstack>>,
    /// Backing store for the `alloca`'d pushback strings in `checkend`,
    /// which likewise accumulate for the life of the call.
    strpool: Vec<Vec<u8>>,
}

/// `alloca(sizeof(*synstack))`
unsafe fn alloca_synstack(st: &mut Rt1) -> *mut synstack {
    st.pool.push(Box::new(mem::zeroed()));
    let last = st.pool.len() - 1;
    (&mut *st.pool[last]) as *mut synstack
}

/// The label targets inside readtoken1's character switch that are
/// reached by `goto` from more than one case.
enum Lbl {
    None,
    Csquote,
    Quotemark,
    Toggledq,
    EndBackq,
}

// [spec:dash:def:parser.readtoken1-fn]
// [spec:dash:sem:parser.readtoken1-fn]
unsafe fn readtoken1(
    firstc: c_int,
    syntax: *const Syntax,
    eofmark: *mut c_char,
    striptabs: c_int,
) -> c_int {
    let mut synbase = synstack {
        syntax,
        prev: ptr::null_mut(),
        next: ptr::null_mut(),
        innerdq: 0,
        varpushed: 0,
        dblquote: (syntax == DQSYNTAX()) as c_int,
        backq: 0,
        varnest: 0,
        parenlevel: 0,
        dqvarnest: 0,
    };
    let mut st = Rt1 {
        synstack: &mut synbase as *mut synstack,
        chkeofmark: checkkwd & CHKEOFMARK,
        printesc: syntax == SQSYNTAX(),
        bqlist: ptr::null_mut(),
        dollarsq: 0,
        c: firstc,
        quotef: 0,
        out: ptr::null_mut(),
        eofmark,
        striptabs,
        pool: Vec::new(),
        strpool: Vec::new(),
    };
    let len: usize;

    crate::STARTSTACKSTR!(st.out);
    'loop_: loop {
        /* for each line, until end of word */
        checkend(&mut st); /* set c to PEOF if at end of here document */
        /* Until end of line or end of word */
        loop {
            'body: {
                let fieldsplitting: c_int;
                let mut ml: c_uint;

                /* Permit max(MB_LEN_MAX, 23) calls to USTPUTC. */
                crate::CHECKSTRSPACE!(
                    (if MB_LEN_MAX > 16 { MB_LEN_MAX } else { 16 }) + 7,
                    st.out
                );
                fieldsplitting = if (*st.synstack).syntax == BASESYNTAX()
                    && ((*st.synstack).varnest | (*st.synstack).backq) == 0
                {
                    4
                } else {
                    0
                };
                ml = getmbc(
                    st.c,
                    st.out,
                    fieldsplitting | (if st.printesc { 2 } else { 0 }),
                );
                if ml == 1 {
                    if st.out == stackblock() {
                        return TBLANK;
                    }
                    st.c = pgetc();
                    break 'loop_;
                }
                st.out = st.out.offset(ml as isize);
                if ml != 0 {
                    break 'body; /* continue */
                }

                let cls = syn_at((*st.synstack).syntax, st.c);
                let mut lbl = Lbl::None;

                if cls == CNL as c_int {
                    /* '\n' */
                    if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    }
                    crate::USTPUTC!(st.c, st.out);
                    nlprompt();
                    st.c = pgetc_top(st.synstack);
                    continue 'loop_; /* continue outer loop */
                } else if cls == CWORD as c_int {
                    crate::USTPUTC!(st.c, st.out);
                } else if cls == CCTL as c_int {
                    if st.c == st.dollarsq {
                        st.out = dollarsq_escape(st.out);
                    } else {
                        if (st.eofmark.is_null() as c_int
                            | (*st.synstack).dblquote
                            | (*st.synstack).varnest)
                            != 0
                        {
                            crate::USTPUTC!(CTLESC, st.out);
                        }
                        crate::USTPUTC!(st.c, st.out);
                    }
                } else if cls == CBACK as c_int {
                    /* backslash */
                    st.c = pgetc();
                    if st.c == PEOF {
                        crate::USTPUTC!(CTLESC, st.out);
                        crate::USTPUTC!('\\', st.out);
                        pungetc();
                    } else {
                        if ((*st.synstack).dblquote | (*st.synstack).backq) != 0
                            && st.c != '\\' as c_int
                            && st.c != '`' as c_int
                            && st.c != '$' as c_int
                            && (st.c != '"' as c_int
                                || (!st.eofmark.is_null() && (*st.synstack).varnest == 0))
                            && (st.c != '}' as c_int || (*st.synstack).varnest == 0)
                        {
                            crate::USTPUTC!(CTLESC, st.out);
                            crate::USTPUTC!('\\', st.out);
                        }
                        st.quotef += 1;

                        ml = getmbc(st.c, st.out, 1);
                        st.out = st.out.offset(ml as isize);
                        if ml == 0 {
                            crate::USTPUTC!(CTLESC, st.out);
                            crate::USTPUTC!(st.c, st.out);
                        }
                    }
                } else if cls == CSQUOTE as c_int {
                    lbl = Lbl::Csquote;
                } else if cls == CDQUOTE as c_int {
                    (*st.synstack).syntax = DQSYNTAX();
                    (*st.synstack).dblquote = 1;
                    lbl = Lbl::Toggledq;
                } else if cls == CENDQUOTE as c_int {
                    if !st.eofmark.is_null() && (*st.synstack).varnest == 0 {
                        crate::USTPUTC!(st.c, st.out);
                    } else {
                        if (*st.synstack).dqvarnest == 0 {
                            if st.dollarsq != 0 {
                                let p = stackblock();

                                *st.out = 0;
                                st.out = p.offset(libc::strlen(p) as isize);
                                st.dollarsq = 0;
                            }

                            (*st.synstack).syntax = BASESYNTAX();
                            (*st.synstack).dblquote = 0;
                        }

                        st.quotef += 1;

                        if st.c == '"' as c_int {
                            lbl = Lbl::Toggledq;
                        } else {
                            lbl = Lbl::Quotemark;
                        }
                    }
                } else if cls == CVAR as c_int {
                    /* '$' */
                    if parsesub(&mut st) {
                        /* parse substitution */
                        lbl = Lbl::Csquote;
                    }
                } else if cls == CENDVAR as c_int {
                    /* '}' */
                    if (*st.synstack).innerdq == 0 && (*st.synstack).varnest > 0 {
                        (*st.synstack).varnest -= 1;
                        if (*st.synstack).varnest == 0 && (*st.synstack).varpushed != 0 {
                            synstack_pop(&mut st.synstack);
                        } else if (*st.synstack).dqvarnest > 0 {
                            (*st.synstack).dqvarnest -= 1;
                        }
                        if st.chkeofmark == 0 {
                            st.c = CTLENDVAR;
                        }
                    }
                    crate::USTPUTC!(st.c, st.out);
                } else if cls == CLP as c_int {
                    /* '(' in arithmetic */
                    (*st.synstack).parenlevel += 1;
                    crate::USTPUTC!(st.c, st.out);
                } else if cls == CRP as c_int {
                    /* ')' in arithmetic */
                    if (*st.synstack).parenlevel > 0 {
                        (*st.synstack).parenlevel -= 1;
                    } else if pgetc_eatbnl() == ')' as c_int {
                        synstack_pop(&mut st.synstack);
                        if st.chkeofmark != 0 {
                            crate::USTPUTC!(st.c, st.out);
                        } else {
                            st.c = CTLENDARI;
                        }
                    } else {
                        /*
                         * unbalanced parens
                         *  (don't 2nd guess - no error)
                         */
                        pungetc();
                    }
                    crate::USTPUTC!(st.c, st.out);
                } else if cls == CBQUOTE as c_int {
                    /* '`' */
                    if (*st.synstack).backq == 2 {
                        lbl = Lbl::EndBackq;
                    } else {
                        crate::USTPUTC!('`', st.out);
                        parsebackq(&mut st, 1);
                    }
                } else if cls == CEOF as c_int {
                    break 'loop_; /* exit outer loop */
                } else {
                    /* default: */
                    if st.c == ')' as c_int && (*st.synstack).backq == 1 {
                        lbl = Lbl::EndBackq;
                    } else if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    } else {
                        crate::USTPUTC!(st.c, st.out);
                    }
                }

                /* the goto-linked tails of the switch above */
                loop {
                    match lbl {
                        Lbl::None => break,
                        Lbl::Csquote => {
                            /* csquote: */
                            (*st.synstack).syntax = SQSYNTAX();
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::Quotemark => {
                            /* quotemark: */
                            if st.eofmark.is_null() {
                                crate::USTPUTC!(CTLQUOTEMARK, st.out);
                            }
                            lbl = Lbl::None;
                        }
                        Lbl::Toggledq => {
                            /* toggledq: */
                            if (*st.synstack).varnest != 0 {
                                (*st.synstack).innerdq ^= 1;
                            }
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::EndBackq => {
                            /* end_backq: */
                            synstack_pop(&mut st.synstack);
                            st.printesc = false;
                            crate::USTPUTC!(st.c, st.out);
                            lbl = Lbl::None;
                        }
                    }
                }
            }
            st.c = pgetc_top(st.synstack);
        }
    }
    /* endword: */
    if (*st.synstack).syntax == ARISYNTAX() {
        synerror(c"Missing '))'".as_ptr());
    }
    if ((*st.synstack).syntax != BASESYNTAX() && st.eofmark.is_null()) || (*st.synstack).backq != 0
    {
        synerror(c"Unterminated quoted string".as_ptr());
    }
    if (*st.synstack).varnest != 0 {
        /* { */
        synerror(c"Missing '}'".as_ptr());
    }
    crate::USTPUTC!('\0', st.out);
    len = st.out as usize - stackblock() as usize;
    st.out = stackblock();
    if st.eofmark.is_null() {
        if (st.c == '>' as c_int || st.c == '<' as c_int)
            && st.quotef == 0
            && len <= 2
            && (*st.out == 0 || is_digit(*st.out as c_int))
        {
            parseredir(&mut st);
            lasttoken = TREDIR;
            return TREDIR;
        } else {
            pungetc();
        }
    }
    quoteflag = st.quotef;
    backquotelist = st.bqlist;
    grabstackblock(len);
    wordtext = st.out;
    lasttoken = TWORD;
    TWORD
}
/* end of readtoken routine */

/*
 * Check to see whether we are at the end of the here document.  When this
 * is called, c is set to the first character of the next input line.  If
 * we are at the end of the here document, this routine sets the c to PEOF.
 */

/* checkend: */
unsafe fn checkend(st: &mut Rt1) {
    if realeofmark(st.eofmark) != 0 {
        let markloc: isize;
        let mut p: *mut c_char;
        let mut more_heredoc = false;

        if st.striptabs != 0 {
            while st.c == '\t' as c_int {
                st.c = pgetc();
            }
        }

        markloc = st.out as isize - stackblock() as isize;
        p = st.eofmark;
        loop {
            crate::STPUTC!(st.c, st.out);
            if *p == 0 {
                break;
            }
            if st.c != *p as i8 as c_int {
                more_heredoc = true; /* goto more_heredoc */
                break;
            }

            st.c = pgetc();
            p = p.offset(1);
        }

        if !more_heredoc {
            if st.c == '\n' as c_int || st.c == PEOF {
                st.c = PEOF;
                nlnoprompt();
            } else {
                more_heredoc = true;
            }
        }

        if more_heredoc {
            let mut len: isize;

            /* more_heredoc: */
            p = stackblock().offset(markloc + 1);
            len = st.out as isize - p as isize;

            if len != 0 {
                len -= (st.c <= PEOF) as isize;
                st.c = *p.offset(-1) as c_int;

                if len != 0 {
                    let str: *mut c_char;

                    /* str = alloca(len + 1) */
                    st.strpool.push(vec![0u8; len as usize + 1]);
                    let last = st.strpool.len() - 1;
                    str = st.strpool[last].as_mut_ptr() as *mut c_char;
                    *(libc::mempcpy(str as *mut c_void, p as *const c_void, len as usize)
                        as *mut c_char) = 0;

                    pushstring(str, ptr::null_mut());
                }
            }
        }

        crate::STADJUST!(stackblock() as isize + markloc - st.out as isize, st.out);
    }
    /* goto checkend_return; */
}

/*
 * Parse a redirection operator.  The variable "out" points to a string
 * specifying the fd to be redirected.  The variable "c" contains the
 * first character of the redirection operator.
 */

/* parseredir: */
unsafe fn parseredir(st: &mut Rt1) {
    let fd: c_char = *st.out;
    let mut np: *mut node;

    np = stalloc(mem::size_of::<nfile>()) as *mut node;
    if st.c == '>' as c_int {
        (*np).nfile.fd = 1;
        st.c = pgetc_eatbnl();
        if st.c == '>' as c_int {
            (*np).r#type = NAPPEND;
        } else if st.c == '|' as c_int {
            (*np).r#type = NCLOBBER;
        } else if st.c == '&' as c_int {
            (*np).r#type = NTOFD;
        } else {
            (*np).r#type = NTO;
            pungetc();
        }
    } else {
        /* c == '<' */
        (*np).nfile.fd = 0;
        st.c = pgetc_eatbnl();
        if st.c == '<' as c_int {
            if mem::size_of::<nfile>() != mem::size_of::<nhere>() {
                np = stalloc(mem::size_of::<nhere>()) as *mut node;
                (*np).nfile.fd = 0;
            }
            (*np).r#type = NHERE;
            heredoc = stalloc(mem::size_of::<heredoc>()) as *mut heredoc;
            (*heredoc).here = np;
            st.c = pgetc_eatbnl();
            if st.c == '-' as c_int {
                (*heredoc).striptabs = 1;
            } else {
                (*heredoc).striptabs = 0;
                pungetc();
            }
        } else if st.c == '&' as c_int {
            (*np).r#type = NFROMFD;
        } else if st.c == '>' as c_int {
            (*np).r#type = NFROMTO;
        } else {
            (*np).r#type = NFROM;
            pungetc();
        }
    }
    if fd != '\0' as c_char {
        (*np).nfile.fd = digit_val(fd as c_int);
    }
    redirnode = np;
    /* goto parseredir_return; */
}

/*
 * Parse a substitution.  At this point, we have read the dollar sign
 * and nothing else.
 *
 * Returns true where the C does `goto csquote`, i.e. jumps back into the
 * CSQUOTE arm of readtoken1's switch instead of returning normally.
 */

/* parsesub: */
unsafe fn parsesub(st: &mut Rt1) -> bool {
    let mut newsyn: *const Syntax = (*st.synstack).syntax;
    static types: [u8; 6] = *b"}-+?=\0";
    let mut subtype: c_int;

    crate::USTPUTC!('$', st.out);

    st.c = pgetc_eatbnl();
    if st.c == '(' as c_int {
        /* $(command) or $((arith)) */
        crate::USTPUTC!(st.c, st.out);
        if pgetc_eatbnl() == '(' as c_int {
            parsearith(st);
        } else {
            pungetc();
            parsebackq(st, 0);
        }
    } else if st.c == '\'' as c_int && syn_at(newsyn, '&' as c_int) != 0 {
        crate::STADJUST!(-1, st.out);
        st.dollarsq = '\\' as c_int;
        return true; /* goto csquote */
    } else if st.c == '{' as c_int || is_name(st.c) || is_special(st.c) != 0 {
        let typeloc: isize = st.out as isize - stackblock() as isize;
        let mut badsub = false;

        crate::STADJUST!((st.chkeofmark == 0) as c_int, st.out);
        subtype = VSNORMAL;
        if st.c == '{' as c_int {
            if st.chkeofmark != 0 {
                crate::USTPUTC!('{', st.out);
            }
            st.c = pgetc_eatbnl();
            subtype = 0;
        }
        'varname: loop {
            if is_name(st.c) {
                loop {
                    crate::STPUTC!(st.c, st.out);
                    st.c = pgetc_eatbnl();
                    if !is_in_name(st.c) {
                        break;
                    }
                }
            } else if is_digit(st.c) {
                loop {
                    crate::STPUTC!(st.c, st.out);
                    st.c = pgetc_eatbnl();
                    if !((subtype <= 0 || subtype >= VSLENGTH) && is_digit(st.c)) {
                        break;
                    }
                }
            } else if st.c != '}' as c_int {
                let mut cc = st.c;

                st.c = pgetc_eatbnl();

                if subtype == 0 && cc == '#' as c_int {
                    subtype = VSLENGTH;

                    if st.c == '_' as c_int || libc::isalnum(st.c) != 0 {
                        if st.chkeofmark != 0 {
                            crate::USTPUTC!('#', st.out);
                        }
                        continue 'varname; /* goto varname */
                    }

                    cc = st.c;
                    st.c = pgetc_eatbnl();
                    if cc == '}' as c_int || st.c != '}' as c_int {
                        pungetc();
                        subtype = 0;
                        st.c = cc;
                        cc = '#' as c_int;
                    } else if st.chkeofmark != 0 {
                        crate::USTPUTC!('#', st.out);
                    }
                }

                if is_special(cc) == 0 {
                    if subtype == VSLENGTH {
                        subtype = 0;
                    }
                    badsub = true; /* goto badsub */
                    break 'varname;
                }

                crate::USTPUTC!(cc, st.out);
            } else {
                badsub = true; /* goto badsub */
                break 'varname;
            }
            break 'varname;
        }

        if badsub {
            /* badsub: */
            pungetc();
        } else if subtype == 0 {
            let cc = st.c;

            if st.chkeofmark != 0 {
                crate::STPUTC!(st.c, st.out);
            }

            if st.c == '%' as c_int || st.c == '#' as c_int {
                subtype = if st.c == '#' as c_int {
                    VSTRIMLEFT
                } else {
                    VSTRIMRIGHT
                };
                st.c = pgetc_eatbnl();
                if st.c == cc {
                    if st.chkeofmark != 0 {
                        crate::STPUTC!(st.c, st.out);
                    }
                    subtype += 1;
                } else {
                    pungetc();
                }

                newsyn = BASESYNTAX();
            } else {
                if st.c == ':' as c_int {
                    subtype = VSNUL;
                    st.c = pgetc_eatbnl();
                    if st.chkeofmark != 0 {
                        crate::STPUTC!(st.c, st.out);
                    }
                    /*FALLTHROUGH*/
                }
                /* default: */
                let p = libc::strchr(types.as_ptr() as *const c_char, st.c);
                if !p.is_null() {
                    subtype |= (p as isize - types.as_ptr() as isize) as c_int + VSNORMAL;
                }
            }
        } else {
            if subtype == VSLENGTH && st.c != '}' as c_int {
                subtype = 0;
            }
            /* badsub: */
            pungetc();
        }

        if newsyn == ARISYNTAX() {
            newsyn = DQSYNTAX();
        }

        if (newsyn != (*st.synstack).syntax || (*st.synstack).innerdq != 0) && subtype != VSNORMAL
        {
            let next = if !(*st.synstack).prev.is_null() {
                (*st.synstack).prev
            } else {
                alloca_synstack(st)
            };
            synstack_push(&mut st.synstack, next, newsyn);

            (*st.synstack).varpushed += 1;
            (*st.synstack).dblquote = (newsyn != BASESYNTAX()) as c_int;
        }

        if subtype != VSNORMAL {
            (*st.synstack).varnest += 1;
            if (*st.synstack).dblquote != 0 {
                (*st.synstack).dqvarnest += 1;
            }
        }
        if st.chkeofmark == 0 {
            let p = stackblock();

            *p.offset(typeloc - 1) = CTLVAR as c_char;
            *p.offset(typeloc) = (subtype | VSBIT) as c_char;
            crate::STPUTC!('=', st.out);
        }
    } else {
        pungetc();
    }

    /* goto parsesub_return; */
    false
}

/*
 * Called to parse command substitutions.  oldstyle is set if the command
 * is enclosed inside `...` rather than $(...).
 */

/* parsebackq: */
unsafe fn parsebackq(st: &mut Rt1, oldstyle: c_int) {
    let mut saveprompt: c_int = 0;
    let saveheredoclist: *mut heredoc;
    let mut nlpp: *mut *mut nodelist;
    let savelen: usize;
    let n: *mut node;
    let mut ml: c_uint;
    let pstr: *mut c_char;
    let str: *mut c_char;

    if st.chkeofmark != 0 {
        let next = if !(*st.synstack).prev.is_null() {
            (*st.synstack).prev
        } else {
            alloca_synstack(st)
        };
        synstack_push(&mut st.synstack, next, BASESYNTAX());
        (*st.synstack).backq = oldstyle + 1;
        st.printesc = true;
        /* goto parsebackq_out; */
        if oldstyle != 0 {
            tokpushback = 0;
        }
        return;
    }
    crate::STADJUST!(oldstyle - 1, st.out);
    *st.out.offset(-1) = CTLBACKQ as c_char;
    str = stackblock();
    savelen = st.out as usize - stackblock() as usize;
    grabstackblock(savelen);
    crate::STARTSTACKSTR!(st.out);
    if oldstyle != 0 {
        /* We must read until the closing backquote, giving special
        treatment to some slashes, and then push the string and
        reread it as input, interpreting it normally.  */
        let mut done = false;
        let mut pout: *mut c_char = st.out;
        let mut pc: c_int;

        while !done {
            'bqbody: {
                crate::CHECKSTRSPACE!(MB_LEN_MAX + 1, pout);
                if needprompt != 0 {
                    setprompt(2);
                }
                pc = pgetc_eatbnl();
                if pc == '`' as c_int {
                    done = true;
                } else if pc == '\\' as c_int {
                    pc = pgetc();
                    if pc != '\\' as c_int
                        && pc != '`' as c_int
                        && pc != '$' as c_int
                        && ((*st.synstack).dblquote == 0 || pc != '"' as c_int)
                    {
                        crate::USTPUTC!('\\', pout);
                    }
                    ml = getmbc(pc, pout, 2);
                    pout = pout.offset(ml as isize);
                    if ml != 0 {
                        break 'bqbody; /* continue */
                    }
                } else if pc == PEOF {
                    synerror(c"EOF in backquote substitution".as_ptr());
                } else if pc == '\n' as c_int {
                    nlnoprompt();
                }
                crate::USTPUTC!(pc, pout);
            }
        }
        *pout.offset(-1) = 0;
        pstr = grabstackstr(pout);
        setinputstring(pstr);
    }
    nlpp = &mut st.bqlist as *mut *mut nodelist;
    while !(*nlpp).is_null() {
        nlpp = addr_of_mut!((**nlpp).next);
    }
    *nlpp = stalloc(mem::size_of::<nodelist>()) as *mut nodelist;
    (**nlpp).next = ptr::null_mut();

    saveheredoclist = heredoclist;
    heredoclist = ptr::null_mut();

    if oldstyle != 0 {
        saveprompt = doprompt;
        doprompt = 0;
    }

    n = list(2);

    if oldstyle != 0 {
        doprompt = saveprompt;
    } else {
        if readtoken() != TRP {
            synexpect(TRP);
        }
        setinputstring(ptr::addr_of!(crate::mystring::nullstr) as *const c_char as *mut c_char);
    }

    parseheredoc();
    heredoclist = saveheredoclist;

    (**nlpp).n = n;
    /* Start reading from old file again. */
    popfile();

    st.out = stnputs(str, savelen, stackblock());

    /* parsebackq_out: */
    if oldstyle != 0 {
        /* Ignore any pushed back tokens left from the backquote
         * parsing.
         */
        tokpushback = 0;
    }
}

/*
 * Parse an arithmetic expansion (indicate start of one and set state)
 */
/* parsearith: */
unsafe fn parsearith(st: &mut Rt1) {
    let next = if !(*st.synstack).prev.is_null() {
        (*st.synstack).prev
    } else {
        alloca_synstack(st)
    };
    synstack_push(&mut st.synstack, next, ARISYNTAX());
    (*st.synstack).dblquote = 1;
    if st.chkeofmark != 0 {
        crate::USTPUTC!(st.c, st.out);
    } else {
        crate::STADJUST!(-1, st.out);
        *st.out.offset(-1) = CTLARI as c_char;
    }
    /* goto parsearith_return; */
}

/*
 * Return of a legal variable name (a letter or underscore followed by zero or
 * more letters, underscores, and digits).
 */

// [spec:dash:def:parser.endofname-fn]
// [spec:dash:sem:parser.endofname-fn]
pub unsafe fn endofname(name: *const c_char) -> *mut c_char {
    let mut p: *mut c_char;

    p = name as *mut c_char;
    if !is_name(*p as c_int) {
        return p;
    }
    loop {
        p = p.offset(1);
        if *p == 0 {
            break;
        }
        if !is_in_name(*p as c_int) {
            break;
        }
    }
    p
}

/*
 * Called when an unexpected token is read during the parse.  The argument
 * is the token that is expected, or -1 if more than one type of token can
 * occur at this point.
 */

// [spec:dash:def:parser.synexpect-fn]
// [spec:dash:sem:parser.synexpect-fn]
unsafe fn synexpect(token: c_int) -> ! {
    let mut msg: [c_char; 64] = [0; 64];

    if token >= 0 {
        fmtstr(
            msg.as_mut_ptr(),
            64,
            c"%s unexpected (expecting %s)".as_ptr(),
            &[
                VaArg::Str(tokname.0[lasttoken as usize]),
                VaArg::Str(tokname.0[token as usize]),
            ],
        );
    } else {
        fmtstr(
            msg.as_mut_ptr(),
            64,
            c"%s unexpected".as_ptr(),
            &[VaArg::Str(tokname.0[lasttoken as usize])],
        );
    }
    synerror(msg.as_ptr());
    /* NOTREACHED */
}

// [spec:dash:def:parser.synerror-fn]
// [spec:dash:sem:parser.synerror-fn]
#[allow(unreachable_code)]
unsafe fn synerror(msg: *const c_char) -> ! {
    errlinno = crate::plinno!();
    crate::error::sh_error(c"Syntax error: %s".as_ptr(), &[VaArg::Str(msg)]);
    /* NOTREACHED */
    unreachable!()
}

// [spec:dash:def:parser.setprompt-fn]
// [spec:dash:sem:parser.setprompt-fn]
#[inline(never)]
unsafe fn setprompt(which: c_int) {
    let mut smark: stackmark = mem::zeroed();
    let show: c_int;

    needprompt = 0;
    whichprompt = which;

    /* #ifdef SMALL: show = 1 */
    show = crate::histedit::el.is_null() as c_int;
    if show != 0 && (*crate::input::parsefile).nleft == 0 {
        pushstackmark(&mut smark, stackblocksize());
        crate::output::out2str(getprompt(ptr::null_mut()));
        popstackmark(&mut smark);
    }
}

// [spec:dash:def:parser.expandstr-fn]
// [spec:dash:sem:parser.expandstr-fn]
pub unsafe fn expandstr(ps: *const c_char) -> *const c_char {
    let file_stop: *mut crate::input::parsefile;
    let savehandler: *mut jmploc;
    let saveheredoclist: *mut heredoc;
    let mut result: *const c_char;
    let saveprompt: c_int;
    let mut jmploc: crate::error::jmploc = crate::error::jmploc::new();
    let mut n: node = mem::zeroed();
    let err: c_int;

    file_stop = crate::input::parsefile;

    /* XXX Fix (char *) cast. */
    setinputstring(ps as *mut c_char);

    saveheredoclist = heredoclist;
    heredoclist = ptr::null_mut();
    saveprompt = doprompt;
    doprompt = 0;
    needprompt = 0;
    result = ps;
    savehandler = handler;
    /* `if (unlikely(err = setjmp(jmploc.loc))) goto out;` — handlers in
     * this port are established by `eval::setjmp_catch`, not a real
     * `setjmp`, so the body goes in the closure and everything after the
     * call is the `out:` label. Raw pointers rather than captures keep
     * the C's aliasing (the closure writes locals the tail then reads). */
    let jl: *mut crate::error::jmploc = addr_of_mut!(jmploc);
    let np: *mut crate::nodes::node = addr_of_mut!(n);
    let resultp: *mut *const c_char = addr_of_mut!(result);
    err = crate::eval::setjmp_catch(jl, || unsafe {
        handler = jl;

        readtoken1(pgetc_eatbnl(), DQSYNTAX(), FAKEEOFMARK(), 0);

        (*np).narg.r#type = NARG;
        (*np).narg.next = ptr::null_mut();
        (*np).narg.text = wordtext;
        (*np).narg.backquote = backquotelist;

        expandarg(np, ptr::null_mut(), EXP_QUOTED);
        *resultp = stackblock();
    });

    /* out: */
    restore_handler_expandarg(savehandler, err);

    doprompt = saveprompt;
    unwindfiles(file_stop);
    heredoclist = saveheredoclist;

    result
}

/*
 * called by editline -- any expansions to the prompt
 *    should be added here.
 */

// [spec:dash:def:parser.getprompt-fn]
// [spec:dash:sem:parser.getprompt-fn]
pub unsafe fn getprompt(unused: *mut c_void) -> *const c_char {
    let prompt: *const c_char;

    match whichprompt {
        1 => {
            prompt = crate::var::ps1val();
        }
        2 => {
            prompt = crate::var::ps2val();
        }
        /* default: falls into case 0 outside DEBUG builds */
        _ => {
            return ptr::addr_of!(crate::mystring::nullstr) as *const c_char;
        }
    }

    expandstr(prompt)
}

// [spec:dash:def:parser.findkwd-fn]
// [spec:dash:sem:parser.findkwd-fn]
pub unsafe fn findkwd(s: *const c_char) -> *const *const c_char {
    crate::mystring::findstring(s, parsekwd.0.as_ptr(), parsekwd.0.len())
}

// ---------------------------------------------------------------------
// src/parser.h inline functions
// ---------------------------------------------------------------------

// [spec:dash:def:parser.goodname-fn]
// [spec:dash:sem:parser.goodname-fn]
pub unsafe fn goodname(p: *const c_char) -> c_int {
    (*endofname(p) == 0) as c_int
}

// [spec:dash:def:parser.parser-eof-fn]
// [spec:dash:sem:parser.parser-eof-fn]
pub unsafe fn parser_eof() -> c_int {
    (tokpushback != 0 && lasttoken == TEOF) as c_int
}

// ---------------------------------------------------------------------
// C library entry points the libc crate does not declare.
// ---------------------------------------------------------------------

extern "C" {
    fn mbrtowc(
        pwc: *mut libc::wchar_t,
        s: *const c_char,
        n: usize,
        ps: *mut libc::mbstate_t,
    ) -> usize;
    fn iswblank(wc: u32) -> c_int;
}
