//! Literal port of `src/parser.c` / `src/parser.h`.
//! Rules: `docs/spec/port/src/parser.md`.
//!
//! The shell command parser.  This is a 1:1 transcription of the C: the
//! same functions, the same control flow, the same side-effect order and
//! the same bugs.  `readtoken1` in particular keeps the C shape — one
//! function whose "internal subroutines" (`checkend`, `parseredir`,
//! `parsesub`, `parsebackq`, `parsearith`) are reached by `goto` in C and
//! are plain functions taking the shared state by `&mut` here.

use core::cell::{Cell, RefCell};
use core::mem;
use std::ffi::CStr;
use std::io::Write;

use bstr::{BStr, BString};
use core::ffi::{c_char, c_int, c_uint};

use crate::context::Shell;
use crate::error::Error;
use crate::expand::{EXP_QUOTED, expandarg, restore_handler_expandarg, rmescapes_owned};
use crate::input::{
    PEOA, pgetc, pgetc_eoa, popfile, pungetc, pungetn, pushstring, setinputstring, unwindfiles,
};
use crate::nodes::{
    NAND, NAPPEND, NBACKGND, NCLOBBER, NCMD, NFROM, NFROMFD, NFROMTO, NHERE, NOR, NPIPE, NREDIR,
    NSEMI, NSUBSHELL, NTO, NTOFD, NUNTIL, NWHILE, NXHERE, Node, NodeText, heredoc_body, narg,
    nbinary, ncase, nclist, ncmd, ndefun, ndup, nfile, nfor, nhere, nif, nnot, npipe, nredir,
};
use crate::syntax::{
    CBACK, CBQUOTE, CCTL, CDQUOTE, CENDQUOTE, CENDVAR, CEOF, CLP, CNL, CRP, CSQUOTE, CVAR, CWORD,
    PEOF, Syntax, digit_val, is_digit, is_in_name, is_name, is_special, syntax_at,
};

// ---------------------------------------------------------------------
// Local transcriptions of the C macros this file uses.
// ---------------------------------------------------------------------

/* `#define equal(s1, s2) (strcmp(s1, s2) == 0)` — src/mystring.h.  The
 * macro had one caller and `strcmp`'s ordering was never wanted there,
 * only its zero; `issimplecmd` now compares the two byte slices, and the
 * word's text already knows its own length. */

/* `USTPUTC` (src/memalloc.h:88) and `STADJUST` (:93) were the last two
 * `memalloc.h` macros this file expanded, and they are gone. Neither ever
 * touched the region allocator -- they were a store-and-advance and an
 * advance over a `BString`'s spare capacity -- which is why
 * [[delete-memalloc]] closed with them still here and recorded rehoming
 * them as bookkeeping.
 *
 * What deletes them is not a rehoming. Their two remaining callers,
 * `getmbc` and `dollarsq_escape`, took a raw cursor because the buffer
 * they wrote into belonged to someone else; both write into their own
 * scratch now, so the cursor is an offset and each macro is one indexed
 * statement written out with the C's name beside it. */

/// `MB_LEN_MAX` from `<limits.h>` (16 on the platforms dash targets).
const MB_LEN_MAX: usize = 16;

/*
 * The four syntax tables, as the *table pointers* `synstack->syntax`
 * carries around.  `syntax.h` spells them `basesyntax + SYNBASE` etc.;
 * Rust cannot form an interior pointer that is indexed negatively, so the
 * SYNBASE offset stays inside `syntax_at` and what travels is a pointer
 * to the whole table.  Pointer identity is what `readtoken1` compares.
 */

/// `#define BASESYNTAX (basesyntax + SYNBASE)`
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum SyntaxKind {
    Base,
    DoubleQuoted,
    SingleQuoted,
    Arithmetic,
}

impl SyntaxKind {
    fn table(self) -> &'static Syntax {
        match self {
            Self::Base => &crate::syntax::basesyntax,
            Self::DoubleQuoted => &crate::syntax::dqsyntax,
            Self::SingleQuoted => &crate::syntax::sqsyntax,
            Self::Arithmetic => &crate::syntax::arisyntax,
        }
    }
}

fn BASESYNTAX() -> SyntaxKind {
    SyntaxKind::Base
}

/// `#define DQSYNTAX (dqsyntax + SYNBASE)`
fn DQSYNTAX() -> SyntaxKind {
    SyntaxKind::DoubleQuoted
}

/// `#define SQSYNTAX (sqsyntax + SYNBASE)`
fn SQSYNTAX() -> SyntaxKind {
    SyntaxKind::SingleQuoted
}

/// `#define ARISYNTAX (arisyntax + SYNBASE)`
fn ARISYNTAX() -> SyntaxKind {
    SyntaxKind::Arithmetic
}

/// `syntax[c]` for a table held in a variable.
fn syn_at(tab: SyntaxKind, c: c_int) -> c_int {
    syntax_at(tab.table(), c) as c_int
}

// ---------------------------------------------------------------------
// src/token.h (generated by mktokens): values returned by readtoken.
// ---------------------------------------------------------------------

// [spec:posix:def:grammar.token-symbols]
pub const TEOF: c_int = 0;
pub const TBLANK: c_int = 1;
pub const TNL: c_int = 2;
pub const TSEMI: c_int = 3;
pub const TBACKGND: c_int = 4;
pub const TAND: c_int = 5;
pub const TOR: c_int = 6;
pub const TPIPE: c_int = 7;
pub const TLP: c_int = 8;
pub const TRP: c_int = 9;
pub const TENDCASE: c_int = 10;
pub const TFALLTHRU: c_int = 11;
pub const TENDBQUOTE: c_int = 12;
pub const TREDIR: c_int = 13;
pub const TWORD: c_int = 14;
pub const TNOT: c_int = 15;
pub const TCASE: c_int = 16;
pub const TDO: c_int = 17;
pub const TDONE: c_int = 18;
pub const TELIF: c_int = 19;
pub const TELSE: c_int = 20;
pub const TESAC: c_int = 21;
pub const TFI: c_int = 22;
pub const TFOR: c_int = 23;
pub const TIF: c_int = 24;
pub const TIN: c_int = 25;
pub const TTHEN: c_int = 26;
pub const TUNTIL: c_int = 27;
pub const TWHILE: c_int = 28;
pub const TBEGIN: c_int = 29;
pub const TEND: c_int = 30;

// ---------------------------------------------------------------------
// src/token_vars.h (generated by mktokens), included by parser.c.
// ---------------------------------------------------------------------

/// Array indicating which tokens mark the end of a list.
static tokendlist: [c_char; 31] = [
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
];

static tokname: [&CStr; 31] = [
    c"end of file",
    c"blank",
    c"newline",
    c"\";\"",
    c"\"&\"",
    c"\"&&\"",
    c"\"||\"",
    c"\"|\"",
    c"\"(\"",
    c"\")\"",
    c"\";;\"",
    c"\";&\"",
    c"\"`\"",
    c"redirection",
    c"word",
    c"\"!\"",
    c"\"case\"",
    c"\"do\"",
    c"\"done\"",
    c"\"elif\"",
    c"\"else\"",
    c"\"esac\"",
    c"\"fi\"",
    c"\"for\"",
    c"\"if\"",
    c"\"in\"",
    c"\"then\"",
    c"\"until\"",
    c"\"while\"",
    c"\"{\"",
    c"\"}\"",
];

pub const KWDOFFSET: c_int = 15;

// [spec:posix:def:grammar.reserved-word-tokens]
// [spec:posix:def:token.reserved-words]
// [spec:posix:def:token.reserved-words-optional]
// [spec:posix:req:token.reserved-word-time]
// [spec:posix:def:token.reserved-words-trailing-colon]
static parsekwd: [&CStr; 16] = [
    c"!",
    c"case",
    c"do",
    c"done",
    c"elif",
    c"else",
    c"esac",
    c"fi",
    c"for",
    c"if",
    c"in",
    c"then",
    c"until",
    c"while",
    c"{",
    c"}",
];

// ---------------------------------------------------------------------
// src/parser.h
// ---------------------------------------------------------------------

/* control characters in argument strings */
pub const CTL_FIRST: c_int = -127; /* first 'special' character */
pub const CTLESC: c_int = -127; /* escape next character */
pub const CTLVAR: c_int = -126; /* variable defn */
pub const CTLENDVAR: c_int = -125;
pub const CTLBACKQ: c_int = -124;
pub const CTLMBCHAR: c_int = -123;
pub const CTLARI: c_int = -122; /* arithmetic expression */
pub const CTLENDARI: c_int = -121;
pub const CTLQUOTEMARK: c_int = -120;
pub const CTL_LAST: c_int = -120; /* last 'special' character */

/* variable substitution byte (follows CTLVAR) */
pub const VSTYPE: c_int = 0x0f; /* type of variable substitution */
pub const VSNUL: c_int = 0x10; /* colon--treat the empty string as unset */
pub const VSBIT: c_int = 0x20; /* Ensure subtype is not zero */

/* values of VSTYPE field */
pub const VSNORMAL: c_int = 0x1; /* normal variable:  $var or ${var} */
pub const VSMINUS: c_int = 0x2; /* ${var-text} */
pub const VSPLUS: c_int = 0x3; /* ${var+text} */
pub const VSQUESTION: c_int = 0x4; /* ${var?message} */
pub const VSASSIGN: c_int = 0x5; /* ${var=text} */
pub const VSTRIMRIGHT: c_int = 0x6; /* ${var%pattern} */
pub const VSTRIMRIGHTMAX: c_int = 0x7; /* ${var%%pattern} */
pub const VSTRIMLEFT: c_int = 0x8; /* ${var#pattern} */
pub const VSTRIMLEFTMAX: c_int = 0x9; /* ${var##pattern} */
pub const VSLENGTH: c_int = 0xa; /* ${#var} */
/* VSLENGTH must come last. */

/* values of checkkwd variable */
pub const CHKALIAS: c_int = 0x1;
pub const CHKKWD: c_int = 0x2;
pub const CHKNL: c_int = 0x4;
pub const CHKEOFMARK: c_int = 0x8;

/// What the C returns from `list()` and `parsecmd`.
///
/// `union node *` is three things there at once: a tree, `NULL` for a blank
/// line, and the sentinel `#define NEOF ((union node *)&tokpushback)` for end
/// of file. Only `list(1)?` — that is, `parsecmd` — can produce `NEOF`,
/// because the `n1 = NEOF` assignment is guarded by `chknl == 0` and `chknl`
/// is only zero when `nlflag & 1`.
pub enum ParseResult {
    /// the C's `NEOF`
    Eof,
    /// a tree, or `None` where the C returned `NULL` for a blank line
    Tree(Option<Node>),
}

impl ParseResult {
    /// The tree, for the callers of `list()` that cannot see `NEOF`.
    fn into_node(self) -> Option<Node> {
        match self {
            ParseResult::Tree(n) => n,
            ParseResult::Eof => None,
        }
    }
}

/// `readtoken1`'s `eofmark` argument.
///
/// The C passes a `char *` that is overloaded three ways: NULL means "read a
/// word", `FAKEEOFMARK` (`(char *)1`) means "read a word but behave as if a
/// here-document were in progress", and anything else is the delimiter of a
/// real here-document. Only the third carries bytes, so only the third owns
/// any.
#[derive(Clone, Copy)]
enum EofMark<'a> {
    /// C: `NULL`
    None,
    /// C: `FAKEEOFMARK` — what `expandstr` passes
    Fake,
    /// C: the here-document's delimiter, after `rmescapes`
    Word(&'a BStr),
}

impl<'a> EofMark<'a> {
    /// `eofmark == NULL`
    fn is_none(self) -> bool {
        matches!(self, EofMark::None)
    }

    /// `#define realeofmark(m) ((m) && (m) != FAKEEOFMARK)` — src/parser.c
    // [spec:dash:def:parser.realeofmark-fn]
    // [spec:dash:sem:parser.realeofmark-fn]
    fn real(self) -> Option<&'a BStr> {
        match self {
            EofMark::Word(w) => Some(w),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------

// [spec:dash:def:parser.heredoc]
/// The C carries `union node *here`, a back pointer to the redirection node,
/// and reads `here->type` in `parseheredoc` to decide whether the body is
/// expanded. Owning the tree makes that pointer impossible, so what travels
/// is the shared body slot (`nodes::heredoc_body`) plus the one bit of the
/// node's type `parseheredoc` actually wanted. `parsefname` settles the type
/// immediately before appending, so the bit is final when it is recorded.
pub struct heredoc {
    /// the slot in the redirection node the body lands in
    pub doc: heredoc_body,
    /// the node is `NXHERE`: read the body with `DQSYNTAX`, not `SQSYNTAX`
    pub expand: bool,
    /// string indicating end of input, with `rmescapes` already applied
    pub eofmark: BString,
    pub striptabs: c_int, /* if set, strip leading tabs */
}

// [spec:dash:def:parser.synstack]
/// One owned parse context. [`Rt1::synstack`] holds the contexts from the
/// base level through the current level, so the C's `next` link is the
/// preceding element and its `prev` link is spare `Vec` capacity left by a
/// pop. No cursor into the vector survives a push or pop.
pub struct synstack {
    pub syntax: SyntaxKind,
    pub innerdq: c_int,
    pub varpushed: c_int,
    pub dblquote: c_int,
    pub backq: c_int,      /* Inside back quotes (here-doc word only). */
    pub varnest: c_int,    /* levels of variables expansion */
    pub parenlevel: c_int, /* levels of parens in arithmetic */
    pub dqvarnest: c_int,  /* levels of variables expansion within double quotes */
}

/// A token together with the word property the C parser carried in the
/// separate `quoteflag` global.
#[derive(Clone, Copy)]
struct Token {
    kind: c_int,
    quoted: c_int,
}

impl Token {
    const fn plain(kind: c_int) -> Self {
        Self { kind, quoted: 0 }
    }
}

// [spec:dash:def:parser.isassignment-fn]
// [spec:dash:sem:parser.isassignment-fn]
pub fn isassignment(locale: &nsh_platform::Locale, text: &BStr) -> c_int {
    let end = endofname(locale, text);
    if end == 0 {
        return 0;
    }
    (text.get(end) == Some(&b'=')) as c_int
}

// [spec:dash:def:parser.issimplecmd-fn]
// [spec:dash:sem:parser.issimplecmd-fn]
pub fn issimplecmd(n: Option<&Node>, name: &BStr) -> c_int {
    match n {
        Some(n) if n.node_type() == NCMD => {
            let args = &n.ncmd().args;
            (!args.is_empty()
                && args[0].narg().text.as_bstr() == name)
                as c_int
        }
        _ => 0,
    }
}

/// The last word read, as its shell-visible bytes.
///
/// Input storage retains the terminating NUL expected by the lexer;
/// `cstr_prefix` removes it without exposing a pointer.
fn wordtext(sh: &Shell) -> &BStr {
    crate::mystring::cstr_prefix(&sh.input.wordtext)
}

/// The last word read, as a node's owned text.
///
/// The bytes are cloned into the syntax tree's owned storage.
fn wordtext_node(sh: &mut Shell) -> NodeText {
    NodeText::new(sh.input.wordtext.clone())
}

/*
 * Read and parse a command.  Returns NEOF on end of file.  (NULL is a
 * valid parse tree indicating a blank line.)
 */

// [spec:dash:def:parser.parsecmd-fn]
// [spec:dash:sem:parser.parsecmd-fn]
// [spec:posix:syn:grammar.program]
// [spec:posix:def:cmd.command-kinds]
// [spec:posix:syn:cmd.format-descriptions-informal]
// [spec:posix:req:cmd.no-size-limit]
// [spec:nsh:req:compat.bash.parse-boundary]
pub fn parsecmd(sh: &mut Shell, interact: c_int) -> Result<ParseResult, Error> {
    let dialect = sh.options.dialect();
    sh.input.begin_parse(dialect);
    sh.input.tokpushback = 0;
    sh.input.heredoclist = Vec::new();
    sh.input.doprompt = interact;
    if sh.input.doprompt != 0 {
        setprompt(sh, sh.input.doprompt);
    }
    sh.input.needprompt = 0;
    list(sh, 1)
}

// [spec:dash:def:parser.list-fn]
// [spec:dash:sem:parser.list-fn]
// [spec:posix:syn:grammar.separators]
// [spec:posix:def:cmd.list-definition]
// [spec:posix:def:cmd.compound-list-definition]
// [spec:posix:req:cmd.list-separator-semantics]
fn list(sh: &mut Shell, nlflag: c_int) -> Result<ParseResult, Error> {
    let mut nlflag = nlflag;
    let chknl = if nlflag & 1 != 0 { 0 } else { CHKNL };
    let mut n1: Option<Node>;
    let mut n2: Option<Node>;
    let mut tok: c_int;

    n1 = None;
    loop {
        tok = readtoken(sh, chknl | CHKKWD | CHKALIAS)?;
        match tok {
            TNL => {
                parseheredoc(sh)?;
                return Ok(ParseResult::Tree(n1));
            }

            TEOF => {
                let eof = n1.is_none() && chknl == 0;
                /* out_eof: */
                parseheredoc(sh)?;
                sh.input.tokpushback += 1;
                sh.input.lasttoken = TEOF;
                return if eof {
                    Ok(ParseResult::Eof)
                } else {
                    Ok(ParseResult::Tree(n1))
                };
            }
            _ => {}
        }

        sh.input.tokpushback += 1;
        if nlflag == 2 && tokendlist[tok as usize] != 0 {
            return Ok(ParseResult::Tree(n1));
        }
        nlflag |= 2;

        /* The line the backgrounded command starts on, captured before
         * anything consumes it. `command()?` and `pipeline()?` both take
         * their `savelinno` at this same point, so a wrapper built here
         * records the line its contents record. */
        let savelinno: c_int = crate::plinno!(sh);

        n2 = andor(sh)?;
        tok = readtoken(sh, 0)?;
        if tok == TBACKGND {
            /* The C dereferences n2 unconditionally here. */
            if n2.as_ref().unwrap().node_type() == NPIPE {
                n2.as_mut().unwrap().npipe_mut().backgnd = 1;
            } else {
                if n2.as_ref().unwrap().node_type() != NREDIR {
                    /* dash never writes `linno` on this wrapper, so
                     * `evalsubshell` copies whatever `stalloc` returned
                     * into `lineno` and `errlinno` -- both observable, via
                     * `$LINENO` and the `sh: N:` diagnostic prefix. It is
                     * reached only on a fork failure, which is why nothing
                     * has noticed.
                     *
                     * There is no bug-for-bug option here: reading
                     * uninitialised memory is not something a safe
                     * language reproduces, so the only question is which
                     * correct value to write. See
                     * [dec:nsh:we-own-the-defects] and
                     * `docs/divergences.md`. */
                    n2 = Some(Node::Redir(nredir {
                        r#type: 0,
                        linno: savelinno,
                        n: n2.map(Box::new),
                        redirect: Vec::new(),
                    }));
                }
                n2.as_mut().unwrap().nredir_mut().r#type = NBACKGND;
            }
        }
        if n1.is_none() {
            n1 = n2;
        } else {
            n1 = Some(Node::Binary(nbinary {
                r#type: NSEMI,
                ch1: n1.map(Box::new),
                ch2: n2.map(Box::new),
            }));
        }
        match tok {
            TEOF => {
                /* goto out_eof */
                parseheredoc(sh)?;
                sh.input.tokpushback += 1;
                sh.input.lasttoken = TEOF;
                return Ok(ParseResult::Tree(n1));
            }
            TNL => {
                sh.input.tokpushback += 1;
                /* fall through */
            }
            TBACKGND | TSEMI => {}
            _ => {
                if chknl == 0 {
                    return Err(synexpect(sh, -1));
                }
                sh.input.tokpushback += 1;
                return Ok(ParseResult::Tree(n1));
            }
        }
    }
}

// [spec:dash:def:parser.andor-fn]
// [spec:dash:sem:parser.andor-fn]
// [spec:posix:syn:grammar.list-and-or]
// [spec:posix:def:cmd.and-or-list-definition]
// [spec:posix:req:cmd.and-or-precedence]
// [spec:posix:syn:cmd.and-list-format]
// [spec:posix:syn:cmd.or-list-format]
fn andor(sh: &mut Shell) -> Result<Option<Node>, Error> {
    let mut n1: Option<Node>;
    let mut t: c_int;

    n1 = pipeline(sh, 0)?;
    loop {
        t = readtoken(sh, 0)?;
        if t == TAND {
            t = NAND;
        } else if t == TOR {
            t = NOR;
        } else {
            sh.input.tokpushback += 1;
            return Ok(n1);
        }
        let n2 = pipeline(sh, CHKNL | CHKKWD | CHKALIAS)?;
        n1 = Some(Node::Binary(nbinary {
            r#type: t,
            ch1: n1.map(Box::new),
            ch2: n2.map(Box::new),
        }));
    }
}

// [spec:dash:def:parser.pipeline-fn]
// [spec:dash:sem:parser.pipeline-fn]
// [spec:posix:syn:grammar.pipeline]
// [spec:posix:def:cmd.pipeline-definition]
// [spec:posix:syn:cmd.pipeline-format]
// [spec:posix:req:cmd.pipeline-bang-subshell-separation]
fn pipeline(sh: &mut Shell, kwd: c_int) -> Result<Option<Node>, Error> {
    let mut n1: Option<Node>;
    let mut negate: c_int;

    negate = 0;
    /* TRACE(("pipeline: entered\n")); */
    let command_kwd = if readtoken(sh, kwd)? == TNOT {
        negate = (negate == 0) as c_int;
        CHKKWD | CHKALIAS
    } else {
        sh.input.tokpushback += 1;
        0
    };
    n1 = command(sh, command_kwd)?;
    if readtoken(sh, 0)? == TPIPE {
        /* Every `stalloc(sizeof(struct nodelist))` the C does here is one
         * `Vec` slot; the list is built front to back either way, and
         * `command()?` cannot return NULL without having raised first. */
        let mut cmdlist: Vec<Node> = vec![n1.take().unwrap()];
        loop {
            cmdlist.push(command(sh, CHKNL | CHKKWD | CHKALIAS)?.unwrap());
            if readtoken(sh, 0)? != TPIPE {
                break;
            }
        }
        n1 = Some(Node::Pipe(npipe {
            backgnd: 0,
            cmdlist,
        }));
    }
    sh.input.tokpushback += 1;
    if negate != 0 {
        Ok(Some(Node::Not(nnot {
            com: n1.map(Box::new),
        })))
    } else {
        Ok(n1)
    }
}

// [spec:dash:def:parser.command-fn]
// [spec:dash:sem:parser.command-fn]
// [spec:posix:syn:grammar.command]
// [spec:posix:syn:grammar.subshell-and-compound-list]
// [spec:posix:syn:grammar.for-clause]
// [spec:posix:syn:grammar.for-name]
// [spec:posix:syn:grammar.third-word-of-for-and-case]
// [spec:posix:syn:grammar.case-statement-termination]
// [spec:posix:syn:grammar.if-clause]
// [spec:posix:syn:grammar.while-until-clause]
// [spec:posix:syn:grammar.brace-group-and-do-group]
// [spec:posix:def:cmd.compound-definition]
// [spec:posix:req:cmd.group-double-paren-ambiguity]
// [spec:posix:req:cmd.for-do-done-delimiters]
// [spec:posix:syn:cmd.for-format]
// [spec:posix:syn:cmd.case-clause-syntax]
// [spec:posix:syn:cmd.case-format]
// [spec:posix:syn:cmd.if-format]
// [spec:posix:syn:cmd.while-format]
// [spec:posix:syn:cmd.until-format]
fn command(sh: &mut Shell, kwd: c_int) -> Result<Option<Node>, Error> {
    let mut n1: Option<Node>;
    let mut t: c_int;
    let savelinno: c_int;

    savelinno = crate::plinno!(sh);

    let mut goto_redir = false;
    let tok = readtoken(sh, kwd)?;
    if tok == TIF {
        /* The C threads the elif chain through `elsepart` on the way down,
         * writing each new nif into its parent before parsing it.  An owned
         * tree cannot hand out that parent pointer, so the clauses are
         * collected in parse order and folded back up afterwards; the
         * sequence of `list(0)?` calls — and so of everything they read — is
         * unchanged. */
        let mut clauses: Vec<(Option<Node>, Option<Node>)> = Vec::new();
        let test = list(sh, 0)?.into_node();
        if readtoken(sh, 0)? != TTHEN {
            return Err(synexpect(sh, TTHEN));
        }
        let ifpart = list(sh, 0)?.into_node();
        clauses.push((test, ifpart));
        while readtoken(sh, 0)? == TELIF {
            let test = list(sh, 0)?.into_node();
            if readtoken(sh, 0)? != TTHEN {
                return Err(synexpect(sh, TTHEN));
            }
            let ifpart = list(sh, 0)?.into_node();
            clauses.push((test, ifpart));
        }
        let mut elsepart: Option<Node> = if sh.input.lasttoken == TELSE {
            list(sh, 0)?.into_node()
        } else {
            sh.input.tokpushback += 1;
            None
        };
        for (test, ifpart) in clauses.into_iter().rev() {
            elsepart = Some(Node::If(nif {
                test: test.map(Box::new),
                ifpart: ifpart.map(Box::new),
                elsepart: elsepart.map(Box::new),
            }));
        }
        n1 = elsepart;
        t = TFI;
    } else if tok == TWHILE || tok == TUNTIL {
        let got: c_int;
        let ty = if sh.input.lasttoken == TWHILE { NWHILE } else { NUNTIL };
        let ch1 = list(sh, 0)?.into_node();
        got = readtoken(sh, 0)?;
        if got != TDO {
            return Err(synexpect(sh, TDO));
        }
        let ch2 = list(sh, 0)?.into_node();
        n1 = Some(Node::Binary(nbinary {
            r#type: ty,
            ch1: ch1.map(Box::new),
            ch2: ch2.map(Box::new),
        }));
        t = TDONE;
    } else if tok == TFOR {
        let var_token = readtoken_with_flags(sh, 0)?;
        if var_token.kind != TWORD
            || var_token.quoted != 0
            || goodname(&sh.locale, wordtext(sh)) == 0
        {
            return Err(synerror(sh, b"Bad for loop variable"));
        }
        /* the C stores `wordtext` into the node here, before any further
         * token read can overwrite it */
        let var = wordtext_node(sh);
        let mut args: Vec<Node> = Vec::new();
        if readtoken(sh, CHKNL | CHKKWD | CHKALIAS)? == TIN {
            while readtoken(sh, 0)? == TWORD {
                args.push(Node::Arg(narg {
                    text: wordtext_node(sh),
                    backquote: core::mem::take(&mut sh.input.backquotelist),
                }));
            }
            if sh.input.lasttoken != TNL && sh.input.lasttoken != TSEMI {
                return Err(synexpect(sh, -1));
            }
        } else {
            /* The implicit `"$@"` of a `for` with no `in`. `dolatstr` is
             * seven bytes ending in the NUL that a word's text keeps, so
             * the value is the static and not what a C reader makes of
             * it. */
            let dolatstr: [u8; 7] = crate::mystring::dolatstr.map(|c| c as u8);
            args.push(Node::Arg(narg {
                text: NodeText::new(BString::from(&dolatstr[..])),
                backquote: Vec::new(),
            }));
            /*
             * Newline or semicolon here is optional (but note
             * that the original Bourne shell only allowed NL).
             */
            if sh.input.lasttoken != TSEMI {
                sh.input.tokpushback += 1;
            }
        }
        if readtoken(sh, CHKNL | CHKKWD | CHKALIAS)? != TDO {
            return Err(synexpect(sh, TDO));
        }
        let body = list(sh, 0)?.into_node();
        n1 = Some(Node::For(nfor {
            linno: savelinno,
            args,
            body: body.map(Box::new),
            var,
        }));
        t = TDONE;
    } else if tok == TCASE {
        if readtoken(sh, 0)? != TWORD {
            return Err(synexpect(sh, TWORD));
        }
        let expr = Node::Arg(narg {
            text: wordtext_node(sh),
            backquote: core::mem::take(&mut sh.input.backquotelist),
        });
        if readtoken(sh, CHKNL | CHKKWD | CHKALIAS)? != TIN {
            return Err(synexpect(sh, TIN));
        }
        let mut cases: Vec<Node> = Vec::new();
        'next_case: loop {
            // [spec:posix:syn:grammar.case-clause]
            // Rule 4 applies here, before an optional `(`, and nowhere in
            // the pattern loop below: words after `(` or `|` stay patterns
            // even when their spelling is otherwise a reserved word.
            t = readtoken(sh, CHKNL | CHKKWD)?;
            while t != TESAC {
                if sh.input.lasttoken == TLP {
                    readtoken(sh, 0)?;
                }
                let mut pattern: Vec<Node> = Vec::new();
                loop {
                    if sh.input.lasttoken < TWORD {
                        return Err(synexpect(sh, TWORD));
                    }
                    pattern.push(Node::Arg(narg {
                        text: wordtext_node(sh),
                        backquote: core::mem::take(&mut sh.input.backquotelist),
                    }));
                    if readtoken(sh, 0)? != TPIPE {
                        break;
                    }
                    readtoken(sh, 0)?;
                }
                if sh.input.lasttoken != TRP {
                    return Err(synexpect(sh, TRP));
                }
                let body = list(sh, 2)?.into_node();
                t = readtoken(sh, CHKNL | CHKKWD)?;
                cases.push(Node::Clist(nclist {
                    pattern,
                    body: body.map(Box::new),
                    fallthrough: t == TFALLTHRU,
                }));

                if t != TESAC {
                    if t != TENDCASE && t != TFALLTHRU {
                        return Err(synexpect(sh, TENDCASE));
                    } else {
                        continue 'next_case;
                    }
                }
            }
            break;
        }
        n1 = Some(Node::Case(ncase {
            linno: savelinno,
            expr: Some(Box::new(expr)),
            cases,
        }));
        goto_redir = true;
    } else if tok == TLP {
        let inner = list(sh, 0)?.into_node();
        n1 = Some(Node::Redir(nredir {
            r#type: NSUBSHELL,
            linno: savelinno,
            n: inner.map(Box::new),
            redirect: Vec::new(),
        }));
        t = TRP;
    } else if tok == TBEGIN {
        n1 = list(sh, 0)?.into_node();
        t = TEND;
    } else if tok == TWORD || tok == TREDIR {
        sh.input.tokpushback += 1;
        return simplecmd(sh);
    } else {
        return Err(synexpect(sh, -1));
        /* NOTREACHED */
    }

    if !goto_redir {
        if readtoken(sh, 0)? != t {
            return Err(synexpect(sh, t));
        }
    }

    /* redir: */
    /* Now check for redirection which may follow command */
    let mut redir: Vec<Node> = Vec::new();
    let mut redir_kwd = CHKKWD | CHKALIAS;
    while readtoken(sh, redir_kwd)? == TREDIR {
        redir_kwd = 0;
        /* The C copies `redirnode` into a local *before* `parsefname`,
         * because the token read inside it can set the global again.
         * Taking ownership of it here is the same guarantee. */
        let mut n2 = core::mem::take(&mut sh.input.redirnode).unwrap();
        parsefname(sh, &mut n2)?;
        redir.push(n2);
    }
    sh.input.tokpushback += 1;
    if !redir.is_empty() {
        if n1.as_ref().map_or(true, |n| n.node_type() != NSUBSHELL) {
            n1 = Some(Node::Redir(nredir {
                r#type: NREDIR,
                linno: savelinno,
                n: n1.map(Box::new),
                redirect: Vec::new(),
            }));
        }
        n1.as_mut().unwrap().nredir_mut().redirect = redir;
    }

    Ok(n1)
}

// [spec:dash:def:parser.simplecmd-fn]
// [spec:dash:sem:parser.simplecmd-fn]
// [spec:posix:req:redir.not-in-command-arguments]
// [spec:posix:syn:grammar.simple-command]
// [spec:posix:syn:grammar.assignment-first-word]
// [spec:posix:syn:grammar.assignment-word-recognition]
// [spec:posix:syn:grammar.function-definition]
// [spec:posix:syn:grammar.function-name]
// [spec:posix:req:grammar.function-body-no-expansion]
// [spec:posix:def:cmd.simple-definition]
// [spec:posix:def:cmd.function-definition-term]
// [spec:posix:syn:cmd.function-format]
// [spec:posix:req:cmd.function-name-requirements]
// [spec:posix:req:cmd.function-no-expansion-at-definition]
fn simplecmd(sh: &mut Shell) -> Result<Option<Node>, Error> {
    let mut args: Vec<Node> = Vec::new();
    let mut vars: Vec<Node> = Vec::new();
    let mut redir: Vec<Node> = Vec::new();
    let mut savecheckkwd: c_int;
    let savelinno: c_int;

    savecheckkwd = CHKALIAS;
    savelinno = crate::plinno!(sh);
    loop {
        let tok = readtoken(sh, savecheckkwd)?;
        if tok == TWORD {
            let n = Node::Arg(narg {
                text: wordtext_node(sh),
                backquote: core::mem::take(&mut sh.input.backquotelist),
            });
            if savecheckkwd != 0 && isassignment(&sh.locale, wordtext(sh)) != 0 {
                vars.push(n);
            } else {
                args.push(n);
                savecheckkwd = 0;
            }
        } else if tok == TREDIR {
            let mut n = core::mem::take(&mut sh.input.redirnode).unwrap();
            parsefname(sh, &mut n)?; /* read name of redirection file */
            redir.push(n);
        } else {
            /* The C's `app == &args->narg.next` says the argument list holds
             * exactly one word, which is the name being defined. */
            if tok == TLP && args.len() == 1 && vars.is_empty() && redir.is_empty() {
                /* We have a function */
                if readtoken(sh, 0)? != TRP {
                    return Err(synexpect(sh, TRP));
                }
                /* the word becomes the function's name; the C keeps the same
                 * `char *` when it relabels the node */
                let word: narg = args.pop().unwrap().into_narg();
                let bcmd = crate::exec::builtin(word.text.as_bstr());
                if goodname(&sh.locale, word.text.as_bstr()) == 0
                    || bcmd.is_some_and(|cmd| {
                        (cmd.flags & crate::builtins::BUILTIN_SPECIAL) != 0
                    })
                {
                    return Err(synerror(sh, b"Bad function name"));
                }
                /* The C relabels the NARG node NDEFUN in place: a union
                 * type-pun that copies `narg.text` (offset 16) into
                 * `ndefun.text` (offset 8) and overwrites the rest.  The
                 * NARG's backquote list is dropped either way. */
                let linno = crate::plinno!(sh);
                let body = command(sh, CHKNL | CHKKWD | CHKALIAS)?;
                return Ok(Some(Node::Defun(ndefun {
                    linno,
                    text: word.text,
                    body: body.map(Box::new),
                })));
            }
            /* fall through */
            /* default: */
            sh.input.tokpushback += 1;
            break;
        }
    }
    /* out: */
    Ok(Some(Node::Cmd(ncmd {
        linno: savelinno,
        assign: vars,
        args,
        redirect: redir,
    })))
}

// [spec:dash:def:parser.makename-fn]
// [spec:dash:sem:parser.makename-fn]
pub(crate) fn makename(sh: &mut Shell) -> Node {
    Node::Arg(narg {
        text: wordtext_node(sh),
        backquote: core::mem::take(&mut sh.input.backquotelist),
    })
}

// [spec:dash:def:parser.fixredir-fn]
// [spec:dash:sem:parser.fixredir-fn]
//
// Called twice with different owners: from `parsefname` while the node is
// still being built (`err == 0`), and from `expredir` on a tree that may be a
// shared function definition (`err != 0`).  Only the second writes at run
// time, and it only writes `dupfd`, which is why that field is the `Cell`.
pub fn fixredir(
    sh: &mut Shell,
    n: &Node,
    text: &BStr,
    err: c_int,
) -> Result<(), Error> {
    /* TRACE(("Fix redir %s %d\n", text, err)); */
    let d = n.ndup();
    if err == 0 {
        *d.vname.borrow_mut() = None;
    }

    let text = crate::mystring::cstr_prefix(text);
    if text.len() == 1 && is_digit(text[0] as c_int) {
        d.dupfd.set(digit_val(text[0] as c_int));
    } else if text == BStr::new(b"-") {
        d.dupfd.set(-1);
    } else {
        if err != 0 {
            let mut message = b"Bad fd number: ".to_vec();
            message.extend_from_slice(text);
            /* A stop before `sh_error` became a value, and still one. */
            return Err(sh.sh_error_value(&message));
        } else {
            *d.vname.borrow_mut() = Some(Box::new(makename(sh)));
        }
    }
    Ok(())
}

// [spec:dash:def:parser.parsefname-fn]
// [spec:dash:sem:parser.parsefname-fn]
// [spec:posix:req:redir.here-doc-quoted-delimiter]
// [spec:posix:req:redir.here-doc-unquoted-delimiter]
// [spec:posix:req:grammar.here-doc-redirection]
//
// The C reads the redirection node out of the `redirnode` global; here the
// caller has already taken ownership of it, because the `readtoken` below can
// set that global again before this function is done with it.
fn parsefname(sh: &mut Shell, n: &mut Node) -> Result<(), Error> {
    let token = readtoken_with_flags(
        sh,
        if n.node_type() == NHERE {
            CHKEOFMARK
        } else {
            0
        },
    )?;
    if token.kind != TWORD {
        return Err(synexpect(sh, -1));
    }
    if n.node_type() == NHERE {
        /* the C reads the `heredoc` global here, after the token read */
        let mut here: heredoc = core::mem::take(&mut sh.input.heredoc).unwrap();

        if token.quoted == 0 {
            n.nhere_mut().r#type = NXHERE;
        }
        /* TRACE(("Here document %d\n", n->type)); */
        /* `rmescapes` rewrites the word in place and can only shorten it, so
         * the new terminator is where the delimiter now ends. */
        let mut mark = core::mem::take(&mut sh.input.wordtext);
        /* The delimiter is compared as bytes, so the terminator that made
         * it a C string is not part of it. */
        let n_mark = rmescapes_owned(&mut mark);
        mark.truncate(n_mark);
        here.eofmark = mark;
        /* `parseheredoc` asked the node whether it was NXHERE; the type is
         * settled above, so the answer travels with the here-document. */
        here.expand = n.nhere().r#type == NXHERE;
        sh.input.heredoclist.push(here);
    } else if n.node_type() == NTOFD || n.node_type() == NFROMFD {
        let word = wordtext(sh).to_owned();
        fixredir(sh, n, BStr::new(word.as_slice()), 0)?;
    } else {
        n.nfile_mut().fname = Some(Box::new(makename(sh)));
    }
    Ok(())
}

/*
 * Input any here documents.
 */

// [spec:dash:def:parser.parseheredoc-fn]
// [spec:dash:sem:parser.parseheredoc-fn]
// [spec:posix:req:redir.here-doc-line-continuation]
// [spec:posix:req:redir.here-doc-backslash]
// [spec:posix:req:redir.here-doc-multiple]
// [spec:posix:req:redir.here-doc-ps2]
// [spec:posix:req:token.here-document-mode]
fn parseheredoc(sh: &mut Shell) -> Result<(), Error> {
    let list: Vec<heredoc> = core::mem::take(&mut sh.input.heredoclist);

    for here in list {
        if sh.input.needprompt != 0 {
            setprompt(sh, 2);
        }
        let mark = EofMark::Word(BStr::new(&here.eofmark));
        /* The C reads the first character inside the argument list. The
         * receiver is passed there too, so the read is its own statement:
         * evaluation order is unchanged, the first character is still
         * read before `readtoken1` runs. */
        if !here.expand {
            let firstc = pgetc(sh)?;
            readtoken1(sh, firstc, SQSYNTAX(), mark, here.striptabs, 0)?;
        } else {
            let firstc = pgetc_eatbnl(sh)?;
            readtoken1(sh, firstc, DQSYNTAX(), mark, here.striptabs, 0)?;
        }
        let n = Node::Arg(narg {
            text: wordtext_node(sh),
            backquote: core::mem::take(&mut sh.input.backquotelist),
        });
        /* `here->here->nhere.doc = n` in the C — the same slot, reached
         * through a shared handle instead of a back pointer.  It is written
         * exactly once, so a second write cannot happen. */
        here.doc.fill(n);
    }
    Ok(())
}

// [spec:dash:def:parser.readtoken-fn]
// [spec:dash:sem:parser.readtoken-fn]
pub(crate) fn readtoken(sh: &mut Shell, kwd: c_int) -> Result<c_int, Error> {
    Ok(readtoken_with_flags(sh, kwd)?.kind)
}

/// Read a token without discarding whether a word contained quoting.
///
/// `kwd` is the C parser's `checkkwd` value for this read. Making it an
/// argument prevents one parse from changing the next parse's mode.
// [spec:posix:syn:grammar.token-context-dependent-distinction]
// [spec:posix:req:grammar.highest-numbered-rule-applies]
// [spec:posix:syn:grammar.command-name]
// [spec:posix:sem:token.categorization]
// [spec:posix:req:token.alias-substitution-conditions]
// [spec:posix:req:token.alias-reserved-word-unspecified]
// [spec:posix:req:token.alias-replacement]
// [spec:posix:req:token.reserved-word-recognition-contexts]
fn readtoken_with_flags(sh: &mut Shell, mut kwd: c_int) -> Result<Token, Error> {
    let mut token: Token;

    'top: loop {
        token = xxreadtoken(sh, kwd & CHKEOFMARK)?;

        /*
         * eat newlines
         */
        if kwd & CHKNL != 0 {
            while token.kind == TNL {
                parseheredoc(sh)?;
                /* The alias bit is dropped with the rest: dash clears the
                 * whole of `checkkwd` here, and the bit lived in it. */
                crate::input::clear_alias_boundary(sh);
                token = xxreadtoken(sh, kwd & CHKEOFMARK)?;
            }
        }

        /* `popstring` sets this while `xxreadtoken` runs. The bit belongs
         * to the input boundary now; this is the same hand-off point. */
        if crate::input::take_alias_boundary(sh) != 0 {
            kwd |= CHKALIAS;
        }

        if token.kind != TWORD || token.quoted != 0 {
            break 'top;
        }

        /*
         * check for keywords
         */
        if kwd & CHKKWD != 0 {
            if let Some(index) = findkwd(wordtext(sh)) {
                token.kind = index as c_int + KWDOFFSET;
                sh.input.lasttoken = token.kind;
                break 'top;
            }
        }

        if kwd & CHKALIAS != 0 {
            /* Hoisted: the receiver cannot appear twice in one argument
             * list. A raw pointer ends its borrow at the `let`, and the
             * word it points at is the parser's own, not the alias's. */
            let name = wordtext(sh).to_owned();
            if let Some(value) = crate::alias::lookup_alias(sh, BStr::new(name.as_slice()), true) {
                if !value.is_empty() {
                    pushstring(sh, BStr::new(value.as_slice()), Some(name));
                }
                continue 'top;
            }
        }
        break 'top;
    }
    /* out: */
    Ok(token)
}

// [spec:dash:def:parser.nlprompt-fn]
// [spec:dash:sem:parser.nlprompt-fn]
fn nlprompt(sh: &mut Shell) {
    crate::plinno!(sh) += 1;
    if sh.input.doprompt != 0 {
        setprompt(sh, 2);
    }
}

// [spec:dash:def:parser.nlnoprompt-fn]
// [spec:dash:sem:parser.nlnoprompt-fn]
fn nlnoprompt(sh: &mut Shell) {
    crate::plinno!(sh) += 1;
    sh.input.needprompt = sh.input.doprompt;
}

/*
 * Read the next input token.
 * If the token is a word, we set backquotelist to the list of cmds in
 *	backquotes.  We set quoteflag to true if any part of the word was
 *	quoted.
 * If the token is TREDIR, then we set redirnode to a structure containing
 *	the redirection.
 */

// [spec:dash:def:parser.xxreadtoken-fn]
// [spec:dash:sem:parser.xxreadtoken-fn]
// [spec:posix:syn:grammar.token-classification]
// [spec:posix:req:token.input-lines]
// [spec:posix:syn:token.recognition-algorithm]
// [spec:posix:syn:token.delimit-at-end-of-input]
// [spec:posix:syn:token.operator-continue]
// [spec:posix:syn:token.operator-delimit]
// [spec:posix:syn:token.start-new-operator]
// [spec:posix:def:grammar.operator-tokens]
// [spec:posix:syn:token.unquoted-blank-delimits]
// [spec:posix:syn:token.comment]
// [spec:posix:syn:token.start-new-word]
fn xxreadtoken(sh: &mut Shell, chkeofmark: c_int) -> Result<Token, Error> {
    let mut c: c_int;

    if sh.input.tokpushback != 0 {
        sh.input.tokpushback = 0;
        return Ok(Token {
            kind: sh.input.lasttoken,
            quoted: sh.input.last_quoteflag,
        });
    }
    if sh.input.needprompt != 0 {
        setprompt(sh, 2);
    }
    loop {
        /* until token or start of word found */
        let tok: Token;

        c = pgetc_eatbnl(sh)?;
        if c == ' ' as c_int || c == '\t' as c_int {
            continue;
        } else if c == '#' as c_int {
            loop {
                c = pgetc(sh)?;
                if c == '\n' as c_int || c == PEOF {
                    break;
                }
            }
            pungetc(sh);
            continue;
        } else if c == '\n' as c_int {
            nlnoprompt(sh);
            sh.input.lasttoken = TNL;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TNL));
        } else if c == PEOF {
            sh.input.lasttoken = TEOF;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TEOF));
        } else if c == '&' as c_int {
            if pgetc_eatbnl(sh)? == '&' as c_int {
                sh.input.lasttoken = TAND;
                sh.input.last_quoteflag = 0;
                return Ok(Token::plain(TAND));
            }
            pungetc(sh);
            sh.input.lasttoken = TBACKGND;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TBACKGND));
        } else if c == '|' as c_int {
            if pgetc_eatbnl(sh)? == '|' as c_int {
                sh.input.lasttoken = TOR;
                sh.input.last_quoteflag = 0;
                return Ok(Token::plain(TOR));
            }
            pungetc(sh);
            sh.input.lasttoken = TPIPE;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TPIPE));
        } else if c == ';' as c_int {
            let next = pgetc_eatbnl(sh)?;
            if next == ';' as c_int {
                sh.input.lasttoken = TENDCASE;
                sh.input.last_quoteflag = 0;
                return Ok(Token::plain(TENDCASE));
            } else if next == '&' as c_int {
                sh.input.lasttoken = TFALLTHRU;
                sh.input.last_quoteflag = 0;
                return Ok(Token::plain(TFALLTHRU));
            }
            pungetc(sh);
            sh.input.lasttoken = TSEMI;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TSEMI));
        } else if c == '(' as c_int {
            sh.input.lasttoken = TLP;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TLP));
        } else if c == ')' as c_int {
            sh.input.lasttoken = TRP;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TRP));
        }
        tok = readtoken1(sh, c, BASESYNTAX(), EofMark::None, 0, chkeofmark)?;
        if tok.kind != TBLANK {
            return Ok(tok);
        }
    }
}

// [spec:dash:def:parser.pgetc-eatbnl-fn]
// [spec:dash:sem:parser.pgetc-eatbnl-fn]
// [spec:posix:req:quote.backslash-newline]
fn pgetc_eatbnl(sh: &mut Shell) -> Result<c_int, Error> {
    let mut c: c_int;

    loop {
        c = pgetc(sh)?;
        if c != '\\' as c_int {
            break;
        }
        if pgetc(sh)? != '\n' as c_int {
            pungetc(sh);
            break;
        }

        nlprompt(sh);
    }

    Ok(c)
}

// [spec:dash:def:parser.pgetc-top-fn]
// [spec:dash:sem:parser.pgetc-top-fn]
fn pgetc_top(sh: &mut Shell, stack: &synstack) -> Result<c_int, Error> {
    if stack.syntax == SQSYNTAX() {
        pgetc(sh)
    } else {
        pgetc_eatbnl(sh)
    }
}

mod synstack_ops;

// [spec:dash:def:parser.getmbc-fn]
// [spec:dash:sem:parser.getmbc-fn]
/// The destination is a fixed scratch buffer sized to what this writes.
///
/// The C hands it a cursor into the stack block and it writes the
/// character's bytes *ahead* of that cursor while it is still deciding
/// whether they form one -- then either frames them and reports the
/// length, or reports 0 and leaves the bytes as scribble for the next
/// write to overwrite. That is a legitimate design, and the room it needs
/// is `MBSLOP`, which every caller had to know from a comment.
///
/// Written into scratch, the speculation is contained by construction:
/// the caller appends only the prefix this reports, and the scribble is
/// simply not copied out. Same bytes, same length, and the reservation
/// stops being a memory-safety contract.
pub fn getmbc(
    sh: &mut Shell,
    c: c_int,
    out: &mut [u8; MBSLOP],
    mode: c_int,
) -> Result<c_uint, Error> {
    let mut c = c;
    /* The C's `out` cursor, and its `start`, as the offsets they were. */
    let mut o: usize = 0;
    let mut decoder = sh.locale.decoder();
    let mut ml: c_uint = 0;
    let mut wc: i32 = 0;
    let mut complete = false;
    let mbc: usize;

    if c >= 0 || c <= PEOF {
        return Ok(0);
    }

    mbc = if (mode & 3) < 2 {
        2 + (mode == 1) as usize
    } else {
        0
    };
    out[mbc + ml as usize] = c as u8;
    loop {
        /* `mbrtowc` is asked for exactly one byte, and the slice it is
         * given starts at the byte just written -- so the pointer is
         * bounded by the indexing rather than by the caller's promise. */
        let decoded = decoder.push(out[mbc + ml as usize]);
        ml += 1;
        match decoded {
            nsh_platform::LocaleDecode::Incomplete => {}
            nsh_platform::LocaleDecode::Complete(wide) => {
                wc = wide;
                complete = true;
                break;
            }
            nsh_platform::LocaleDecode::Invalid => break,
        }
        if ml as usize >= MB_LEN_MAX {
            break;
        }
        c = pgetc_eoa(sh)?;
        if c == PEOA || c == PEOF {
            break;
        }
        out[mbc + ml as usize] = c as u8;
    }

    if complete && ml > 1 {
        if mode == 4 && sh.locale.wide_is_blank(wc) {
            return Ok(1);
        }

        /* The last two `memalloc.h` macros this file expanded were here.
         * Over an offset they are one statement each, so they are written
         * out with the C's name beside them and the macros are deleted --
         * the bookkeeping [[delete-memalloc]] left recorded. */
        if (mode & 3) < 2 {
            /* USTPUTC(CTLMBCHAR, out) */
            out[o] = CTLMBCHAR as u8;
            o += 1;
            if mode == 1 {
                /* USTPUTC(CTLESC, out) */
                out[o] = CTLESC as u8;
                o += 1;
            }
            /* USTPUTC(ml, out) */
            out[o] = ml as u8;
            o += 1;
        }
        /* STADJUST(ml, out) — step over the bytes written ahead of the
         * cursor, which are the character itself. */
        o += ml as usize;
        if (mode & 3) < 2 {
            /* USTPUTC(ml, out) */
            out[o] = ml as u8;
            o += 1;
            /* USTPUTC(CTLMBCHAR, out) */
            out[o] = CTLMBCHAR as u8;
            o += 1;
        }

        return Ok(o as c_uint);
    }

    if ml > 1 {
        pungetn(sh, ml as c_int - 1);
    }

    Ok(0)
}

/// The most `getmbc` or `conv_escape` can write past the cursor.
///
/// `readtoken1` spells it `CHECKSTRSPACE(MAX(MB_LEN_MAX, 16) + 7, out)` and
/// then lets both of them write through a bare `char *`. Reserving is what
/// makes those writes land in a `Vec`'s spare capacity rather than past the
/// end of it, so the number has to stay the C's.
pub const MBSLOP: usize = (if MB_LEN_MAX > 16 { MB_LEN_MAX } else { 16 }) + 7;

/// `getmbc` appending to a growable string.
///
/// The C hands it a cursor into the stack block; the byte count it returns is
/// how far that cursor moved, which here is what the caller commits. It can
/// also return 0 or 1 having scribbled on the block past the cursor, and the
/// C leaves that scribble for the next write to overwrite — so does this,
/// because the bytes stay uncommitted.
fn getmbc_at(sh: &mut Shell, out: &mut BString, c: c_int, mode: c_int) -> Result<c_uint, Error> {
    let mut scratch: [u8; MBSLOP] = [0; MBSLOP];
    let ml = getmbc(sh, c, &mut scratch, mode)?;
    /* The append *is* the commit the callers used to make with `set_len`,
     * so it happens here once instead of at each of the three of them. */
    out.extend_from_slice(&scratch[..ml as usize]);
    Ok(ml)
}

// [spec:dash:def:parser.dollarsq-escape-fn]
// [spec:dash:sem:parser.dollarsq-escape-fn]
// [spec:posix:def:quote.dollar-single-quotes-escapes]
// [spec:posix:def:quote.dollar-single-quotes-control-escape]
// [spec:posix:def:quote.dollar-single-quotes-hex-escape]
// [spec:posix:def:quote.dollar-single-quotes-octal-escape]
// [spec:posix:req:quote.dollar-single-quotes-undefined-escape]
// [spec:posix:syn:quote.dollar-single-quotes-escape-termination]
// [spec:posix:req:quote.dollar-single-quotes-processing-time]
// [spec:posix:req:quote.dollar-single-quotes-null-byte]
// [spec:posix:req:quote.dollar-single-quotes-octal-overflow]
// [spec:posix:req:quote.dollar-single-quotes-unencodable]
// [spec:posix:req:quote.dollar-single-quotes-quote-escape-not-terminator]
fn dollarsq_escape(sh: &mut Shell, dest: &mut BString) -> Result<(), Error> {
    /* The C writes into the stack block through a cursor and commits the
     * prefix. `conv_escape` takes a fixed scratch buffer now -- it writes
     * above the length it reports, which is why the buffer has to be
     * `CONV_ESCAPE_SLOP` and not the four bytes the C's `CHECKSTRSPACE`
     * names -- so the write lands there and the committed prefix is
     * appended. Same bytes, same length, and the reservation that used to
     * be a memory-safety contract is gone with the raw cursor. */
    let mut scratch: [u8; crate::escape::CONV_ESCAPE_SLOP] =
        [0; crate::escape::CONV_ESCAPE_SLOP];
    let mut o: usize = 0;
    /* 10 = length of UXXXXXXXX + NUL */
    let mut text = [0u8; 10];
    let mut len: usize;
    let mut at: usize;

    len = 0;
    while len < text.len() - 1 {
        let c = pgetc(sh)?;

        if c <= PEOF {
            break;
        }

        text[len] = c as u8;
        len += 1;

        if c == '\'' as c_int {
            break;
        }
    }
    text[len] = 0;

    at = 0;
    if text[at] != b'c' {
        let ret: c_uint;

        ret = crate::escape::conv_escape(&text[at..], &mut scratch, true);
        at += (ret >> 4) as usize;
        o += (ret & 15) as usize;
    } else {
        at += 1;
        if text[at] != 0 {
            let conv_ch: c_int;
            let c: c_int;

            c = text[at] as c_int;
            at += 1;

            at += (((c ^ text[at] as c_int) | (c ^ '\\' as c_int)) == 0) as usize;

            conv_ch = (c & !((c & 0x40) >> 1) & 0x7f) ^ 0x40;
            /* USTPUTC(conv_ch, out) */
            scratch[o] = conv_ch as u8;
            o += 1;
        }
    }

    pungetn(sh, len.saturating_sub(at) as c_int);
    dest.extend_from_slice(&scratch[..o]);
    Ok(())
}

/*
 * If eofmark is NULL, read a word or a redirection symbol.  If eofmark
 * is not NULL, read a here document.  In the latter case, eofmark is the
 * word which marks the end of the document and striptabs is true if
 * leading tabs should be stripped from the document.  The argument firstc
 * is the first character of the input token or document.
 *
 * Because C does not have internal subroutines, the original simulates
 * them with goto's: CHECKEND, PARSEREDIR, PARSESUB, PARSEBACKQOLD,
 * PARSEBACKQNEW and PARSEARITH run code that appears at the end of
 * readtoken1.  Here they are plain functions taking the shared C locals
 * (`Rt1`) by `&mut`; they are called from exactly the same places and
 * mutate the state in exactly the same order.
 */

/// The locals of `readtoken1` that its internal subroutines share.
struct Rt1<'a> {
    /// Owned parse contexts, base first and current last. Popping retains the
    /// allocation, matching the C's reuse of its most recently popped level.
    synstack: Vec<synstack>,
    chkeofmark: c_int,
    printesc: bool,
    bqlist: Vec<Option<Node>>,
    dollarsq: c_int,
    c: c_int,
    quotef: c_int,
    /// The word being built. The C's `out` is a `char *` cursor into the
    /// stack block and `stackblock()` is the base; here the base is the
    /// buffer and the cursor is its length, so `STADJUST` is `truncate`
    /// or `push`. Nothing writes into this buffer's spare capacity any
    /// more -- the two routines that did, `getmbc` and `dollarsq_escape`,
    /// have their own scratch and hand back bytes to append.
    out: BString,
    eofmark: EofMark<'a>,
    striptabs: c_int,
    /// Backing store for the `alloca`'d pushback strings in `checkend`,
    /// which likewise accumulate for the life of the call.
    strpool: Vec<Vec<u8>>,
}

impl Rt1<'_> {
    #[inline]
    fn syn(&self) -> &synstack {
        self.synstack.last().unwrap()
    }

    #[inline]
    fn syn_mut(&mut self) -> &mut synstack {
        self.synstack.last_mut().unwrap()
    }
}

/// The label targets inside readtoken1's character switch that are
/// reached by `goto` from more than one case.
enum Lbl {
    None,
    Csquote,
    Quotemark,
    Toggledq,
    EndBackq,
}

// [spec:dash:def:parser.readtoken1-fn]
// [spec:dash:sem:parser.readtoken1-fn]
// [spec:posix:req:shell.hashbang-unspecified]
// [spec:posix:sem:shell.tokenization-and-parsing]
// [spec:posix:def:quote.purpose]
// [spec:posix:req:quote.always-special-characters]
// [spec:posix:req:quote.conditionally-special-characters]
// [spec:posix:req:quote.future-special-characters]
// [spec:posix:def:quote.mechanisms]
// [spec:posix:req:quote.backslash-literal]
// [spec:posix:req:quote.single-quotes]
// [spec:posix:req:quote.double-quotes-literal]
// [spec:posix:req:quote.double-quotes-dollar-sign]
// [spec:posix:req:quote.double-quotes-command-substitution]
// [spec:posix:req:quote.double-quotes-substring-parameter-expansion]
// [spec:posix:req:quote.double-quotes-other-parameter-expansion]
// [spec:posix:req:quote.double-quotes-backquote]
// [spec:posix:req:quote.double-quotes-backquote-undefined]
// [spec:posix:req:quote.double-quotes-backslash]
// [spec:posix:req:quote.double-quotes-expansion-result]
// [spec:posix:req:quote.double-quotes-embedded-double-quote]
// [spec:posix:req:quote.dollar-single-quotes]
// [spec:posix:syn:token.quoting-characters]
// [spec:posix:syn:token.expansion-candidates]
// [spec:posix:syn:token.append-to-word]
fn readtoken1(
    sh: &mut Shell,
    firstc: c_int,
    syntax: SyntaxKind,
    eofmark: EofMark<'_>,
    striptabs: c_int,
    chkeofmark: c_int,
) -> Result<Token, Error> {
    let mut st = Rt1 {
        synstack: vec![synstack {
            syntax,
            innerdq: 0,
            varpushed: 0,
            dblquote: (syntax == DQSYNTAX()) as c_int,
            backq: 0,
            varnest: 0,
            parenlevel: 0,
            dqvarnest: 0,
        }],
        chkeofmark,
        printesc: syntax == SQSYNTAX(),
        bqlist: Vec::new(),
        dollarsq: 0,
        c: firstc,
        quotef: 0,
        out: BString::new(Vec::new()),
        eofmark,
        striptabs,
        strpool: Vec::new(),
    };
    let len: usize;

    'loop_: loop {
        /* for each line, until end of word */
        checkend(sh, &mut st)?; /* set c to PEOF if at end of here document */
        /* Until end of line or end of word */
        loop {
            'body: {
                let fieldsplitting: c_int;
                let mut ml: c_uint;

                fieldsplitting = if st.syn().syntax == BASESYNTAX()
                    && (st.syn().varnest | st.syn().backq) == 0
                {
                    4
                } else {
                    0
                };
                /* The C's CHECKSTRSPACE, which permits max(MB_LEN_MAX, 23)
                 * calls to USTPUTC, has no counterpart here: `getmbc`
                 * writes into its own scratch and `getmbc_at` appends
                 * what it reports, so there is no room for this frame to
                 * make on its behalf. */
                ml = getmbc_at(sh, 
                    &mut st.out,
                    st.c,
                    fieldsplitting | (if st.printesc { 2 } else { 0 }),
                )?;
                if ml == 1 {
                    if st.out.is_empty() {
                        return Ok(Token::plain(TBLANK));
                    }
                    st.c = pgetc(sh)?;
                    break 'loop_;
                }
                if ml != 0 {
                    break 'body; /* continue */
                }

                let cls = syn_at(st.syn().syntax, st.c);
                let mut lbl = Lbl::None;

                if cls == CNL as c_int {
                    /* '\n' */
                    if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    }
                    st.out.push(st.c as u8);
                    nlprompt(sh);
                    st.c = pgetc_top(sh, st.syn())?;
                    continue 'loop_; /* continue outer loop */
                } else if cls == CWORD as c_int {
                    st.out.push(st.c as u8);
                } else if cls == CCTL as c_int {
                    if st.c == st.dollarsq {
                        dollarsq_escape(sh, &mut st.out)?;
                    } else {
                        if (st.eofmark.is_none() as c_int | st.syn().dblquote | st.syn().varnest)
                            != 0
                        {
                            st.out.push(CTLESC as u8);
                        }
                        st.out.push(st.c as u8);
                    }
                } else if cls == CBACK as c_int {
                    /* backslash */
                    st.c = pgetc(sh)?;
                    if st.c == PEOF {
                        st.out.push(CTLESC as u8);
                        st.out.push('\\' as u8);
                        pungetc(sh);
                    } else {
                        if (st.syn().dblquote | st.syn().backq) != 0
                            && st.c != '\\' as c_int
                            && st.c != '`' as c_int
                            && st.c != '$' as c_int
                            && (st.c != '"' as c_int
                                || (!st.eofmark.is_none() && st.syn().varnest == 0))
                            && (st.c != '}' as c_int || st.syn().varnest == 0)
                        {
                            st.out.push(CTLESC as u8);
                            st.out.push('\\' as u8);
                        }
                        st.quotef += 1;

                        ml = getmbc_at(sh, &mut st.out, st.c, 1)?;
                        if ml == 0 {
                            st.out.push(CTLESC as u8);
                            st.out.push(st.c as u8);
                        }
                    }
                } else if cls == CSQUOTE as c_int {
                    lbl = Lbl::Csquote;
                } else if cls == CDQUOTE as c_int {
                    st.syn_mut().syntax = DQSYNTAX();
                    st.syn_mut().dblquote = 1;
                    lbl = Lbl::Toggledq;
                } else if cls == CENDQUOTE as c_int {
                    if !st.eofmark.is_none() && st.syn().varnest == 0 {
                        st.out.push(st.c as u8);
                    } else {
                        if st.syn().dqvarnest == 0 {
                            if st.dollarsq != 0 {
                                /* `*out = '\0'; out = p + strlen(p);` — a NUL
                                 * written by a `$'\0'` escape ends the word,
                                 * so the cursor winds back to it. */
                                let end =
                                    st.out.iter().position(|&b| b == 0).unwrap_or(st.out.len());
                                st.out.truncate(end);
                                st.dollarsq = 0;
                            }

                            st.syn_mut().syntax = BASESYNTAX();
                            st.syn_mut().dblquote = 0;
                        }

                        st.quotef += 1;

                        if st.c == '"' as c_int {
                            lbl = Lbl::Toggledq;
                        } else {
                            lbl = Lbl::Quotemark;
                        }
                    }
                } else if cls == CVAR as c_int {
                    /* '$' */
                    if parsesub(sh, &mut st)? {
                        /* parse substitution */
                        lbl = Lbl::Csquote;
                    }
                } else if cls == CENDVAR as c_int {
                    /* '}' */
                    if st.syn().innerdq == 0 && st.syn().varnest > 0 {
                        st.syn_mut().varnest -= 1;
                        if st.syn().varnest == 0 && st.syn().varpushed != 0 {
                            synstack_ops::pop(&mut st.synstack);
                        } else if st.syn().dqvarnest > 0 {
                            st.syn_mut().dqvarnest -= 1;
                        }
                        if st.chkeofmark == 0 {
                            st.c = CTLENDVAR;
                        }
                    }
                    st.out.push(st.c as u8);
                } else if cls == CLP as c_int {
                    /* '(' in arithmetic */
                    st.syn_mut().parenlevel += 1;
                    st.out.push(st.c as u8);
                } else if cls == CRP as c_int {
                    /* ')' in arithmetic */
                    if st.syn().parenlevel > 0 {
                        st.syn_mut().parenlevel -= 1;
                    } else if pgetc_eatbnl(sh)? == ')' as c_int {
                        synstack_ops::pop(&mut st.synstack);
                        if st.chkeofmark != 0 {
                            st.out.push(st.c as u8);
                        } else {
                            st.c = CTLENDARI;
                        }
                    } else {
                        /*
                         * unbalanced parens
                         *  (don't 2nd guess - no error)
                         */
                        pungetc(sh);
                    }
                    st.out.push(st.c as u8);
                } else if cls == CBQUOTE as c_int {
                    /* '`' */
                    if st.syn().backq == 2 {
                        lbl = Lbl::EndBackq;
                    } else {
                        st.out.push('`' as u8);
                        parsebackq(sh, &mut st, 1)?;
                    }
                } else if cls == CEOF as c_int {
                    break 'loop_; /* exit outer loop */
                } else {
                    /* default: */
                    if st.c == ')' as c_int && st.syn().backq == 1 {
                        lbl = Lbl::EndBackq;
                    } else if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    } else {
                        st.out.push(st.c as u8);
                    }
                }

                /* the goto-linked tails of the switch above */
                loop {
                    match lbl {
                        Lbl::None => break,
                        Lbl::Csquote => {
                            /* csquote: */
                            st.syn_mut().syntax = SQSYNTAX();
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::Quotemark => {
                            /* quotemark: */
                            if st.eofmark.is_none() {
                                st.out.push(CTLQUOTEMARK as u8);
                            }
                            lbl = Lbl::None;
                        }
                        Lbl::Toggledq => {
                            /* toggledq: */
                            if st.syn().varnest != 0 {
                                st.syn_mut().innerdq ^= 1;
                            }
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::EndBackq => {
                            /* end_backq: */
                            synstack_ops::pop(&mut st.synstack);
                            st.printesc = false;
                            st.out.push(st.c as u8);
                            lbl = Lbl::None;
                        }
                    }
                }
            }
            st.c = pgetc_top(sh, st.syn())?;
        }
    }
    /* endword: */
    if st.syn().syntax == ARISYNTAX() {
        return Err(synerror(sh, b"Missing '))'"));
    }
    if (st.syn().syntax != BASESYNTAX() && st.eofmark.is_none()) || st.syn().backq != 0 {
        return Err(synerror(sh, b"Unterminated quoted string"));
    }
    if st.syn().varnest != 0 {
        /* { */
        return Err(synerror(sh, b"Missing '}'"));
    }
    st.out.push(b'\0');
    len = st.out.len();
    if st.eofmark.is_none() {
        if (st.c == '>' as c_int || st.c == '<' as c_int)
            && st.quotef == 0
            && len <= 2
            && (st.out[0] == 0 || is_digit(st.out[0] as i8 as c_int))
        {
            parseredir(sh, &mut st)?;
            sh.input.lasttoken = TREDIR;
            sh.input.last_quoteflag = 0;
            return Ok(Token::plain(TREDIR));
        } else {
            pungetc(sh);
        }
    }
    sh.input.last_quoteflag = st.quotef;
    sh.input.backquotelist = mem::take(&mut st.bqlist);
    /* `grabstackblock(len)` reserved the bytes the C had been writing into
     * scratch space, which is what made `wordtext` outlive the next token.
     * Moving the buffer out is the same guarantee. */
    sh.input.wordtext = mem::take(&mut st.out);
    sh.input.lasttoken = TWORD;
    Ok(Token {
        kind: TWORD,
        quoted: st.quotef,
    })
}
/* end of readtoken routine */

/*
 * Check to see whether we are at the end of the here document.  When this
 * is called, c is set to the first character of the next input line.  If
 * we are at the end of the here document, this routine sets the c to PEOF.
 */

/* checkend: */
// [spec:posix:req:redir.here-doc-delimiter]
// [spec:posix:req:redir.here-doc-tab-strip]
fn checkend(sh: &mut Shell, st: &mut Rt1<'_>) -> Result<(), Error> {
    if let Some(mark) = st.eofmark.real() {
        let markloc: usize;
        let mut i: usize;
        let mut more_heredoc = false;

        if st.striptabs != 0 {
            while st.c == '\t' as c_int {
                st.c = pgetc(sh)?;
            }
        }

        /* The C reads the candidate delimiter into the word being built and
         * then winds the cursor back to `markloc`, so the scratch is the tail
         * of the same buffer. */
        markloc = st.out.len();
        i = 0;
        loop {
            st.out.push(st.c as u8);
            if i == mark.len() {
                /* `*p == '\0'` — the delimiter's terminator */
                break;
            }
            if st.c != mark[i] as i8 as c_int {
                more_heredoc = true; /* goto more_heredoc */
                break;
            }

            st.c = pgetc(sh)?;
            i += 1;
        }

        if !more_heredoc {
            if st.c == '\n' as c_int || st.c == PEOF {
                st.c = PEOF;
                nlnoprompt(sh);
            } else {
                more_heredoc = true;
            }
        }

        if more_heredoc {
            let mut len: usize;

            /* more_heredoc: */
            let start = markloc + 1;
            len = st.out.len() - start;

            if len != 0 {
                len -= (st.c <= PEOF) as usize;
                st.c = st.out[start - 1] as i8 as c_int;

                if len != 0 {
                    pushstring(sh, BStr::new(&st.out[start..start + len]), None);
                }
            }
        }

        st.out.truncate(markloc);
    }
    /* goto checkend_return; */
    Ok(())
}

/*
 * Parse a redirection operator.  The variable "out" points to a string
 * specifying the fd to be redirected.  The variable "c" contains the
 * first character of the redirection operator.
 */

/* parseredir: */
// [spec:posix:syn:redir.format]
// [spec:posix:syn:redir.quoting-suppresses-recognition]
// [spec:posix:req:redir.location-format]
// [spec:posix:req:redir.max-fd-number]
// [spec:posix:syn:redir.output-format]
// [spec:posix:syn:redir.append-format]
// [spec:posix:def:redir.here-doc]
// [spec:posix:syn:redir.here-doc-format]
// [spec:posix:syn:grammar.io-redirect]
// [spec:posix:syn:grammar.io-file]
// [spec:posix:syn:grammar.io-here]
// [spec:posix:def:grammar.operator-tokens]
fn parseredir(sh: &mut Shell, st: &mut Rt1<'_>) -> Result<(), Error> {
    let fdc: c_char = st.out[0] as c_char;
    /* The C carves one `struct nfile` and then decides what it is by
     * assigning `np->type`, re-allocating only because `nhere` is smaller.
     * The arm has to be chosen up front here, so the type and the fd are
     * worked out first and the node built at the end. */
    let mut fd: c_int;
    let ty: c_int;
    let mut doc: Option<heredoc_body> = None;

    if st.c == '>' as c_int {
        fd = 1;
        st.c = pgetc_eatbnl(sh)?;
        if st.c == '>' as c_int {
            ty = NAPPEND;
        } else if st.c == '|' as c_int {
            ty = NCLOBBER;
        } else if st.c == '&' as c_int {
            ty = NTOFD;
        } else {
            ty = NTO;
            pungetc(sh);
        }
    } else {
        /* c == '<' */
        fd = 0;
        st.c = pgetc_eatbnl(sh)?;
        if st.c == '<' as c_int {
            ty = NHERE;
            let slot = heredoc_body::new();
            let mut here = heredoc {
                doc: slot.clone(),
                expand: false,
                eofmark: BString::new(Vec::new()),
                striptabs: 0,
            };
            doc = Some(slot);
            st.c = pgetc_eatbnl(sh)?;
            if st.c == '-' as c_int {
                here.striptabs = 1;
            } else {
                here.striptabs = 0;
                pungetc(sh);
            }
            sh.input.heredoc = Some(here);
        } else if st.c == '&' as c_int {
            ty = NFROMFD;
        } else if st.c == '>' as c_int {
            ty = NFROMTO;
        } else {
            ty = NFROM;
            pungetc(sh);
        }
    }
    if fdc != '\0' as c_char {
        fd = digit_val(fdc as c_int);
    }
    sh.input.redirnode = Some(match ty {
        NTOFD | NFROMFD => Node::Dup(ndup {
            r#type: ty,
            fd,
            dupfd: Cell::new(0),
            vname: RefCell::new(None),
        }),
        NHERE => Node::Here(nhere {
            r#type: NHERE,
            fd,
            doc: doc.unwrap(),
        }),
        _ => Node::File(nfile {
            r#type: ty,
            fd,
            fname: None,
            expfname: RefCell::new(None),
        }),
    });
    /* goto parseredir_return; */
    Ok(())
}

/*
 * Parse a substitution.  At this point, we have read the dollar sign
 * and nothing else.
 *
 * Returns true where the C does `goto csquote`, i.e. jumps back into the
 * CSQUOTE arm of readtoken1's switch instead of returning normally.
 */

/* parsesub: */
fn parsesub(sh: &mut Shell, st: &mut Rt1<'_>) -> Result<bool, Error> {
    let mut newsyn = st.syn().syntax;
    static types: [u8; 6] = *b"}-+?=\0";
    let mut subtype: c_int;

    st.out.push('$' as u8);

    st.c = pgetc_eatbnl(sh)?;
    if st.c == '(' as c_int {
        /* $(command) or $((arith)) */
        st.out.push(st.c as u8);
        if pgetc_eatbnl(sh)? == '(' as c_int {
            parsearith(sh, st)?;
        } else {
            pungetc(sh);
            parsebackq(sh, st, 0)?;
        }
    } else if st.c == '\'' as c_int && syn_at(newsyn, '&' as c_int) != 0 {
        st.out.pop();
        st.dollarsq = '\\' as c_int;
        return Ok(true); /* goto csquote */
    } else if st.c == '{' as c_int || is_name(&sh.locale, st.c) || is_special(st.c) != 0 {
        let typeloc: usize = st.out.len();
        let mut badsub = false;

        /* `STADJUST(chkeofmark == 0, out)` steps over the byte the CTLVAR
         * subtype lands in below; nothing reads it in between, so the
         * placeholder value is not observable. */
        st.out.resize(typeloc + (st.chkeofmark == 0) as usize, 0);
        subtype = VSNORMAL;
        if st.c == '{' as c_int {
            if st.chkeofmark != 0 {
                st.out.push('{' as u8);
            }
            st.c = pgetc_eatbnl(sh)?;
            subtype = 0;
        }
        'varname: loop {
            if is_name(&sh.locale, st.c) {
                loop {
                    st.out.push(st.c as u8);
                    st.c = pgetc_eatbnl(sh)?;
                    if !is_in_name(&sh.locale, st.c) {
                        break;
                    }
                }
            } else if is_digit(st.c) {
                loop {
                    st.out.push(st.c as u8);
                    st.c = pgetc_eatbnl(sh)?;
                    if !((subtype <= 0 || subtype >= VSLENGTH) && is_digit(st.c)) {
                        break;
                    }
                }
            } else if st.c != '}' as c_int {
                let mut cc = st.c;

                st.c = pgetc_eatbnl(sh)?;

                if subtype == 0 && cc == '#' as c_int {
                    subtype = VSLENGTH;

                    if st.c == '_' as c_int || sh.locale.is_alphanumeric(st.c as u8) {
                        if st.chkeofmark != 0 {
                            st.out.push('#' as u8);
                        }
                        continue 'varname; /* goto varname */
                    }

                    cc = st.c;
                    st.c = pgetc_eatbnl(sh)?;
                    if cc == '}' as c_int || st.c != '}' as c_int {
                        pungetc(sh);
                        subtype = 0;
                        st.c = cc;
                        cc = '#' as c_int;
                    } else if st.chkeofmark != 0 {
                        st.out.push('#' as u8);
                    }
                }

                if is_special(cc) == 0 {
                    if subtype == VSLENGTH {
                        subtype = 0;
                    }
                    badsub = true; /* goto badsub */
                    break 'varname;
                }

                st.out.push(cc as u8);
            } else {
                badsub = true; /* goto badsub */
                break 'varname;
            }
            break 'varname;
        }

        if badsub {
            /* badsub: */
            pungetc(sh);
        } else if subtype == 0 {
            let cc = st.c;

            if st.chkeofmark != 0 {
                st.out.push(st.c as u8);
            }

            if st.c == '%' as c_int || st.c == '#' as c_int {
                subtype = if st.c == '#' as c_int {
                    VSTRIMLEFT
                } else {
                    VSTRIMRIGHT
                };
                st.c = pgetc_eatbnl(sh)?;
                if st.c == cc {
                    if st.chkeofmark != 0 {
                        st.out.push(st.c as u8);
                    }
                    subtype += 1;
                } else {
                    pungetc(sh);
                }

                newsyn = BASESYNTAX();
            } else {
                if st.c == ':' as c_int {
                    subtype = VSNUL;
                    st.c = pgetc_eatbnl(sh)?;
                    if st.chkeofmark != 0 {
                        st.out.push(st.c as u8);
                    }
                    /*FALLTHROUGH*/
                }
                /* default: */
                /* The search runs over the whole array, terminator
                 * included, because that is what `strchr` does: a NUL
                 * `c` lands on index 5 rather than missing. */
                if let Some(at) = types.iter().position(|&b| b as c_int == st.c) {
                    subtype |= at as c_int + VSNORMAL;
                }
            }
        } else {
            if subtype == VSLENGTH && st.c != '}' as c_int {
                subtype = 0;
            }
            /* badsub: */
            pungetc(sh);
        }

        if newsyn == ARISYNTAX() {
            newsyn = DQSYNTAX();
        }

        if (newsyn != st.syn().syntax || st.syn().innerdq != 0) && subtype != VSNORMAL {
            synstack_ops::push(&mut st.synstack, newsyn);

            st.syn_mut().varpushed += 1;
            st.syn_mut().dblquote = (newsyn != BASESYNTAX()) as c_int;
        }

        if subtype != VSNORMAL {
            st.syn_mut().varnest += 1;
            if st.syn().dblquote != 0 {
                st.syn_mut().dqvarnest += 1;
            }
        }
        if st.chkeofmark == 0 {
            st.out[typeloc - 1] = CTLVAR as u8;
            st.out[typeloc] = (subtype | VSBIT) as u8;
            st.out.push(b'=');
        }
    } else {
        pungetc(sh);
    }

    /* goto parsesub_return; */
    Ok(false)
}

/*
 * Called to parse command substitutions.  oldstyle is set if the command
 * is enclosed inside `...` rather than $(...).
 */

/* parsebackq: */
// [spec:posix:def:expand.cmdsub-forms]
// [spec:posix:req:expand.cmdsub-backquote-backslash]
// [spec:posix:req:expand.cmdsub-backquote-matching]
// [spec:posix:syn:expand.cmdsub-dollar-paren-extent]
// [spec:posix:req:expand.cmdsub-parsing]
// [spec:posix:req:expand.cmdsub-redirections-only]
// [spec:posix:req:expand.cmdsub-alias-substitution]
// [spec:posix:req:expand.cmdsub-terminating-paren]
// [spec:posix:req:expand.cmdsub-nesting]
// [spec:posix:req:expand.cmdsub-arith-ambiguity]
fn parsebackq(sh: &mut Shell, st: &mut Rt1<'_>, oldstyle: c_int) -> Result<(), Error> {
    let mut saveprompt: c_int = 0;
    let saveheredoclist: Vec<heredoc>;
    let nlpp: usize;
    let n: Option<Node>;
    let mut ml: c_uint;
    /* `grabstackstr(pout)` had to reserve the backquote's text because
     * `list(2)?` builds on the same stack; owning it says the same thing, and
     * it has to outlive the `popfile` below because `setinputstring` reads
     * through the pointer rather than copying. */
    let mut pstr: BString = BString::new(Vec::new());
    let str: BString;

    if st.chkeofmark != 0 {
        synstack_ops::push(&mut st.synstack, BASESYNTAX());
        st.syn_mut().backq = oldstyle + 1;
        st.printesc = true;
        /* goto parsebackq_out; */
        if oldstyle != 0 {
            sh.input.tokpushback = 0;
        }
        return Ok(());
    }
    /* `STADJUST(oldstyle - 1, out)` drops the '(' of `$(` and leaves the '`'
     * of a backquote in place; either way the last byte becomes CTLBACKQ. */
    if oldstyle == 0 {
        st.out.pop();
    }
    let last = st.out.len() - 1;
    st.out[last] = CTLBACKQ as u8;
    /* The word so far is parked while `list(2)?` runs, which is what
     * `grabstackblock(savelen)` bought the C. */
    str = mem::take(&mut st.out);
    if oldstyle != 0 {
        /* We must read until the closing backquote, giving special
        treatment to some slashes, and then push the string and
        reread it as input, interpreting it normally.  */
        let mut done = false;
        let mut pc: c_int;

        while !done {
            'bqbody: {
                if sh.input.needprompt != 0 {
                    setprompt(sh, 2);
                }
                pc = pgetc_eatbnl(sh)?;
                if pc == '`' as c_int {
                    done = true;
                } else if pc == '\\' as c_int {
                    pc = pgetc(sh)?;
                    if pc != '\\' as c_int
                        && pc != '`' as c_int
                        && pc != '$' as c_int
                        && (st.syn().dblquote == 0 || pc != '"' as c_int)
                    {
                        pstr.push(b'\\');
                    }
                    ml = getmbc_at(sh, &mut pstr, pc, 2)?;
                    if ml != 0 {
                        break 'bqbody; /* continue */
                    }
                } else if pc == PEOF {
                    return Err(synerror(sh, b"EOF in backquote substitution"));
                } else if pc == '\n' as c_int {
                    nlnoprompt(sh);
                }
                pstr.push(pc as u8);
            }
        }
        /* `pout[-1] = '\0'` — over the closing backquote the loop just
         * wrote, which is why the buffer is never empty here. */
        let last = pstr.len() - 1;
        pstr[last] = 0;
        setinputstring(sh, crate::mystring::cstr_prefix(&pstr));
    }
    /* The C walks to the tail of `bqlist` and appends an empty cell, then
     * fills its `n` after the recursive parse.  Reserving the slot first is
     * the same order; nothing else can append to this list while `list(2)?`
     * runs, because `bqlist` is a local of *this* `readtoken1`. */
    nlpp = st.bqlist.len();
    st.bqlist.push(None);

    saveheredoclist = core::mem::take(&mut sh.input.heredoclist);

    if oldstyle != 0 {
        saveprompt = sh.input.doprompt;
        sh.input.doprompt = 0;
    }

    n = list(sh, 2)?.into_node();

    if oldstyle != 0 {
        sh.input.doprompt = saveprompt;
    } else {
        if readtoken(sh, 0)? != TRP {
            return Err(synexpect(sh, TRP));
        }
        setinputstring(sh, BStr::new(b""));
    }

    parseheredoc(sh)?;
    sh.input.heredoclist = saveheredoclist;

    st.bqlist[nlpp] = n;
    /* Start reading from old file again. */
    popfile(sh);

    st.out = str;

    /* parsebackq_out: */
    if oldstyle != 0 {
        /* Ignore any pushed back tokens left from the backquote
         * parsing.
         */
        sh.input.tokpushback = 0;
    }
    Ok(())
}

/*
 * Parse an arithmetic expansion (indicate start of one and set state)
 */
/* parsearith: */
// [spec:posix:syn:expand.arith-format]
fn parsearith(sh: &mut Shell, st: &mut Rt1<'_>) -> Result<(), Error> {
    synstack_ops::push(&mut st.synstack, ARISYNTAX());
    st.syn_mut().dblquote = 1;
    if st.chkeofmark != 0 {
        st.out.push(st.c as u8);
    } else {
        /* `STADJUST(-1); out[-1] = CTLARI` — drop the second '(' of `$((`
         * and relabel the '$'. */
        st.out.pop();
        let last = st.out.len() - 1;
        st.out[last] = CTLARI as u8;
    }
    /* goto parsearith_return; */
    Ok(())
}

/*
 * Return of a legal variable name (a letter or underscore followed by zero or
 * more letters, underscores, and digits).
 */

// [spec:dash:def:parser.endofname-fn]
// [spec:dash:sem:parser.endofname-fn]
pub fn endofname(locale: &nsh_platform::Locale, name: &BStr) -> usize {
    let name = crate::mystring::cstr_prefix(name);
    let Some(&first) = name.first() else {
        return 0;
    };
    if !is_name(locale, first as c_char as c_int) {
        return 0;
    }
    1 + name[1..]
        .iter()
        .position(|&byte| !is_in_name(locale, byte as c_char as c_int))
        .unwrap_or(name.len() - 1)
}

/*
 * Called when an unexpected token is read during the parse.  The argument
 * is the token that is expected, or -1 if more than one type of token can
 * occur at this point.
 */

// [spec:dash:def:parser.synexpect-fn]
// [spec:dash:sem:parser.synexpect-fn]
fn synexpect(sh: &mut Shell, token: c_int) -> Error {
    let mut message = Vec::new();

    message.extend_from_slice(tokname[sh.input.lasttoken as usize].to_bytes());
    message.extend_from_slice(b" unexpected");
    if token >= 0 {
        message.extend_from_slice(b" (expecting ");
        message.extend_from_slice(tokname[token as usize].to_bytes());
        message.push(b')');
    }
    message.truncate(63);
    synerror(sh, &message)
}

// [spec:dash:def:parser.synerror-fn]
// [spec:dash:sem:parser.synerror-fn]
fn synerror(sh: &mut Shell, msg: &[u8]) -> Error {
    sh.eval.errlinno = crate::plinno!(sh);
    let mut message = b"Syntax error: ".to_vec();
    message.extend_from_slice(msg);
    sh.sh_error_value(&message)
}

// [spec:dash:def:parser.setprompt-fn]
// [spec:dash:sem:parser.setprompt-fn]
#[inline(never)]
fn setprompt(sh: &mut Shell, which: c_int) {
    let show: c_int;

    sh.input.needprompt = 0;
    sh.input.whichprompt = which;

    /* #ifdef SMALL: show = 1 */
    show = (!crate::histedit::editing_active(sh)) as c_int;
    if show != 0 && crate::input::cur_pf(sh).nleft == 0 {
        /* `pushstackmark(&smark, stackblocksize())` bounded the prompt
         * `expandstr` had left in the region for `out2str` to read.  The
         * expansion buffer is owned, so there is nothing to bound. */
        let prompt = getprompt(sh);
        let _ = sh.io.stderr().write_all(&prompt);
    }
}

// [spec:dash:def:parser.expandstr-fn]
// [spec:dash:sem:parser.expandstr-fn]
pub fn expandstr(sh: &mut Shell, ps: &BStr) -> Result<BString, Error> {
    let file_stop: usize;
    let saveheredoclist: Vec<heredoc>;
    let mut result: BString;
    let saveprompt: c_int;

    file_stop = crate::input::cur_mark(sh);

    /* XXX Fix (char *) cast. */
    let ps = crate::mystring::cstr_prefix(ps);
    setinputstring(sh, ps);

    saveheredoclist = core::mem::take(&mut sh.input.heredoclist);
    saveprompt = sh.input.doprompt;
    sh.input.doprompt = 0;
    sh.input.needprompt = 0;
    /* `result = ps` — the C seeds the answer with the string it was given
     * and the failure path is what leaves the seed standing.
     *
     * The seed is a *copy* rather than the pointer, and that is a fix
     * rather than a transcription. `ps` points into a shell variable's
     * text, and the expansion about to run can reassign that variable —
     * `PS1='$(PS1=x; echo)'` reaches it — which reallocates the text and
     * leaves `ps` dangling for exactly the failure path that reads it.
     * The C read it anyway. Copying at the point the C takes the seed
     * keeps the C's sequence and removes the read-after-free. */
    result = BString::from(ps);
    /* `if (unlikely(err = setjmp(jmploc.loc))) goto out;` — handlers in
     * this port are established by `eval::setjmp_catch`, not a real
     * `setjmp`, so the body goes in the closure and everything after the
     * call is the `out:` label. The C's `union node n` is a bare local it
     * never reads after the call, so it lives inside the closure here.
     *
     * The raw out-pointer this used to need is gone with the pointer it
     * carried: an immediately-invoked closure can capture the local
     * mutably, and `result`'s bytes are its own. */
    /* The C's `if (unlikely(err = setjmp(jmploc.loc))) goto out;` and the
     * whole of the frame it armed are gone. What it was for is here as an
     * ordinary `?` chain, and the `out:` label is what follows the call. */
    let caught = (|| -> Result<(), crate::error::Error> {
        let result = &mut result;
        let firstc = pgetc_eatbnl(sh)?;
        readtoken1(sh, firstc, DQSYNTAX(), EofMark::Fake, 0, 0)?;

        let n = Node::Arg(narg {
            text: wordtext_node(sh),
            backquote: core::mem::take(&mut sh.input.backquotelist),
        });

        expandarg(sh, &n, None, EXP_QUOTED)?;
        /* The C reads the expansion back as `stackblock()`; the expansion
         * buffer is owned now, so the read is named.  The C's pointer was
         * live only until the next `stalloc`; this one is live until the
         * next expansion, which is a superset.
         *
         * Neither `?` above reaches this line, which is the whole of the
         * C's `goto out` skipping it: a prompt that fails to parse or to
         * expand leaves `result` as the `ps` it was seeded with, and the
         * caller renders the prompt unexpanded.
         *
         * The copy is what the C's pointer bought with liveness instead.
         * It costs one allocation per prompt — drawn at the rate a human
         * presses return, or once per traced command — and it buys the
         * caller a value that no later expansion can pull out from under
         * it. `getprompt` handing back a borrow of the expansion buffer
         * would have to outlive the next `expandarg` to be useful, and it
         * cannot. */
        *result = BString::from(crate::expand::expansion_result(sh));
        Ok(())
    })()
    .err();

    /* out: */
    /* A *diagnostic* is dropped, and that is dash: `expandstr` reports it
     * and hands back the string it was given, which is why a bad `PS1` or
     * `PS4` cannot abort a script (`docs/api-design.md` §3.3).
     *
     * An interrupt is not, and cannot be — the C re-raised it from
     * `restore_handler_expandarg` and there is nothing here that may
     * swallow a ^C. It is why this function returns a `Result` at all;
     * both callers are fallible and neither wanted one otherwise. */
    let caught = restore_handler_expandarg(sh, caught);

    sh.input.doprompt = saveprompt;
    unwindfiles(sh, file_stop);
    sh.input.heredoclist = saveheredoclist;

    match caught {
        Some(e) if e.is_interrupt() => Err(e),
        other => {
            /* A bad `PS1`/`PS4` is reported and the unexpanded prompt is
             * used; the status it took is still the shell's, so the catch
             * writes it. */
            if let Some(e) = &other {
                sh.status = e.status();
            }
            drop(other);
            Ok(result)
        }
    }
}

/*
 * called by editline -- any expansions to the prompt
 *    should be added here.
 */

// [spec:dash:def:parser.getprompt-fn]
// [spec:dash:sem:parser.getprompt-fn]
// [spec:posix:req:param.ps1]
// [spec:posix:req:param.ps1-two-pass]
// [spec:posix:req:param.ps2]
pub fn getprompt(sh: &mut Shell) -> BString {
    let prompt = match sh.input.whichprompt {
        1 => {
            let prompt = crate::var::ps1val(sh);
            sh.histedit
                .expand_prompt_exclamation_marks(BStr::new(prompt.as_slice()))
        }
        2 => crate::var::ps2val(sh),
        /* default: falls into case 0 outside DEBUG builds.  The C returns
         * `nullstr`, whose *address* is load-bearing at other sites (see
         * `mystring::nullstr`) but not at this one: both readers here take
         * its bytes and there are none, so the empty value is exact. */
        _ => {
            return BString::default();
        }
    };

    /* A callback: the line editor calls this through a function pointer
     * and there is nothing here to return a `Result` to. A diagnostic is
     * dropped, as everywhere `expandstr` is used; an interrupt is put
     * back for the next poll site, because dropping it would lose the
     * user's ^C. See `error::rearm_interrupt`. */
    /* The receiver arrives by parameter, and that is the whole of the
     * answer `move-state` owed this site. It was the last
     * `Shell::detached()`, and the reason recorded for it -- a
     * `fn(*mut c_void) -> *const c_char` the line editor calls through a
     * function pointer, with nowhere to put a `&mut Shell` -- stopped
     * being true when the editor moved to its native Rust API: nothing
     * calls this through a pointer any more. `linedit::shell_prompt`
     * calls it, and `setprompt` calls it, and both are ordinary Rust
     * frames that can carry a receiver. So this is threading after all,
     * not the handle `docs/api-design.md` §5.1 keeps for the signal
     * handler -- which is still the one shape that cannot take a
     * parameter, because a handler has no frame to thread through. */
    match expandstr(sh, BStr::new(prompt.as_slice())) {
        Ok(expanded) => expanded,
        Err(e) => {
            crate::error::rearm_interrupt(e);
            /* The interrupted prompt is rendered unexpanded, which is the
             * same answer `expandstr`'s own failure path gives — and the
             * same read of `prompt`, taken here because this arm never
             * entered the copy `expandstr` makes. */
            prompt
        }
    }
}

/// The C reaches `parsekwd` through `mystring.c`'s `findstring`, a generic
/// `bsearch` over an array of `char *`. This is that function's only
/// instantiation in the port, and `strcmp` over the table is plain byte
/// order — `parsekwd` is ASCII and sorted — so `<[u8]>::cmp` is the C
/// comparator rather than an approximation of it.
///
/// The result stays a pointer *into* `parsekwd` because `readtoken1`
/// recovers the token code by subtracting the base.
// [spec:dash:def:parser.findkwd-fn]
// [spec:dash:sem:parser.findkwd-fn]
pub fn findkwd(s: &BStr) -> Option<usize> {
    let key = crate::mystring::cstr_prefix(s);
    parsekwd
        .binary_search_by(|kwd| kwd.to_bytes().cmp(key.as_ref()))
        .ok()
}

// ---------------------------------------------------------------------
// src/parser.h inline functions
// ---------------------------------------------------------------------

// [spec:dash:def:parser.goodname-fn]
// [spec:dash:sem:parser.goodname-fn]
pub fn goodname(locale: &nsh_platform::Locale, name: &BStr) -> c_int {
    let name = crate::mystring::cstr_prefix(name);
    (endofname(locale, name) == name.len()) as c_int
}

// [spec:dash:def:parser.parser-eof-fn]
// [spec:dash:sem:parser.parser-eof-fn]
pub fn parser_eof(sh: &Shell) -> c_int {
    (sh.input.tokpushback != 0 && sh.input.lasttoken == TEOF) as c_int
}

#[cfg(test)]
mod bash_mode_tests;

#[cfg(test)]
mod tests {
    use super::*;

    // [spec:dash:sem:parser.findkwd-fn/test]
    #[test]
    fn findkwd_preserves_the_sorted_table_contract() {
        let mut previous: Option<&[u8]> = None;

        for (i, keyword) in parsekwd.iter().enumerate() {
            let bytes = keyword.to_bytes();
            if let Some(previous) = previous {
                assert!(previous < bytes, "parsekwd must be strictly sorted");
            }
            previous = Some(bytes);

            assert_eq!(findkwd(BStr::new(bytes)), Some(i));

            let mut longer = bytes.to_vec();
            longer.push(b'x');
            assert_eq!(findkwd(BStr::new(&longer)), None);
        }

        for missing in [b"".as_slice(), b"cas", b"integer", b"zebra"] {
            assert_eq!(findkwd(BStr::new(missing)), None);
        }

        assert_eq!(findkwd(BStr::new(&[0xff_u8])), None);
    }
}
