//! Literal port of `src/parser.c` / `src/parser.h`.
//! Rules: `docs/spec/port/src/parser.md`.
//!
//! The shell command parser.  This is a 1:1 transcription of the C: the
//! same functions, the same control flow, the same side-effect order and
//! the same bugs.  `readtoken1` in particular keeps the C shape — one
//! function whose "internal subroutines" (`checkend`, `parseredir`,
//! `parsesub`, `parsebackq`, `parsearith`) are reached by `goto` in C and
//! are plain functions taking the shared state by `&mut` here.

use core::cell::{Cell, OnceCell, RefCell};
use core::mem;
use core::ptr;
use core::ptr::addr_of_mut;
use std::ffi::CStr;
use std::io::Write;
use std::rc::Rc;

use bstr::{BStr, BString};
use libc::{c_char, c_int, c_uint, c_void};

use crate::error::{errlinno, handler, jmploc};
use crate::expand::{EXP_QUOTED, expandarg, restore_handler_expandarg, rmescapes};
use crate::input::{
    PEOA, pgetc, pgetc_eoa, popfile, pungetc, pungetn, pushstring, setinputstring, unwindfiles,
    whichprompt,
};
use crate::nodes::{
    NAND, NAPPEND, NBACKGND, NCLOBBER, NCMD, NFROM, NFROMFD, NFROMTO, NHERE, NOR, NPIPE, NREDIR,
    NSEMI, NSUBSHELL, NTO, NTOFD, NUNTIL, NWHILE, NXHERE, Node, NodeText, heredoc_body, narg,
    nbinary, ncase, nclist, ncmd, ndefun, ndup, nfile, nfor, nhere, nif, nnot, npipe, nredir,
};
use crate::syntax::{
    CBACK, CBQUOTE, CCTL, CDQUOTE, CENDQUOTE, CENDVAR, CEOF, CLP, CNL, CRP, CSQUOTE, CVAR, CWORD,
    PEOF, Syntax, digit_val, is_digit, is_in_name, is_name, is_special, syntax_at,
};

// ---------------------------------------------------------------------
// Local transcriptions of the C macros this file uses.
// ---------------------------------------------------------------------

/* `#define equal(s1, s2) (strcmp(s1, s2) == 0)` — src/mystring.h.  The
 * macro had one caller and `strcmp`'s ordering was never wanted there,
 * only its zero; `issimplecmd` now compares the two byte slices, and the
 * word's text already knows its own length. */

/// `#define USTPUTC(c, p) (*p++ = (c))` — src/memalloc.h:88
///
/// The C's other stack-string macros read `stacknxt`/`sstrend`; these two
/// do not touch the allocator, and here the buffer under the cursor is a
/// `BString`'s spare capacity. `getmbc` and `dollarsq_escape` are the only
/// callers left, and both reserve `MBSLOP` before they take the cursor.
macro_rules! USTPUTC {
    ($c:expr, $p:ident) => {{
        *$p = $c as c_char;
        $p = $p.add(1);
    }};
}

/// `#define STADJUST(amount, p) (p += (amount))` — src/memalloc.h:93
macro_rules! STADJUST {
    ($amount:expr, $p:ident) => {
        $p = $p.offset($amount as isize)
    };
}

/// `MB_LEN_MAX` from `<limits.h>` (16 on the platforms dash targets).
const MB_LEN_MAX: usize = 16;

/*
 * The four syntax tables, as the *table pointers* `synstack->syntax`
 * carries around.  `syntax.h` spells them `basesyntax + SYNBASE` etc.;
 * Rust cannot form an interior pointer that is indexed negatively, so the
 * SYNBASE offset stays inside `syntax_at` and what travels is a pointer
 * to the whole table.  Pointer identity is what `readtoken1` compares.
 */

/// `#define BASESYNTAX (basesyntax + SYNBASE)`
fn BASESYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::basesyntax)
}

/// `#define DQSYNTAX (dqsyntax + SYNBASE)`
fn DQSYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::dqsyntax)
}

/// `#define SQSYNTAX (sqsyntax + SYNBASE)`
fn SQSYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::sqsyntax)
}

/// `#define ARISYNTAX (arisyntax + SYNBASE)`
fn ARISYNTAX() -> *const Syntax {
    ptr::addr_of!(crate::syntax::arisyntax)
}

/// `syntax[c]` for a table held in a variable.
unsafe fn syn_at(tab: *const Syntax, c: c_int) -> c_int {
    syntax_at(&*tab, c) as c_int
}

// ---------------------------------------------------------------------
// src/token.h (generated by mktokens): values returned by readtoken.
// ---------------------------------------------------------------------

pub const TEOF: c_int = 0;
pub const TBLANK: c_int = 1;
pub const TNL: c_int = 2;
pub const TSEMI: c_int = 3;
pub const TBACKGND: c_int = 4;
pub const TAND: c_int = 5;
pub const TOR: c_int = 6;
pub const TPIPE: c_int = 7;
pub const TLP: c_int = 8;
pub const TRP: c_int = 9;
pub const TENDCASE: c_int = 10;
pub const TENDBQUOTE: c_int = 11;
pub const TREDIR: c_int = 12;
pub const TWORD: c_int = 13;
pub const TNOT: c_int = 14;
pub const TCASE: c_int = 15;
pub const TDO: c_int = 16;
pub const TDONE: c_int = 17;
pub const TELIF: c_int = 18;
pub const TELSE: c_int = 19;
pub const TESAC: c_int = 20;
pub const TFI: c_int = 21;
pub const TFOR: c_int = 22;
pub const TIF: c_int = 23;
pub const TIN: c_int = 24;
pub const TTHEN: c_int = 25;
pub const TUNTIL: c_int = 26;
pub const TWHILE: c_int = 27;
pub const TBEGIN: c_int = 28;
pub const TEND: c_int = 29;

// ---------------------------------------------------------------------
// src/token_vars.h (generated by mktokens), included by parser.c.
// ---------------------------------------------------------------------

/// Array indicating which tokens mark the end of a list.
static tokendlist: [c_char; 30] = [
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
];

/// A table of `const char *` needs a `Sync` wrapper to live in a plain
/// `static`; the contents are exactly the generated C arrays.
struct CStrTable<const N: usize>([*const c_char; N]);
unsafe impl<const N: usize> Sync for CStrTable<N> {}

static tokname: CStrTable<30> = CStrTable([
    c"end of file".as_ptr(),
    c"blank".as_ptr(),
    c"newline".as_ptr(),
    c"\";\"".as_ptr(),
    c"\"&\"".as_ptr(),
    c"\"&&\"".as_ptr(),
    c"\"||\"".as_ptr(),
    c"\"|\"".as_ptr(),
    c"\"(\"".as_ptr(),
    c"\")\"".as_ptr(),
    c"\";;\"".as_ptr(),
    c"\"`\"".as_ptr(),
    c"redirection".as_ptr(),
    c"word".as_ptr(),
    c"\"!\"".as_ptr(),
    c"\"case\"".as_ptr(),
    c"\"do\"".as_ptr(),
    c"\"done\"".as_ptr(),
    c"\"elif\"".as_ptr(),
    c"\"else\"".as_ptr(),
    c"\"esac\"".as_ptr(),
    c"\"fi\"".as_ptr(),
    c"\"for\"".as_ptr(),
    c"\"if\"".as_ptr(),
    c"\"in\"".as_ptr(),
    c"\"then\"".as_ptr(),
    c"\"until\"".as_ptr(),
    c"\"while\"".as_ptr(),
    c"\"{\"".as_ptr(),
    c"\"}\"".as_ptr(),
]);

pub const KWDOFFSET: c_int = 14;

static parsekwd: CStrTable<16> = CStrTable([
    c"!".as_ptr(),
    c"case".as_ptr(),
    c"do".as_ptr(),
    c"done".as_ptr(),
    c"elif".as_ptr(),
    c"else".as_ptr(),
    c"esac".as_ptr(),
    c"fi".as_ptr(),
    c"for".as_ptr(),
    c"if".as_ptr(),
    c"in".as_ptr(),
    c"then".as_ptr(),
    c"until".as_ptr(),
    c"while".as_ptr(),
    c"{".as_ptr(),
    c"}".as_ptr(),
]);

// ---------------------------------------------------------------------
// src/parser.h
// ---------------------------------------------------------------------

/* control characters in argument strings */
pub const CTL_FIRST: c_int = -127; /* first 'special' character */
pub const CTLESC: c_int = -127; /* escape next character */
pub const CTLVAR: c_int = -126; /* variable defn */
pub const CTLENDVAR: c_int = -125;
pub const CTLBACKQ: c_int = -124;
pub const CTLMBCHAR: c_int = -123;
pub const CTLARI: c_int = -122; /* arithmetic expression */
pub const CTLENDARI: c_int = -121;
pub const CTLQUOTEMARK: c_int = -120;
pub const CTL_LAST: c_int = -120; /* last 'special' character */

/* variable substitution byte (follows CTLVAR) */
pub const VSTYPE: c_int = 0x0f; /* type of variable substitution */
pub const VSNUL: c_int = 0x10; /* colon--treat the empty string as unset */
pub const VSBIT: c_int = 0x20; /* Ensure subtype is not zero */

/* values of VSTYPE field */
pub const VSNORMAL: c_int = 0x1; /* normal variable:  $var or ${var} */
pub const VSMINUS: c_int = 0x2; /* ${var-text} */
pub const VSPLUS: c_int = 0x3; /* ${var+text} */
pub const VSQUESTION: c_int = 0x4; /* ${var?message} */
pub const VSASSIGN: c_int = 0x5; /* ${var=text} */
pub const VSTRIMRIGHT: c_int = 0x6; /* ${var%pattern} */
pub const VSTRIMRIGHTMAX: c_int = 0x7; /* ${var%%pattern} */
pub const VSTRIMLEFT: c_int = 0x8; /* ${var#pattern} */
pub const VSTRIMLEFTMAX: c_int = 0x9; /* ${var##pattern} */
pub const VSLENGTH: c_int = 0xa; /* ${#var} */
/* VSLENGTH must come last. */

/* values of checkkwd variable */
pub const CHKALIAS: c_int = 0x1;
pub const CHKKWD: c_int = 0x2;
pub const CHKNL: c_int = 0x4;
pub const CHKEOFMARK: c_int = 0x8;

/// What the C returns from `list()` and `parsecmd`.
///
/// `union node *` is three things there at once: a tree, `NULL` for a blank
/// line, and the sentinel `#define NEOF ((union node *)&tokpushback)` for end
/// of file. Only `list(1)` — that is, `parsecmd` — can produce `NEOF`,
/// because the `n1 = NEOF` assignment is guarded by `chknl == 0` and `chknl`
/// is only zero when `nlflag & 1`.
pub enum ParseResult {
    /// the C's `NEOF`
    Eof,
    /// a tree, or `None` where the C returned `NULL` for a blank line
    Tree(Option<Node>),
}

impl ParseResult {
    /// The tree, for the callers of `list()` that cannot see `NEOF`.
    fn into_node(self) -> Option<Node> {
        match self {
            ParseResult::Tree(n) => n,
            ParseResult::Eof => None,
        }
    }
}

/// `readtoken1`'s `eofmark` argument.
///
/// The C passes a `char *` that is overloaded three ways: NULL means "read a
/// word", `FAKEEOFMARK` (`(char *)1`) means "read a word but behave as if a
/// here-document were in progress", and anything else is the delimiter of a
/// real here-document. Only the third carries bytes, so only the third owns
/// any.
#[derive(Clone, Copy)]
enum EofMark<'a> {
    /// C: `NULL`
    None,
    /// C: `FAKEEOFMARK` — what `expandstr` passes
    Fake,
    /// C: the here-document's delimiter, after `rmescapes`
    Word(&'a BStr),
}

impl<'a> EofMark<'a> {
    /// `eofmark == NULL`
    fn is_none(self) -> bool {
        matches!(self, EofMark::None)
    }

    /// `#define realeofmark(m) ((m) && (m) != FAKEEOFMARK)` — src/parser.c
    // [spec:dash:def:parser.realeofmark-fn]
    // [spec:dash:sem:parser.realeofmark-fn]
    fn real(self) -> Option<&'a BStr> {
        match self {
            EofMark::Word(w) => Some(w),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------

// [spec:dash:def:parser.heredoc]
/// The C carries `union node *here`, a back pointer to the redirection node,
/// and reads `here->type` in `parseheredoc` to decide whether the body is
/// expanded. Owning the tree makes that pointer impossible, so what travels
/// is the shared body slot (`nodes::heredoc_body`) plus the one bit of the
/// node's type `parseheredoc` actually wanted. `parsefname` settles the type
/// immediately before appending, so the bit is final when it is recorded.
pub struct heredoc {
    /// the slot in the redirection node the body lands in
    pub doc: heredoc_body,
    /// the node is `NXHERE`: read the body with `DQSYNTAX`, not `SQSYNTAX`
    pub expand: bool,
    /// string indicating end of input, with `rmescapes` already applied
    pub eofmark: BString,
    pub striptabs: c_int, /* if set, strip leading tabs */
}

// [spec:dash:def:parser.synstack]
/// One owned parse context. [`Rt1::synstack`] holds the contexts from the
/// base level through the current level, so the C's `next` link is the
/// preceding element and its `prev` link is spare `Vec` capacity left by a
/// pop. No cursor into the vector survives a push or pop.
pub struct synstack {
    pub syntax: *const Syntax,
    pub innerdq: c_int,
    pub varpushed: c_int,
    pub dblquote: c_int,
    pub backq: c_int,      /* Inside back quotes (here-doc word only). */
    pub varnest: c_int,    /* levels of variables expansion */
    pub parenlevel: c_int, /* levels of parens in arithmetic */
    pub dqvarnest: c_int,  /* levels of variables expansion within double quotes */
}

pub static mut heredoclist: Vec<heredoc> = Vec::new(); /* list of here documents to read */
pub static mut doprompt: c_int = 0; /* if set, prompt the user */
pub static mut needprompt: c_int = 0; /* true if interactive and at start of line */
pub static mut lasttoken: c_int = 0; /* last token read */
pub static mut tokpushback: c_int = 0; /* last token pushed back */
/// text of last word, with the terminating NUL `readtoken1` writes
pub static mut wordtext: BString = BString::new(Vec::new());
pub static mut checkkwd: c_int = 0;
pub static mut backquotelist: Vec<Option<Node>> = Vec::new();
pub static mut redirnode: Option<Node> = None;
pub static mut heredoc: Option<heredoc> = None;
pub static mut quoteflag: c_int = 0; /* set if (part of) last token was quoted */

/// Move one of the parser's globals out and leave it empty.
///
/// Four of them hand a value to whoever reads next and are not read again
/// until the next token refills them, which in C is a pointer copy and here
/// has to be a move:
///
///   * `backquotelist` — `n->narg.backquote = backquotelist`, aliased into
///     the node just built; the next `readtoken1` overwrites the global.
///   * `heredoclist` — `save = heredoclist; heredoclist = NULL;`.
///   * `redirnode` — copied into a local at the top of `parsefname`, because
///     the token read inside it can set the global again.
///   * `heredoc` — the pending here-document `parseredir` left behind.
///
/// Raw rather than `mem::take` so that no `&mut` to a `static mut` exists,
/// even momentarily.
unsafe fn takeglobal<T: Default>(p: *mut T) -> T {
    ptr::replace(p, T::default())
}

// [spec:dash:def:parser.isassignment-fn]
// [spec:dash:sem:parser.isassignment-fn]
pub unsafe fn isassignment(p: *const c_char) -> c_int {
    let q = endofname(p);
    if p == q as *const c_char {
        return 0;
    }
    (*q == '=' as c_char) as c_int
}

// [spec:dash:def:parser.issimplecmd-fn]
// [spec:dash:sem:parser.issimplecmd-fn]
pub unsafe fn issimplecmd(n: Option<&Node>, name: *const c_char) -> c_int {
    match n {
        Some(n) if n.node_type() == NCMD => {
            let args = &n.ncmd().args;
            (!args.is_empty()
                && args[0].narg().text.as_bstr() == CStr::from_ptr(name).to_bytes())
                as c_int
        }
        _ => 0,
    }
}

/// The last word read, as the `char *` the C-shaped readers still expect.
unsafe fn wordtext_ptr() -> *mut c_char {
    (*ptr::addr_of!(wordtext)).as_ptr() as *mut c_char
}

/// The last word read, as a node's owned text.
unsafe fn wordtext_node() -> NodeText {
    NodeText::new((*ptr::addr_of!(wordtext)).clone())
}

/*
 * Read and parse a command.  Returns NEOF on end of file.  (NULL is a
 * valid parse tree indicating a blank line.)
 */

// [spec:dash:def:parser.parsecmd-fn]
// [spec:dash:sem:parser.parsecmd-fn]
pub unsafe fn parsecmd(interact: c_int) -> ParseResult {
    tokpushback = 0;
    checkkwd = 0;
    heredoclist = Vec::new();
    doprompt = interact;
    if doprompt != 0 {
        setprompt(doprompt);
    }
    needprompt = 0;
    list(1)
}

// [spec:dash:def:parser.list-fn]
// [spec:dash:sem:parser.list-fn]
unsafe fn list(nlflag: c_int) -> ParseResult {
    let mut nlflag = nlflag;
    let chknl = if nlflag & 1 != 0 { 0 } else { CHKNL };
    let mut n1: Option<Node>;
    let mut n2: Option<Node>;
    let mut tok: c_int;

    n1 = None;
    loop {
        checkkwd = chknl | CHKKWD | CHKALIAS;
        tok = readtoken();
        match tok {
            TNL => {
                parseheredoc();
                return ParseResult::Tree(n1);
            }

            TEOF => {
                let eof = n1.is_none() && chknl == 0;
                /* out_eof: */
                parseheredoc();
                tokpushback += 1;
                lasttoken = TEOF;
                return if eof {
                    ParseResult::Eof
                } else {
                    ParseResult::Tree(n1)
                };
            }
            _ => {}
        }

        tokpushback += 1;
        if nlflag == 2 && tokendlist[tok as usize] != 0 {
            return ParseResult::Tree(n1);
        }
        nlflag |= 2;

        /* The line the backgrounded command starts on, captured before
         * anything consumes it. `command()` and `pipeline()` both take
         * their `savelinno` at this same point, so a wrapper built here
         * records the line its contents record. */
        let savelinno: c_int = crate::plinno!();

        n2 = andor();
        tok = readtoken();
        if tok == TBACKGND {
            /* The C dereferences n2 unconditionally here. */
            if n2.as_ref().unwrap().node_type() == NPIPE {
                n2.as_mut().unwrap().npipe_mut().backgnd = 1;
            } else {
                if n2.as_ref().unwrap().node_type() != NREDIR {
                    /* dash never writes `linno` on this wrapper, so
                     * `evalsubshell` copies whatever `stalloc` returned
                     * into `lineno` and `errlinno` -- both observable, via
                     * `$LINENO` and the `sh: N:` diagnostic prefix. It is
                     * reached only on a fork failure, which is why nothing
                     * has noticed.
                     *
                     * There is no bug-for-bug option here: reading
                     * uninitialised memory is not something a safe
                     * language reproduces, so the only question is which
                     * correct value to write. See
                     * [dec:nsh:we-own-the-defects] and
                     * `docs/divergences.md`. */
                    n2 = Some(Node::Redir(nredir {
                        r#type: 0,
                        linno: savelinno,
                        n: n2.map(Box::new),
                        redirect: Vec::new(),
                    }));
                }
                n2.as_mut().unwrap().nredir_mut().r#type = NBACKGND;
            }
        }
        if n1.is_none() {
            n1 = n2;
        } else {
            n1 = Some(Node::Binary(nbinary {
                r#type: NSEMI,
                ch1: n1.map(Box::new),
                ch2: n2.map(Box::new),
            }));
        }
        match tok {
            TEOF => {
                /* goto out_eof */
                parseheredoc();
                tokpushback += 1;
                lasttoken = TEOF;
                return ParseResult::Tree(n1);
            }
            TNL => {
                tokpushback += 1;
                /* fall through */
            }
            TBACKGND | TSEMI => {}
            _ => {
                if chknl == 0 {
                    synexpect(-1);
                }
                tokpushback += 1;
                return ParseResult::Tree(n1);
            }
        }
    }
}

// [spec:dash:def:parser.andor-fn]
// [spec:dash:sem:parser.andor-fn]
unsafe fn andor() -> Option<Node> {
    let mut n1: Option<Node>;
    let mut t: c_int;

    n1 = pipeline();
    loop {
        t = readtoken();
        if t == TAND {
            t = NAND;
        } else if t == TOR {
            t = NOR;
        } else {
            tokpushback += 1;
            return n1;
        }
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        let n2 = pipeline();
        n1 = Some(Node::Binary(nbinary {
            r#type: t,
            ch1: n1.map(Box::new),
            ch2: n2.map(Box::new),
        }));
    }
}

// [spec:dash:def:parser.pipeline-fn]
// [spec:dash:sem:parser.pipeline-fn]
unsafe fn pipeline() -> Option<Node> {
    let mut n1: Option<Node>;
    let mut negate: c_int;

    negate = 0;
    /* TRACE(("pipeline: entered\n")); */
    if readtoken() == TNOT {
        negate = (negate == 0) as c_int;
        checkkwd = CHKKWD | CHKALIAS;
    } else {
        tokpushback += 1;
    }
    n1 = command();
    if readtoken() == TPIPE {
        /* Every `stalloc(sizeof(struct nodelist))` the C does here is one
         * `Vec` slot; the list is built front to back either way, and
         * `command()` cannot return NULL without having raised first. */
        let mut cmdlist: Vec<Node> = vec![n1.take().unwrap()];
        loop {
            checkkwd = CHKNL | CHKKWD | CHKALIAS;
            cmdlist.push(command().unwrap());
            if readtoken() != TPIPE {
                break;
            }
        }
        n1 = Some(Node::Pipe(npipe {
            backgnd: 0,
            cmdlist,
        }));
    }
    tokpushback += 1;
    if negate != 0 {
        Some(Node::Not(nnot {
            com: n1.map(Box::new),
        }))
    } else {
        n1
    }
}

// [spec:dash:def:parser.command-fn]
// [spec:dash:sem:parser.command-fn]
unsafe fn command() -> Option<Node> {
    let mut n1: Option<Node>;
    let mut t: c_int;
    let savelinno: c_int;

    savelinno = crate::plinno!();

    let mut goto_redir = false;
    let tok = readtoken();
    if tok == TIF {
        /* The C threads the elif chain through `elsepart` on the way down,
         * writing each new nif into its parent before parsing it.  An owned
         * tree cannot hand out that parent pointer, so the clauses are
         * collected in parse order and folded back up afterwards; the
         * sequence of `list(0)` calls — and so of everything they read — is
         * unchanged. */
        let mut clauses: Vec<(Option<Node>, Option<Node>)> = Vec::new();
        let test = list(0).into_node();
        if readtoken() != TTHEN {
            synexpect(TTHEN);
        }
        let ifpart = list(0).into_node();
        clauses.push((test, ifpart));
        while readtoken() == TELIF {
            let test = list(0).into_node();
            if readtoken() != TTHEN {
                synexpect(TTHEN);
            }
            let ifpart = list(0).into_node();
            clauses.push((test, ifpart));
        }
        let mut elsepart: Option<Node> = if lasttoken == TELSE {
            list(0).into_node()
        } else {
            tokpushback += 1;
            None
        };
        for (test, ifpart) in clauses.into_iter().rev() {
            elsepart = Some(Node::If(nif {
                test: test.map(Box::new),
                ifpart: ifpart.map(Box::new),
                elsepart: elsepart.map(Box::new),
            }));
        }
        n1 = elsepart;
        t = TFI;
    } else if tok == TWHILE || tok == TUNTIL {
        let got: c_int;
        let ty = if lasttoken == TWHILE { NWHILE } else { NUNTIL };
        let ch1 = list(0).into_node();
        got = readtoken();
        if got != TDO {
            synexpect(TDO);
        }
        let ch2 = list(0).into_node();
        n1 = Some(Node::Binary(nbinary {
            r#type: ty,
            ch1: ch1.map(Box::new),
            ch2: ch2.map(Box::new),
        }));
        t = TDONE;
    } else if tok == TFOR {
        if readtoken() != TWORD || quoteflag != 0 || goodname(wordtext_ptr()) == 0 {
            synerror(c"Bad for loop variable".as_ptr());
        }
        /* the C stores `wordtext` into the node here, before any further
         * token read can overwrite it */
        let var = wordtext_node();
        let mut args: Vec<Node> = Vec::new();
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() == TIN {
            while readtoken() == TWORD {
                args.push(Node::Arg(narg {
                    text: wordtext_node(),
                    backquote: takeglobal(addr_of_mut!(backquotelist)),
                }));
            }
            if lasttoken != TNL && lasttoken != TSEMI {
                synexpect(-1);
            }
        } else {
            /* The implicit `"$@"` of a `for` with no `in`. `dolatstr` is
             * seven bytes ending in the NUL that a word's text keeps, so
             * the value is the static and not what a C reader makes of
             * it. */
            let dolatstr: [u8; 7] = crate::mystring::dolatstr.map(|c| c as u8);
            args.push(Node::Arg(narg {
                text: NodeText::new(BString::from(&dolatstr[..])),
                backquote: Vec::new(),
            }));
            /*
             * Newline or semicolon here is optional (but note
             * that the original Bourne shell only allowed NL).
             */
            if lasttoken != TSEMI {
                tokpushback += 1;
            }
        }
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() != TDO {
            synexpect(TDO);
        }
        let body = list(0).into_node();
        n1 = Some(Node::For(nfor {
            linno: savelinno,
            args,
            body: body.map(Box::new),
            var,
        }));
        t = TDONE;
    } else if tok == TCASE {
        if readtoken() != TWORD {
            synexpect(TWORD);
        }
        let expr = Node::Arg(narg {
            text: wordtext_node(),
            backquote: takeglobal(addr_of_mut!(backquotelist)),
        });
        checkkwd = CHKNL | CHKKWD | CHKALIAS;
        if readtoken() != TIN {
            synexpect(TIN);
        }
        let mut cases: Vec<Node> = Vec::new();
        'next_case: loop {
            checkkwd = CHKNL | CHKKWD;
            t = readtoken();
            while t != TESAC {
                if lasttoken == TLP {
                    readtoken();
                }
                let mut pattern: Vec<Node> = Vec::new();
                loop {
                    if lasttoken < TWORD {
                        synexpect(TWORD);
                    }
                    pattern.push(Node::Arg(narg {
                        text: wordtext_node(),
                        backquote: takeglobal(addr_of_mut!(backquotelist)),
                    }));
                    if readtoken() != TPIPE {
                        break;
                    }
                    readtoken();
                }
                if lasttoken != TRP {
                    synexpect(TRP);
                }
                let body = list(2).into_node();
                cases.push(Node::Clist(nclist {
                    pattern,
                    body: body.map(Box::new),
                }));

                checkkwd = CHKNL | CHKKWD;
                t = readtoken();
                if t != TESAC {
                    if t != TENDCASE {
                        synexpect(TENDCASE);
                    } else {
                        continue 'next_case;
                    }
                }
            }
            break;
        }
        n1 = Some(Node::Case(ncase {
            linno: savelinno,
            expr: Some(Box::new(expr)),
            cases,
        }));
        goto_redir = true;
    } else if tok == TLP {
        let inner = list(0).into_node();
        n1 = Some(Node::Redir(nredir {
            r#type: NSUBSHELL,
            linno: savelinno,
            n: inner.map(Box::new),
            redirect: Vec::new(),
        }));
        t = TRP;
    } else if tok == TBEGIN {
        n1 = list(0).into_node();
        t = TEND;
    } else if tok == TWORD || tok == TREDIR {
        tokpushback += 1;
        return simplecmd();
    } else {
        synexpect(-1);
        /* NOTREACHED */
    }

    if !goto_redir {
        if readtoken() != t {
            synexpect(t);
        }
    }

    /* redir: */
    /* Now check for redirection which may follow command */
    checkkwd = CHKKWD | CHKALIAS;
    let mut redir: Vec<Node> = Vec::new();
    while readtoken() == TREDIR {
        /* The C copies `redirnode` into a local *before* `parsefname`,
         * because the token read inside it can set the global again.
         * Taking ownership of it here is the same guarantee. */
        let mut n2 = takeglobal(addr_of_mut!(redirnode)).unwrap();
        parsefname(&mut n2);
        redir.push(n2);
    }
    tokpushback += 1;
    if !redir.is_empty() {
        if n1.as_ref().map_or(true, |n| n.node_type() != NSUBSHELL) {
            n1 = Some(Node::Redir(nredir {
                r#type: NREDIR,
                linno: savelinno,
                n: n1.map(Box::new),
                redirect: Vec::new(),
            }));
        }
        n1.as_mut().unwrap().nredir_mut().redirect = redir;
    }

    n1
}

// [spec:dash:def:parser.simplecmd-fn]
// [spec:dash:sem:parser.simplecmd-fn]
unsafe fn simplecmd() -> Option<Node> {
    let mut args: Vec<Node> = Vec::new();
    let mut vars: Vec<Node> = Vec::new();
    let mut redir: Vec<Node> = Vec::new();
    let mut savecheckkwd: c_int;
    let savelinno: c_int;

    savecheckkwd = CHKALIAS;
    savelinno = crate::plinno!();
    loop {
        checkkwd = savecheckkwd;
        let tok = readtoken();
        if tok == TWORD {
            let n = Node::Arg(narg {
                text: wordtext_node(),
                backquote: takeglobal(addr_of_mut!(backquotelist)),
            });
            if savecheckkwd != 0 && isassignment(wordtext_ptr()) != 0 {
                vars.push(n);
            } else {
                args.push(n);
                savecheckkwd = 0;
            }
        } else if tok == TREDIR {
            let mut n = takeglobal(addr_of_mut!(redirnode)).unwrap();
            parsefname(&mut n); /* read name of redirection file */
            redir.push(n);
        } else {
            /* The C's `app == &args->narg.next` says the argument list holds
             * exactly one word, which is the name being defined. */
            if tok == TLP && args.len() == 1 && vars.is_empty() && redir.is_empty() {
                let bcmd: *const crate::builtins::builtincmd;
                let name: *const c_char;

                /* We have a function */
                if readtoken() != TRP {
                    synexpect(TRP);
                }
                /* the word becomes the function's name; the C keeps the same
                 * `char *` when it relabels the node */
                let word: narg = args.pop().unwrap().into_narg();
                name = word.text.as_ptr();
                bcmd = crate::exec::find_builtin(name);
                if goodname(name) == 0
                    || (!bcmd.is_null() && ((*bcmd).flags & crate::builtins::BUILTIN_SPECIAL) != 0)
                {
                    synerror(c"Bad function name".as_ptr());
                }
                /* The C relabels the NARG node NDEFUN in place: a union
                 * type-pun that copies `narg.text` (offset 16) into
                 * `ndefun.text` (offset 8) and overwrites the rest.  The
                 * NARG's backquote list is dropped either way. */
                checkkwd = CHKNL | CHKKWD | CHKALIAS;
                let linno = crate::plinno!();
                let body = command();
                return Some(Node::Defun(ndefun {
                    linno,
                    text: word.text,
                    body: body.map(Box::new),
                }));
            }
            /* fall through */
            /* default: */
            tokpushback += 1;
            break;
        }
    }
    /* out: */
    Some(Node::Cmd(ncmd {
        linno: savelinno,
        assign: vars,
        args,
        redirect: redir,
    }))
}

// [spec:dash:def:parser.makename-fn]
// [spec:dash:sem:parser.makename-fn]
unsafe fn makename() -> Node {
    Node::Arg(narg {
        text: wordtext_node(),
        backquote: takeglobal(addr_of_mut!(backquotelist)),
    })
}

// [spec:dash:def:parser.fixredir-fn]
// [spec:dash:sem:parser.fixredir-fn]
//
// Called twice with different owners: from `parsefname` while the node is
// still being built (`err == 0`), and from `expredir` on a tree that may be a
// shared function definition (`err != 0`).  Only the second writes at run
// time, and it only writes `dupfd`, which is why that field is the `Cell`.
pub unsafe fn fixredir(n: &Node, text: *const c_char, err: c_int) {
    /* TRACE(("Fix redir %s %d\n", text, err)); */
    let d = n.ndup();
    if err == 0 {
        *d.vname.borrow_mut() = None;
    }

    if is_digit(*text.offset(0) as c_int) && *text.offset(1) == 0 {
        d.dupfd.set(digit_val(*text.offset(0) as c_int));
    } else if *text.offset(0) == '-' as c_char && *text.offset(1) == 0 {
        d.dupfd.set(-1);
    } else {
        if err != 0 {
            let mut message = b"Bad fd number: ".to_vec();
            message.extend_from_slice(CStr::from_ptr(text).to_bytes());
            crate::error::sh_error(&message);
        } else {
            *d.vname.borrow_mut() = Some(Box::new(makename()));
        }
    }
}

// [spec:dash:def:parser.parsefname-fn]
// [spec:dash:sem:parser.parsefname-fn]
//
// The C reads the redirection node out of the `redirnode` global; here the
// caller has already taken ownership of it, because the `readtoken` below can
// set that global again before this function is done with it.
unsafe fn parsefname(n: &mut Node) {
    if n.node_type() == NHERE {
        checkkwd |= CHKEOFMARK;
    }
    if readtoken() != TWORD {
        synexpect(-1);
    }
    checkkwd &= !CHKEOFMARK;
    if n.node_type() == NHERE {
        /* the C reads the `heredoc` global here, after the token read */
        let mut here: heredoc = takeglobal(addr_of_mut!(heredoc)).unwrap();

        if quoteflag == 0 {
            n.nhere_mut().r#type = NXHERE;
        }
        /* TRACE(("Here document %d\n", n->type)); */
        /* `rmescapes` rewrites the word in place and can only shorten it, so
         * the new terminator is where the delimiter now ends. */
        let mut mark = takeglobal(addr_of_mut!(wordtext));
        rmescapes(mark.as_mut_ptr() as *mut c_char);
        let n_mark = libc::strlen(mark.as_ptr() as *const c_char);
        mark.truncate(n_mark);
        here.eofmark = mark;
        /* `parseheredoc` asked the node whether it was NXHERE; the type is
         * settled above, so the answer travels with the here-document. */
        here.expand = n.nhere().r#type == NXHERE;
        (&mut *addr_of_mut!(heredoclist)).push(here);
    } else if n.node_type() == NTOFD || n.node_type() == NFROMFD {
        fixredir(n, wordtext_ptr(), 0);
    } else {
        n.nfile_mut().fname = Some(Box::new(makename()));
    }
}

/*
 * Input any here documents.
 */

// [spec:dash:def:parser.parseheredoc-fn]
// [spec:dash:sem:parser.parseheredoc-fn]
unsafe fn parseheredoc() {
    let list: Vec<heredoc> = takeglobal(addr_of_mut!(heredoclist));

    for here in list {
        if needprompt != 0 {
            setprompt(2);
        }
        let mark = EofMark::Word(BStr::new(&here.eofmark));
        if !here.expand {
            readtoken1(pgetc(), SQSYNTAX(), mark, here.striptabs);
        } else {
            readtoken1(pgetc_eatbnl(), DQSYNTAX(), mark, here.striptabs);
        }
        let n = Node::Arg(narg {
            text: wordtext_node(),
            backquote: takeglobal(addr_of_mut!(backquotelist)),
        });
        /* `here->here->nhere.doc = n` in the C — the same slot, reached
         * through a shared handle instead of a back pointer.  It is written
         * exactly once, so a second write cannot happen. */
        let _ = here.doc.set(n);
    }
}

// [spec:dash:def:parser.readtoken-fn]
// [spec:dash:sem:parser.readtoken-fn]
unsafe fn readtoken() -> c_int {
    let mut t: c_int;
    let mut kwd: c_int = checkkwd;

    'top: loop {
        t = xxreadtoken();

        /*
         * eat newlines
         */
        if kwd & CHKNL != 0 {
            while t == TNL {
                parseheredoc();
                checkkwd = 0;
                t = xxreadtoken();
            }
        }

        kwd |= checkkwd;
        checkkwd = 0;

        if t != TWORD || quoteflag != 0 {
            break 'top;
        }

        /*
         * check for keywords
         */
        if kwd & CHKKWD != 0 {
            let pp: *const *const c_char = findkwd(wordtext_ptr());

            if !pp.is_null() {
                t = pp.offset_from(parsekwd.0.as_ptr()) as c_int + KWDOFFSET;
                lasttoken = t;
                break 'top;
            }
        }

        if kwd & CHKALIAS != 0 {
            let ap = crate::alias::lookupalias(wordtext_ptr(), 1);
            if !ap.is_null() {
                if *(*ap).val != 0 {
                    pushstring((*ap).val, ap as *mut c_void);
                }
                continue 'top;
            }
        }
        break 'top;
    }
    /* out: */
    t
}

// [spec:dash:def:parser.nlprompt-fn]
// [spec:dash:sem:parser.nlprompt-fn]
unsafe fn nlprompt() {
    crate::plinno!() += 1;
    if doprompt != 0 {
        setprompt(2);
    }
}

// [spec:dash:def:parser.nlnoprompt-fn]
// [spec:dash:sem:parser.nlnoprompt-fn]
unsafe fn nlnoprompt() {
    crate::plinno!() += 1;
    needprompt = doprompt;
}

/*
 * Read the next input token.
 * If the token is a word, we set backquotelist to the list of cmds in
 *	backquotes.  We set quoteflag to true if any part of the word was
 *	quoted.
 * If the token is TREDIR, then we set redirnode to a structure containing
 *	the redirection.
 */

// [spec:dash:def:parser.xxreadtoken-fn]
// [spec:dash:sem:parser.xxreadtoken-fn]
unsafe fn xxreadtoken() -> c_int {
    let mut c: c_int;

    if tokpushback != 0 {
        tokpushback = 0;
        return lasttoken;
    }
    if needprompt != 0 {
        setprompt(2);
    }
    loop {
        /* until token or start of word found */
        let tok: c_int;

        c = pgetc_eatbnl();
        if c == ' ' as c_int || c == '\t' as c_int {
            continue;
        } else if c == '#' as c_int {
            loop {
                c = pgetc();
                if c == '\n' as c_int || c == PEOF {
                    break;
                }
            }
            pungetc();
            continue;
        } else if c == '\n' as c_int {
            nlnoprompt();
            lasttoken = TNL;
            return TNL;
        } else if c == PEOF {
            lasttoken = TEOF;
            return TEOF;
        } else if c == '&' as c_int {
            if pgetc_eatbnl() == '&' as c_int {
                lasttoken = TAND;
                return TAND;
            }
            pungetc();
            lasttoken = TBACKGND;
            return TBACKGND;
        } else if c == '|' as c_int {
            if pgetc_eatbnl() == '|' as c_int {
                lasttoken = TOR;
                return TOR;
            }
            pungetc();
            lasttoken = TPIPE;
            return TPIPE;
        } else if c == ';' as c_int {
            if pgetc_eatbnl() == ';' as c_int {
                lasttoken = TENDCASE;
                return TENDCASE;
            }
            pungetc();
            lasttoken = TSEMI;
            return TSEMI;
        } else if c == '(' as c_int {
            lasttoken = TLP;
            return TLP;
        } else if c == ')' as c_int {
            lasttoken = TRP;
            return TRP;
        }
        tok = readtoken1(c, BASESYNTAX(), EofMark::None, 0);
        if tok != TBLANK {
            return tok;
        }
    }
}

// [spec:dash:def:parser.pgetc-eatbnl-fn]
// [spec:dash:sem:parser.pgetc-eatbnl-fn]
unsafe fn pgetc_eatbnl() -> c_int {
    let mut c: c_int;

    loop {
        c = pgetc();
        if c != '\\' as c_int {
            break;
        }
        if pgetc() != '\n' as c_int {
            pungetc();
            break;
        }

        nlprompt();
    }

    c
}

// [spec:dash:def:parser.pgetc-top-fn]
// [spec:dash:sem:parser.pgetc-top-fn]
unsafe fn pgetc_top(stack: &synstack) -> c_int {
    if stack.syntax == SQSYNTAX() {
        pgetc()
    } else {
        pgetc_eatbnl()
    }
}

mod synstack_ops;

// [spec:dash:def:parser.getmbc-fn]
// [spec:dash:sem:parser.getmbc-fn]
pub unsafe fn getmbc(c: c_int, out: *mut c_char, mode: c_int) -> c_uint {
    let mut c = c;
    let mut out = out;
    let start: *mut c_char = out;
    let mut mbst: libc::mbstate_t = mem::zeroed();
    let mut ml: c_uint = 0;
    let mut ml2: usize;
    let mut wc: libc::wchar_t = 0;
    let mbc: *mut c_char;

    if c >= 0 || c <= PEOF {
        return 0;
    }

    mbc = if (mode & 3) < 2 {
        out.offset(2 + (mode == 1) as isize)
    } else {
        out
    };
    *mbc.offset(ml as isize) = c as c_char;
    loop {
        ml2 = mbrtowc(&mut wc, mbc.offset(ml as isize), 1, &mut mbst);
        ml += 1;
        if ml2 != (-2isize) as usize {
            break;
        }
        if ml as usize >= MB_LEN_MAX {
            break;
        }
        c = pgetc_eoa();
        if c == PEOA || c == PEOF {
            break;
        }
        *mbc.offset(ml as isize) = c as c_char;
    }

    if ml2 == 1 && ml > 1 {
        if mode == 4 && iswblank(wc as u32) != 0 {
            return 1;
        }

        if (mode & 3) < 2 {
            USTPUTC!(CTLMBCHAR, out);
            if mode == 1 {
                USTPUTC!(CTLESC, out);
            }
            USTPUTC!(ml, out);
        }
        STADJUST!(ml, out);
        if (mode & 3) < 2 {
            USTPUTC!(ml, out);
            USTPUTC!(CTLMBCHAR, out);
        }

        return (out as usize - start as usize) as c_uint;
    }

    if ml > 1 {
        pungetn(ml as c_int - 1);
    }

    0
}

/// The most `getmbc` or `conv_escape` can write past the cursor.
///
/// `readtoken1` spells it `CHECKSTRSPACE(MAX(MB_LEN_MAX, 16) + 7, out)` and
/// then lets both of them write through a bare `char *`. Reserving is what
/// makes those writes land in a `Vec`'s spare capacity rather than past the
/// end of it, so the number has to stay the C's.
const MBSLOP: usize = (if MB_LEN_MAX > 16 { MB_LEN_MAX } else { 16 }) + 7;

/// `getmbc` appending to a growable string.
///
/// The C hands it a cursor into the stack block; the byte count it returns is
/// how far that cursor moved, which here is what the caller commits. It can
/// also return 0 or 1 having scribbled on the block past the cursor, and the
/// C leaves that scribble for the next write to overwrite — so does this,
/// because the bytes stay uncommitted.
unsafe fn getmbc_at(out: &mut BString, c: c_int, mode: c_int) -> c_uint {
    out.reserve(MBSLOP);
    let len = out.len();
    getmbc(c, out.as_mut_ptr().add(len) as *mut c_char, mode)
}

// [spec:dash:def:parser.dollarsq-escape-fn]
// [spec:dash:sem:parser.dollarsq-escape-fn]
unsafe fn dollarsq_escape(dest: &mut BString) {
    dest.reserve(MBSLOP);
    let base = dest.len();
    let mut out: *mut c_char = dest.as_mut_ptr().add(base) as *mut c_char;
    /* 10 = length of UXXXXXXXX + NUL */
    let mut str: [c_char; 10] = [0; 10];
    let mut len: c_uint;
    let mut p: *mut c_char;

    len = 0;
    while (len as usize) < mem::size_of_val(&str) - 1 {
        let c = pgetc();

        if c <= PEOF {
            break;
        }

        str[len as usize] = c as c_char;
        len += 1;

        if c == '\'' as c_int {
            break;
        }
    }
    str[len as usize] = 0;

    p = str.as_mut_ptr();
    if *p != 'c' as c_char {
        let ret: c_uint;

        ret = crate::escape::conv_escape(p, out, true);
        p = p.offset((ret >> 4) as isize);
        out = out.offset((ret & 15) as isize);
    } else {
        p = p.offset(1);
        if *p != 0 {
            let conv_ch: c_int;
            let c: c_int;

            c = *p as u8 as c_int;
            p = p.offset(1);

            p = p.offset((((c ^ *p as c_int) | (c ^ '\\' as c_int)) == 0) as isize);

            conv_ch = (c & !((c & 0x40) >> 1) & 0x7f) ^ 0x40;
            USTPUTC!(conv_ch, out);
        }
    }

    pungetn((len as isize - (p as isize - str.as_ptr() as isize)) as c_int);
    let written = out as usize - (dest.as_ptr().add(base) as usize);
    dest.set_len(base + written);
}

/*
 * If eofmark is NULL, read a word or a redirection symbol.  If eofmark
 * is not NULL, read a here document.  In the latter case, eofmark is the
 * word which marks the end of the document and striptabs is true if
 * leading tabs should be stripped from the document.  The argument firstc
 * is the first character of the input token or document.
 *
 * Because C does not have internal subroutines, the original simulates
 * them with goto's: CHECKEND, PARSEREDIR, PARSESUB, PARSEBACKQOLD,
 * PARSEBACKQNEW and PARSEARITH run code that appears at the end of
 * readtoken1.  Here they are plain functions taking the shared C locals
 * (`Rt1`) by `&mut`; they are called from exactly the same places and
 * mutate the state in exactly the same order.
 */

/// The locals of `readtoken1` that its internal subroutines share.
struct Rt1<'a> {
    /// Owned parse contexts, base first and current last. Popping retains the
    /// allocation, matching the C's reuse of its most recently popped level.
    synstack: Vec<synstack>,
    chkeofmark: c_int,
    printesc: bool,
    bqlist: Vec<Option<Node>>,
    dollarsq: c_int,
    c: c_int,
    quotef: c_int,
    /// The word being built. The C's `out` is a `char *` cursor into the
    /// stack block and `stackblock()` is the base; here the base is the
    /// buffer, the cursor is its length, and `STADJUST` is `truncate` or a
    /// `set_len` over bytes a raw writer has already filled.
    out: BString,
    eofmark: EofMark<'a>,
    striptabs: c_int,
    /// Backing store for the `alloca`'d pushback strings in `checkend`,
    /// which likewise accumulate for the life of the call.
    strpool: Vec<Vec<u8>>,
}

impl Rt1<'_> {
    #[inline]
    fn syn(&self) -> &synstack {
        self.synstack.last().unwrap()
    }

    #[inline]
    fn syn_mut(&mut self) -> &mut synstack {
        self.synstack.last_mut().unwrap()
    }
}

/// The label targets inside readtoken1's character switch that are
/// reached by `goto` from more than one case.
enum Lbl {
    None,
    Csquote,
    Quotemark,
    Toggledq,
    EndBackq,
}

// [spec:dash:def:parser.readtoken1-fn]
// [spec:dash:sem:parser.readtoken1-fn]
unsafe fn readtoken1(
    firstc: c_int,
    syntax: *const Syntax,
    eofmark: EofMark<'_>,
    striptabs: c_int,
) -> c_int {
    let mut st = Rt1 {
        synstack: vec![synstack {
            syntax,
            innerdq: 0,
            varpushed: 0,
            dblquote: (syntax == DQSYNTAX()) as c_int,
            backq: 0,
            varnest: 0,
            parenlevel: 0,
            dqvarnest: 0,
        }],
        chkeofmark: checkkwd & CHKEOFMARK,
        printesc: syntax == SQSYNTAX(),
        bqlist: Vec::new(),
        dollarsq: 0,
        c: firstc,
        quotef: 0,
        out: BString::new(Vec::new()),
        eofmark,
        striptabs,
        strpool: Vec::new(),
    };
    let len: usize;

    'loop_: loop {
        /* for each line, until end of word */
        checkend(&mut st); /* set c to PEOF if at end of here document */
        /* Until end of line or end of word */
        loop {
            'body: {
                let fieldsplitting: c_int;
                let mut ml: c_uint;

                fieldsplitting = if st.syn().syntax == BASESYNTAX()
                    && (st.syn().varnest | st.syn().backq) == 0
                {
                    4
                } else {
                    0
                };
                /* The C's CHECKSTRSPACE, which permits max(MB_LEN_MAX, 23)
                 * calls to USTPUTC, is `getmbc_at`'s reserve. */
                ml = getmbc_at(
                    &mut st.out,
                    st.c,
                    fieldsplitting | (if st.printesc { 2 } else { 0 }),
                );
                if ml == 1 {
                    if st.out.is_empty() {
                        return TBLANK;
                    }
                    st.c = pgetc();
                    break 'loop_;
                }
                let grown = st.out.len() + ml as usize;
                st.out.set_len(grown);
                if ml != 0 {
                    break 'body; /* continue */
                }

                let cls = syn_at(st.syn().syntax, st.c);
                let mut lbl = Lbl::None;

                if cls == CNL as c_int {
                    /* '\n' */
                    if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    }
                    st.out.push(st.c as u8);
                    nlprompt();
                    st.c = pgetc_top(st.syn());
                    continue 'loop_; /* continue outer loop */
                } else if cls == CWORD as c_int {
                    st.out.push(st.c as u8);
                } else if cls == CCTL as c_int {
                    if st.c == st.dollarsq {
                        dollarsq_escape(&mut st.out);
                    } else {
                        if (st.eofmark.is_none() as c_int | st.syn().dblquote | st.syn().varnest)
                            != 0
                        {
                            st.out.push(CTLESC as u8);
                        }
                        st.out.push(st.c as u8);
                    }
                } else if cls == CBACK as c_int {
                    /* backslash */
                    st.c = pgetc();
                    if st.c == PEOF {
                        st.out.push(CTLESC as u8);
                        st.out.push('\\' as u8);
                        pungetc();
                    } else {
                        if (st.syn().dblquote | st.syn().backq) != 0
                            && st.c != '\\' as c_int
                            && st.c != '`' as c_int
                            && st.c != '$' as c_int
                            && (st.c != '"' as c_int
                                || (!st.eofmark.is_none() && st.syn().varnest == 0))
                            && (st.c != '}' as c_int || st.syn().varnest == 0)
                        {
                            st.out.push(CTLESC as u8);
                            st.out.push('\\' as u8);
                        }
                        st.quotef += 1;

                        ml = getmbc_at(&mut st.out, st.c, 1);
                        let grown = st.out.len() + ml as usize;
                        st.out.set_len(grown);
                        if ml == 0 {
                            st.out.push(CTLESC as u8);
                            st.out.push(st.c as u8);
                        }
                    }
                } else if cls == CSQUOTE as c_int {
                    lbl = Lbl::Csquote;
                } else if cls == CDQUOTE as c_int {
                    st.syn_mut().syntax = DQSYNTAX();
                    st.syn_mut().dblquote = 1;
                    lbl = Lbl::Toggledq;
                } else if cls == CENDQUOTE as c_int {
                    if !st.eofmark.is_none() && st.syn().varnest == 0 {
                        st.out.push(st.c as u8);
                    } else {
                        if st.syn().dqvarnest == 0 {
                            if st.dollarsq != 0 {
                                /* `*out = '\0'; out = p + strlen(p);` — a NUL
                                 * written by a `$'\0'` escape ends the word,
                                 * so the cursor winds back to it. */
                                let end =
                                    st.out.iter().position(|&b| b == 0).unwrap_or(st.out.len());
                                st.out.truncate(end);
                                st.dollarsq = 0;
                            }

                            st.syn_mut().syntax = BASESYNTAX();
                            st.syn_mut().dblquote = 0;
                        }

                        st.quotef += 1;

                        if st.c == '"' as c_int {
                            lbl = Lbl::Toggledq;
                        } else {
                            lbl = Lbl::Quotemark;
                        }
                    }
                } else if cls == CVAR as c_int {
                    /* '$' */
                    if parsesub(&mut st) {
                        /* parse substitution */
                        lbl = Lbl::Csquote;
                    }
                } else if cls == CENDVAR as c_int {
                    /* '}' */
                    if st.syn().innerdq == 0 && st.syn().varnest > 0 {
                        st.syn_mut().varnest -= 1;
                        if st.syn().varnest == 0 && st.syn().varpushed != 0 {
                            synstack_ops::pop(&mut st.synstack);
                        } else if st.syn().dqvarnest > 0 {
                            st.syn_mut().dqvarnest -= 1;
                        }
                        if st.chkeofmark == 0 {
                            st.c = CTLENDVAR;
                        }
                    }
                    st.out.push(st.c as u8);
                } else if cls == CLP as c_int {
                    /* '(' in arithmetic */
                    st.syn_mut().parenlevel += 1;
                    st.out.push(st.c as u8);
                } else if cls == CRP as c_int {
                    /* ')' in arithmetic */
                    if st.syn().parenlevel > 0 {
                        st.syn_mut().parenlevel -= 1;
                    } else if pgetc_eatbnl() == ')' as c_int {
                        synstack_ops::pop(&mut st.synstack);
                        if st.chkeofmark != 0 {
                            st.out.push(st.c as u8);
                        } else {
                            st.c = CTLENDARI;
                        }
                    } else {
                        /*
                         * unbalanced parens
                         *  (don't 2nd guess - no error)
                         */
                        pungetc();
                    }
                    st.out.push(st.c as u8);
                } else if cls == CBQUOTE as c_int {
                    /* '`' */
                    if st.syn().backq == 2 {
                        lbl = Lbl::EndBackq;
                    } else {
                        st.out.push('`' as u8);
                        parsebackq(&mut st, 1);
                    }
                } else if cls == CEOF as c_int {
                    break 'loop_; /* exit outer loop */
                } else {
                    /* default: */
                    if st.c == ')' as c_int && st.syn().backq == 1 {
                        lbl = Lbl::EndBackq;
                    } else if fieldsplitting != 0 {
                        break 'loop_; /* exit outer loop */
                    } else {
                        st.out.push(st.c as u8);
                    }
                }

                /* the goto-linked tails of the switch above */
                loop {
                    match lbl {
                        Lbl::None => break,
                        Lbl::Csquote => {
                            /* csquote: */
                            st.syn_mut().syntax = SQSYNTAX();
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::Quotemark => {
                            /* quotemark: */
                            if st.eofmark.is_none() {
                                st.out.push(CTLQUOTEMARK as u8);
                            }
                            lbl = Lbl::None;
                        }
                        Lbl::Toggledq => {
                            /* toggledq: */
                            if st.syn().varnest != 0 {
                                st.syn_mut().innerdq ^= 1;
                            }
                            lbl = Lbl::Quotemark;
                        }
                        Lbl::EndBackq => {
                            /* end_backq: */
                            synstack_ops::pop(&mut st.synstack);
                            st.printesc = false;
                            st.out.push(st.c as u8);
                            lbl = Lbl::None;
                        }
                    }
                }
            }
            st.c = pgetc_top(st.syn());
        }
    }
    /* endword: */
    if st.syn().syntax == ARISYNTAX() {
        synerror(c"Missing '))'".as_ptr());
    }
    if (st.syn().syntax != BASESYNTAX() && st.eofmark.is_none()) || st.syn().backq != 0 {
        synerror(c"Unterminated quoted string".as_ptr());
    }
    if st.syn().varnest != 0 {
        /* { */
        synerror(c"Missing '}'".as_ptr());
    }
    st.out.push(b'\0');
    len = st.out.len();
    if st.eofmark.is_none() {
        if (st.c == '>' as c_int || st.c == '<' as c_int)
            && st.quotef == 0
            && len <= 2
            && (st.out[0] == 0 || is_digit(st.out[0] as i8 as c_int))
        {
            parseredir(&mut st);
            lasttoken = TREDIR;
            return TREDIR;
        } else {
            pungetc();
        }
    }
    quoteflag = st.quotef;
    backquotelist = mem::take(&mut st.bqlist);
    /* `grabstackblock(len)` reserved the bytes the C had been writing into
     * scratch space, which is what made `wordtext` outlive the next token.
     * Moving the buffer out is the same guarantee. */
    wordtext = mem::take(&mut st.out);
    lasttoken = TWORD;
    TWORD
}
/* end of readtoken routine */

/*
 * Check to see whether we are at the end of the here document.  When this
 * is called, c is set to the first character of the next input line.  If
 * we are at the end of the here document, this routine sets the c to PEOF.
 */

/* checkend: */
unsafe fn checkend(st: &mut Rt1<'_>) {
    if let Some(mark) = st.eofmark.real() {
        let markloc: usize;
        let mut i: usize;
        let mut more_heredoc = false;

        if st.striptabs != 0 {
            while st.c == '\t' as c_int {
                st.c = pgetc();
            }
        }

        /* The C reads the candidate delimiter into the word being built and
         * then winds the cursor back to `markloc`, so the scratch is the tail
         * of the same buffer. */
        markloc = st.out.len();
        i = 0;
        loop {
            st.out.push(st.c as u8);
            if i == mark.len() {
                /* `*p == '\0'` — the delimiter's terminator */
                break;
            }
            if st.c != mark[i] as i8 as c_int {
                more_heredoc = true; /* goto more_heredoc */
                break;
            }

            st.c = pgetc();
            i += 1;
        }

        if !more_heredoc {
            if st.c == '\n' as c_int || st.c == PEOF {
                st.c = PEOF;
                nlnoprompt();
            } else {
                more_heredoc = true;
            }
        }

        if more_heredoc {
            let mut len: usize;

            /* more_heredoc: */
            let start = markloc + 1;
            len = st.out.len() - start;

            if len != 0 {
                len -= (st.c <= PEOF) as usize;
                st.c = st.out[start - 1] as i8 as c_int;

                if len != 0 {
                    let str: *mut c_char;

                    /* str = alloca(len + 1) */
                    let mut copy: Vec<u8> = Vec::with_capacity(len + 1);
                    copy.extend_from_slice(&st.out[start..start + len]);
                    copy.push(0);
                    st.strpool.push(copy);
                    let last = st.strpool.len() - 1;
                    str = st.strpool[last].as_mut_ptr() as *mut c_char;

                    pushstring(str, ptr::null_mut());
                }
            }
        }

        st.out.truncate(markloc);
    }
    /* goto checkend_return; */
}

/*
 * Parse a redirection operator.  The variable "out" points to a string
 * specifying the fd to be redirected.  The variable "c" contains the
 * first character of the redirection operator.
 */

/* parseredir: */
unsafe fn parseredir(st: &mut Rt1<'_>) {
    let fdc: c_char = st.out[0] as c_char;
    /* The C carves one `struct nfile` and then decides what it is by
     * assigning `np->type`, re-allocating only because `nhere` is smaller.
     * The arm has to be chosen up front here, so the type and the fd are
     * worked out first and the node built at the end. */
    let mut fd: c_int;
    let ty: c_int;
    let mut doc: Option<heredoc_body> = None;

    if st.c == '>' as c_int {
        fd = 1;
        st.c = pgetc_eatbnl();
        if st.c == '>' as c_int {
            ty = NAPPEND;
        } else if st.c == '|' as c_int {
            ty = NCLOBBER;
        } else if st.c == '&' as c_int {
            ty = NTOFD;
        } else {
            ty = NTO;
            pungetc();
        }
    } else {
        /* c == '<' */
        fd = 0;
        st.c = pgetc_eatbnl();
        if st.c == '<' as c_int {
            ty = NHERE;
            let slot: heredoc_body = Rc::new(OnceCell::new());
            let mut here = heredoc {
                doc: Rc::clone(&slot),
                expand: false,
                eofmark: BString::new(Vec::new()),
                striptabs: 0,
            };
            doc = Some(slot);
            st.c = pgetc_eatbnl();
            if st.c == '-' as c_int {
                here.striptabs = 1;
            } else {
                here.striptabs = 0;
                pungetc();
            }
            heredoc = Some(here);
        } else if st.c == '&' as c_int {
            ty = NFROMFD;
        } else if st.c == '>' as c_int {
            ty = NFROMTO;
        } else {
            ty = NFROM;
            pungetc();
        }
    }
    if fdc != '\0' as c_char {
        fd = digit_val(fdc as c_int);
    }
    redirnode = Some(match ty {
        NTOFD | NFROMFD => Node::Dup(ndup {
            r#type: ty,
            fd,
            dupfd: Cell::new(0),
            vname: RefCell::new(None),
        }),
        NHERE => Node::Here(nhere {
            r#type: NHERE,
            fd,
            doc: doc.unwrap(),
        }),
        _ => Node::File(nfile {
            r#type: ty,
            fd,
            fname: None,
            expfname: RefCell::new(None),
        }),
    });
    /* goto parseredir_return; */
}

/*
 * Parse a substitution.  At this point, we have read the dollar sign
 * and nothing else.
 *
 * Returns true where the C does `goto csquote`, i.e. jumps back into the
 * CSQUOTE arm of readtoken1's switch instead of returning normally.
 */

/* parsesub: */
unsafe fn parsesub(st: &mut Rt1<'_>) -> bool {
    let mut newsyn: *const Syntax = st.syn().syntax;
    static types: [u8; 6] = *b"}-+?=\0";
    let mut subtype: c_int;

    st.out.push('$' as u8);

    st.c = pgetc_eatbnl();
    if st.c == '(' as c_int {
        /* $(command) or $((arith)) */
        st.out.push(st.c as u8);
        if pgetc_eatbnl() == '(' as c_int {
            parsearith(st);
        } else {
            pungetc();
            parsebackq(st, 0);
        }
    } else if st.c == '\'' as c_int && syn_at(newsyn, '&' as c_int) != 0 {
        st.out.pop();
        st.dollarsq = '\\' as c_int;
        return true; /* goto csquote */
    } else if st.c == '{' as c_int || is_name(st.c) || is_special(st.c) != 0 {
        let typeloc: usize = st.out.len();
        let mut badsub = false;

        /* `STADJUST(chkeofmark == 0, out)` steps over the byte the CTLVAR
         * subtype lands in below; nothing reads it in between, so the
         * placeholder value is not observable. */
        st.out.resize(typeloc + (st.chkeofmark == 0) as usize, 0);
        subtype = VSNORMAL;
        if st.c == '{' as c_int {
            if st.chkeofmark != 0 {
                st.out.push('{' as u8);
            }
            st.c = pgetc_eatbnl();
            subtype = 0;
        }
        'varname: loop {
            if is_name(st.c) {
                loop {
                    st.out.push(st.c as u8);
                    st.c = pgetc_eatbnl();
                    if !is_in_name(st.c) {
                        break;
                    }
                }
            } else if is_digit(st.c) {
                loop {
                    st.out.push(st.c as u8);
                    st.c = pgetc_eatbnl();
                    if !((subtype <= 0 || subtype >= VSLENGTH) && is_digit(st.c)) {
                        break;
                    }
                }
            } else if st.c != '}' as c_int {
                let mut cc = st.c;

                st.c = pgetc_eatbnl();

                if subtype == 0 && cc == '#' as c_int {
                    subtype = VSLENGTH;

                    if st.c == '_' as c_int || libc::isalnum(st.c) != 0 {
                        if st.chkeofmark != 0 {
                            st.out.push('#' as u8);
                        }
                        continue 'varname; /* goto varname */
                    }

                    cc = st.c;
                    st.c = pgetc_eatbnl();
                    if cc == '}' as c_int || st.c != '}' as c_int {
                        pungetc();
                        subtype = 0;
                        st.c = cc;
                        cc = '#' as c_int;
                    } else if st.chkeofmark != 0 {
                        st.out.push('#' as u8);
                    }
                }

                if is_special(cc) == 0 {
                    if subtype == VSLENGTH {
                        subtype = 0;
                    }
                    badsub = true; /* goto badsub */
                    break 'varname;
                }

                st.out.push(cc as u8);
            } else {
                badsub = true; /* goto badsub */
                break 'varname;
            }
            break 'varname;
        }

        if badsub {
            /* badsub: */
            pungetc();
        } else if subtype == 0 {
            let cc = st.c;

            if st.chkeofmark != 0 {
                st.out.push(st.c as u8);
            }

            if st.c == '%' as c_int || st.c == '#' as c_int {
                subtype = if st.c == '#' as c_int {
                    VSTRIMLEFT
                } else {
                    VSTRIMRIGHT
                };
                st.c = pgetc_eatbnl();
                if st.c == cc {
                    if st.chkeofmark != 0 {
                        st.out.push(st.c as u8);
                    }
                    subtype += 1;
                } else {
                    pungetc();
                }

                newsyn = BASESYNTAX();
            } else {
                if st.c == ':' as c_int {
                    subtype = VSNUL;
                    st.c = pgetc_eatbnl();
                    if st.chkeofmark != 0 {
                        st.out.push(st.c as u8);
                    }
                    /*FALLTHROUGH*/
                }
                /* default: */
                /* The search runs over the whole array, terminator
                 * included, because that is what `strchr` does: a NUL
                 * `c` lands on index 5 rather than missing. */
                if let Some(at) = types.iter().position(|&b| b as c_int == st.c) {
                    subtype |= at as c_int + VSNORMAL;
                }
            }
        } else {
            if subtype == VSLENGTH && st.c != '}' as c_int {
                subtype = 0;
            }
            /* badsub: */
            pungetc();
        }

        if newsyn == ARISYNTAX() {
            newsyn = DQSYNTAX();
        }

        if (newsyn != st.syn().syntax || st.syn().innerdq != 0) && subtype != VSNORMAL {
            synstack_ops::push(&mut st.synstack, newsyn);

            st.syn_mut().varpushed += 1;
            st.syn_mut().dblquote = (newsyn != BASESYNTAX()) as c_int;
        }

        if subtype != VSNORMAL {
            st.syn_mut().varnest += 1;
            if st.syn().dblquote != 0 {
                st.syn_mut().dqvarnest += 1;
            }
        }
        if st.chkeofmark == 0 {
            st.out[typeloc - 1] = CTLVAR as u8;
            st.out[typeloc] = (subtype | VSBIT) as u8;
            st.out.push(b'=');
        }
    } else {
        pungetc();
    }

    /* goto parsesub_return; */
    false
}

/*
 * Called to parse command substitutions.  oldstyle is set if the command
 * is enclosed inside `...` rather than $(...).
 */

/* parsebackq: */
unsafe fn parsebackq(st: &mut Rt1<'_>, oldstyle: c_int) {
    let mut saveprompt: c_int = 0;
    let saveheredoclist: Vec<heredoc>;
    let nlpp: usize;
    let n: Option<Node>;
    let mut ml: c_uint;
    /* `grabstackstr(pout)` had to reserve the backquote's text because
     * `list(2)` builds on the same stack; owning it says the same thing, and
     * it has to outlive the `popfile` below because `setinputstring` reads
     * through the pointer rather than copying. */
    let mut pstr: BString = BString::new(Vec::new());
    let str: BString;

    if st.chkeofmark != 0 {
        synstack_ops::push(&mut st.synstack, BASESYNTAX());
        st.syn_mut().backq = oldstyle + 1;
        st.printesc = true;
        /* goto parsebackq_out; */
        if oldstyle != 0 {
            tokpushback = 0;
        }
        return;
    }
    /* `STADJUST(oldstyle - 1, out)` drops the '(' of `$(` and leaves the '`'
     * of a backquote in place; either way the last byte becomes CTLBACKQ. */
    if oldstyle == 0 {
        st.out.pop();
    }
    let last = st.out.len() - 1;
    st.out[last] = CTLBACKQ as u8;
    /* The word so far is parked while `list(2)` runs, which is what
     * `grabstackblock(savelen)` bought the C. */
    str = mem::take(&mut st.out);
    if oldstyle != 0 {
        /* We must read until the closing backquote, giving special
        treatment to some slashes, and then push the string and
        reread it as input, interpreting it normally.  */
        let mut done = false;
        let mut pc: c_int;

        while !done {
            'bqbody: {
                if needprompt != 0 {
                    setprompt(2);
                }
                pc = pgetc_eatbnl();
                if pc == '`' as c_int {
                    done = true;
                } else if pc == '\\' as c_int {
                    pc = pgetc();
                    if pc != '\\' as c_int
                        && pc != '`' as c_int
                        && pc != '$' as c_int
                        && (st.syn().dblquote == 0 || pc != '"' as c_int)
                    {
                        pstr.push(b'\\');
                    }
                    ml = getmbc_at(&mut pstr, pc, 2);
                    let grown = pstr.len() + ml as usize;
                    pstr.set_len(grown);
                    if ml != 0 {
                        break 'bqbody; /* continue */
                    }
                } else if pc == PEOF {
                    synerror(c"EOF in backquote substitution".as_ptr());
                } else if pc == '\n' as c_int {
                    nlnoprompt();
                }
                pstr.push(pc as u8);
            }
        }
        /* `pout[-1] = '\0'` — over the closing backquote the loop just
         * wrote, which is why the buffer is never empty here. */
        let last = pstr.len() - 1;
        pstr[last] = 0;
        setinputstring(pstr.as_mut_ptr() as *mut c_char);
    }
    /* The C walks to the tail of `bqlist` and appends an empty cell, then
     * fills its `n` after the recursive parse.  Reserving the slot first is
     * the same order; nothing else can append to this list while `list(2)`
     * runs, because `bqlist` is a local of *this* `readtoken1`. */
    nlpp = st.bqlist.len();
    st.bqlist.push(None);

    saveheredoclist = takeglobal(addr_of_mut!(heredoclist));

    if oldstyle != 0 {
        saveprompt = doprompt;
        doprompt = 0;
    }

    n = list(2).into_node();

    if oldstyle != 0 {
        doprompt = saveprompt;
    } else {
        if readtoken() != TRP {
            synexpect(TRP);
        }
        setinputstring(ptr::addr_of!(crate::mystring::nullstr) as *const c_char as *mut c_char);
    }

    parseheredoc();
    heredoclist = saveheredoclist;

    st.bqlist[nlpp] = n;
    /* Start reading from old file again. */
    popfile();

    st.out = str;

    /* parsebackq_out: */
    if oldstyle != 0 {
        /* Ignore any pushed back tokens left from the backquote
         * parsing.
         */
        tokpushback = 0;
    }
}

/*
 * Parse an arithmetic expansion (indicate start of one and set state)
 */
/* parsearith: */
unsafe fn parsearith(st: &mut Rt1<'_>) {
    synstack_ops::push(&mut st.synstack, ARISYNTAX());
    st.syn_mut().dblquote = 1;
    if st.chkeofmark != 0 {
        st.out.push(st.c as u8);
    } else {
        /* `STADJUST(-1); out[-1] = CTLARI` — drop the second '(' of `$((`
         * and relabel the '$'. */
        st.out.pop();
        let last = st.out.len() - 1;
        st.out[last] = CTLARI as u8;
    }
    /* goto parsearith_return; */
}

/*
 * Return of a legal variable name (a letter or underscore followed by zero or
 * more letters, underscores, and digits).
 */

// [spec:dash:def:parser.endofname-fn]
// [spec:dash:sem:parser.endofname-fn]
pub unsafe fn endofname(name: *const c_char) -> *mut c_char {
    let mut p: *mut c_char;

    p = name as *mut c_char;
    if !is_name(*p as c_int) {
        return p;
    }
    loop {
        p = p.offset(1);
        if *p == 0 {
            break;
        }
        if !is_in_name(*p as c_int) {
            break;
        }
    }
    p
}

/*
 * Called when an unexpected token is read during the parse.  The argument
 * is the token that is expected, or -1 if more than one type of token can
 * occur at this point.
 */

// [spec:dash:def:parser.synexpect-fn]
// [spec:dash:sem:parser.synexpect-fn]
unsafe fn synexpect(token: c_int) -> ! {
    let mut msg: [c_char; 64] = [0; 64];
    let mut message = Vec::new();

    message.extend_from_slice(CStr::from_ptr(tokname.0[lasttoken as usize]).to_bytes());
    message.extend_from_slice(b" unexpected");
    if token >= 0 {
        message.extend_from_slice(b" (expecting ");
        message.extend_from_slice(CStr::from_ptr(tokname.0[token as usize]).to_bytes());
        message.push(b')');
    }
    let copied = message.len().min(msg.len() - 1);
    core::ptr::copy_nonoverlapping(message.as_ptr(), msg.as_mut_ptr() as *mut u8, copied);
    synerror(msg.as_ptr());
    /* NOTREACHED */
}

// [spec:dash:def:parser.synerror-fn]
// [spec:dash:sem:parser.synerror-fn]
#[allow(unreachable_code)]
unsafe fn synerror(msg: *const c_char) -> ! {
    errlinno = crate::plinno!();
    let mut message = b"Syntax error: ".to_vec();
    message.extend_from_slice(CStr::from_ptr(msg).to_bytes());
    crate::error::sh_error(&message);
    /* NOTREACHED */
    unreachable!()
}

// [spec:dash:def:parser.setprompt-fn]
// [spec:dash:sem:parser.setprompt-fn]
#[inline(never)]
unsafe fn setprompt(which: c_int) {
    let show: c_int;

    needprompt = 0;
    whichprompt = which;

    /* #ifdef SMALL: show = 1 */
    show = (!crate::histedit::editing_active()) as c_int;
    if show != 0 && crate::input::cur_pf().nleft == 0 {
        /* `pushstackmark(&smark, stackblocksize())` bounded the prompt
         * `expandstr` had left in the region for `out2str` to read.  The
         * expansion buffer is owned, so there is nothing to bound. */
        let prompt = CStr::from_ptr(getprompt(ptr::null_mut())).to_bytes();
        let _ = (*crate::output::stderr()).write_all(prompt);
    }
}

// [spec:dash:def:parser.expandstr-fn]
// [spec:dash:sem:parser.expandstr-fn]
pub unsafe fn expandstr(ps: *const c_char) -> *const c_char {
    let file_stop: usize;
    let savehandler: *mut jmploc;
    let saveheredoclist: Vec<heredoc>;
    let mut result: *const c_char;
    let saveprompt: c_int;
    let mut jmploc: crate::error::jmploc = crate::error::jmploc::new();
    let err: c_int;

    file_stop = crate::input::cur_mark();

    /* XXX Fix (char *) cast. */
    setinputstring(ps as *mut c_char);

    saveheredoclist = takeglobal(addr_of_mut!(heredoclist));
    saveprompt = doprompt;
    doprompt = 0;
    needprompt = 0;
    result = ps;
    savehandler = handler;
    /* `if (unlikely(err = setjmp(jmploc.loc))) goto out;` — handlers in
     * this port are established by `eval::setjmp_catch`, not a real
     * `setjmp`, so the body goes in the closure and everything after the
     * call is the `out:` label. Raw pointers rather than captures keep
     * the C's aliasing (the closure writes locals the tail then reads).
     * The C's `union node n` is a bare local it never reads after the
     * call, so it lives inside the closure here. */
    let jl: *mut crate::error::jmploc = addr_of_mut!(jmploc);
    let resultp: *mut *const c_char = addr_of_mut!(result);
    err = crate::eval::setjmp_catch(jl, || unsafe {
        handler = jl;

        readtoken1(pgetc_eatbnl(), DQSYNTAX(), EofMark::Fake, 0);

        let n = Node::Arg(narg {
            text: wordtext_node(),
            backquote: takeglobal(addr_of_mut!(backquotelist)),
        });

        expandarg(&n, None, EXP_QUOTED);
        /* The C reads the expansion back as `stackblock()`; the expansion
         * buffer is owned now, so the read is named.  The C's pointer was
         * live only until the next `stalloc`; this one is live until the
         * next expansion, which is a superset. */
        *resultp = crate::expand::expansion_result() as *const c_char;
    });

    /* out: */
    restore_handler_expandarg(savehandler, err);

    doprompt = saveprompt;
    unwindfiles(file_stop);
    heredoclist = saveheredoclist;

    result
}

/*
 * called by editline -- any expansions to the prompt
 *    should be added here.
 */

// [spec:dash:def:parser.getprompt-fn]
// [spec:dash:sem:parser.getprompt-fn]
pub unsafe fn getprompt(unused: *mut c_void) -> *const c_char {
    let prompt: *const c_char;

    match whichprompt {
        1 => {
            prompt = crate::var::ps1val();
        }
        2 => {
            prompt = crate::var::ps2val();
        }
        /* default: falls into case 0 outside DEBUG builds */
        _ => {
            return ptr::addr_of!(crate::mystring::nullstr) as *const c_char;
        }
    }

    expandstr(prompt)
}

/// The C reaches `parsekwd` through `mystring.c`'s `findstring`, a generic
/// `bsearch` over an array of `char *`. This is that function's only
/// instantiation in the port, and `strcmp` over the table is plain byte
/// order — `parsekwd` is ASCII and sorted — so `<[u8]>::cmp` is the C
/// comparator rather than an approximation of it.
///
/// The result stays a pointer *into* `parsekwd` because `readtoken1`
/// recovers the token code by subtracting the base.
// [spec:dash:def:parser.findkwd-fn]
// [spec:dash:sem:parser.findkwd-fn]
pub unsafe fn findkwd(s: *const c_char) -> *const *const c_char {
    let key = core::ffi::CStr::from_ptr(s).to_bytes();
    match parsekwd
        .0
        .binary_search_by(|&kwd| core::ffi::CStr::from_ptr(kwd).to_bytes().cmp(key))
    {
        Ok(i) => parsekwd.0.as_ptr().add(i),
        Err(_) => ptr::null(),
    }
}

// ---------------------------------------------------------------------
// src/parser.h inline functions
// ---------------------------------------------------------------------

// [spec:dash:def:parser.goodname-fn]
// [spec:dash:sem:parser.goodname-fn]
pub unsafe fn goodname(p: *const c_char) -> c_int {
    (*endofname(p) == 0) as c_int
}

// [spec:dash:def:parser.parser-eof-fn]
// [spec:dash:sem:parser.parser-eof-fn]
pub unsafe fn parser_eof() -> c_int {
    (tokpushback != 0 && lasttoken == TEOF) as c_int
}

// ---------------------------------------------------------------------
// C library entry points the libc crate does not declare.
// ---------------------------------------------------------------------

unsafe extern "C" {
    fn mbrtowc(
        pwc: *mut libc::wchar_t,
        s: *const c_char,
        n: usize,
        ps: *mut libc::mbstate_t,
    ) -> usize;
    fn iswblank(wc: u32) -> c_int;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::CStr0;

    // [spec:dash:sem:parser.findkwd-fn/test]
    #[test]
    fn findkwd_preserves_the_sorted_table_contract() {
        unsafe {
            let mut previous: Option<&[u8]> = None;

            for (i, &keyword) in parsekwd.0.iter().enumerate() {
                let bytes = core::ffi::CStr::from_ptr(keyword).to_bytes();
                if let Some(previous) = previous {
                    assert!(previous < bytes, "parsekwd must be strictly sorted");
                }
                previous = Some(bytes);

                let found = findkwd(keyword);
                assert!(!found.is_null(), "keyword {bytes:?} was not found");
                assert_eq!(*found, keyword);
                assert_eq!(found.offset_from(parsekwd.0.as_ptr()) as usize, i);

                let mut longer = bytes.to_vec();
                longer.push(b'x');
                longer.push(0);
                assert!(findkwd(longer.as_ptr().cast()).is_null());
            }

            for missing in ["", "cas", "integer", "zebra"] {
                assert!(findkwd(CStr0::new(missing).p()).is_null());
            }

            let non_ascii = [0xff_u8, 0];
            assert!(findkwd(non_ascii.as_ptr().cast()).is_null());
        }
    }
}
